### ISSUE TITLE
Add user's personal stats

### ISSUE THREAD

**Issue by 0BuRner** [akiver/CSGO-Demos-Manager#10]
Add global statistics of *the user* (win/lose/draw ratio, kd ratio, hs ratio, avg rating, ...) in the main page.

**Comment by roknir** [comment]
This would be a great feature that I would find useful.  For example, I would rather see how many 1Ks I had in a given demo in the main page than how many 1Ks were in the demo in total.  Though seeing the totals for all players in the demo is useful too.  Maybe make it show your personal stats by default but have some sort of filter toggle to display the total stats?

**Comment by roknir** [comment]
One other thought... it might be cool to be able to focus on a specific player when doing demo analysis.  (Basically, I might care about more than just myself and the totals in the demos... it could be good to filter to a specific other player too.)

**Comment by akiver** [comment]
An option to display only user's stats has been added, dedicated view for each player will come later, I think we can close this issue.
