### ISSUE TITLE
Rank Stats - Date Scale

### ISSUE THREAD

**Issue by free-style** [akiver/CSGO-Demos-Manager#100]
My apologies if this is in the wrong place... 

I'm trying to figure out how I can look at date-scaled view of rank progression in the stats section.  Since the only data points are the exact dates of the demos, it is difficult to determine the length of time you spent at anyone rank.  (I used to sporadically download demos... now I try to download them all)

Is this already possible?

Thanks!
(Amazing program, btw... awesome... thanks for it!)

**Comment by akiver** [comment]
I added the ability to scale the graph by day or month.
I think it should solve this problem.

**Comment by free-style** [comment]
You are awesome.    Can't wait to try it !
  
  

  
  
>
