### ISSUE TITLE
Demos analyzing in batches of four

### ISSUE THREAD

**Issue by MrLawbreaker** [akiver/CSGO-Demos-Manager#101]
It has been i awhile since this was introduced but i just noticed that demos are always being analyzed in batches of four, and the next batch only start when the previous four have finished. My suggestion is to have the next demo start analyzing as soon as another one is ready.

**Comment by Skaronator** [comment]
Would be nice to have a setting to define the number. Default value should based on cpu thread count (not core).

A Extreme Setting would be nice as well, which analyse as much as possible demos at the same time but it should keep the CPU usage below 80%.
