### ISSUE TITLE
Rank and outcome issues after update 

### ISSUE THREAD

**Issue by neXib** [akiver/CSGO-Demos-Manager#105]
Usually when analyzing a new match after rank update it would update rank for an account, but it's not happening now.

Also win,lose, draw doesn't update until quitting and reloading the program for new matches, and also didn't update win,loss, draw when clicking "Show more demos". 

It also doesn't show win,loss, draw for faceit games eventhough it's the same Steam profile, does it go by account name?

**Comment by Skaronator** [comment]
> Also win,lose, draw doesn't update until quitting and reloading the program for new matches, and also didn't update win,loss, draw when clicking "Show more demos".

Can confirm that, UI doesn't update after the analysis is done. After refresh (F5) it appears correctly.
