### ISSUE TITLE
Could you make a Language API?

### ISSUE THREAD

**Issue by 872517414** [akiver/CSGO-Demos-Manager#113]
I think this is necessary.
:D

**Comment by akiver** [comment]
I'm not sure to understand what do you mean by language api?

**Comment by 872517414** [comment]
The translation?This is a good program,but my friend can't use it.Because their English are not very well.(me too.):(

**Comment by akiver** [comment]
I added a translation system, you are free to translate it in your language.
More details are in the [readme](https://github.com/akiver/CSGO-Demos-Manager#translations)
