### ISSUE TITLE
Question Json "id"

### ISSUE THREAD

**Issue by Skaronator** [akiver/CSGO-Demos-Manager#114]
This is just a question, not a bug report.

The "id" in the json export is it a unique ID? Is it even unique if you mix up with esea, faceit and cevo demos?

**Comment by akiver** [comment]
It's based on the demo's header data and file creation date (seconds).

`id = header.MapName.Replace("/", "") + "_" + seconds + header.SignonLength + header.PlaybackFrames`

**Comment by Skaronator** [comment]
alright that should be unique enough
