### ISSUE TITLE
Server demos unable to be analyzed in 2.8.1

### ISSUE THREAD

**Issue by sambooo** [akiver/CSGO-Demos-Manager#119]
I'm unable to analyse any of the recent 10mans from my server, getting the standard 'error occurred' message. Notably the analysis does at least start, but seems to break before getting to the end of the first round. Might be related to the knife round or some other aspect of the Pug Setup plugin used on my server, but I used to be able to analyse these demos so something must have changed.

Links to a few examples:
https://dl.dropboxusercontent.com/u/30829668/demos/pug_de_overpass_2016-08-14_23.dem
https://dl.dropboxusercontent.com/u/30829668/demos/pug_de_cache_2016-08-10_23.dem

**Comment by akiver** [comment]
Change the source to eBot, it works.
Be aware that demos from community servers that don't use eBot or valve match system may not work as excepted.

**Comment by sambooo** [comment]
Works as expected now, thanks.

Is this documented anywhere?

**Comment by akiver** [comment]
http://csgo-demos-manager.com/support in analyze section.
