### ISSUE TITLE
Player appears on the wrong side.

### ISSUE THREAD

**Issue by ghost** [akiver/CSGO-Demos-Manager#121]
![untitled](https://cloud.githubusercontent.com/assets/15868811/17707771/386f16dc-63e2-11e6-8b46-79e9beb18bcc.png)
The guy who is on the wrong side wasn't in the game in the first round, but later he joined. This might cause the problem? This doesn't happen on other demos. The program crashes when I tried to see this player's details.

**Comment by Paager** [comment]
The program crashes when I tried to see this player's details.

**Comment by akiver** [comment]
Could you upload the demo please?

**Comment by Paager** [comment]
Here it is.
https://mega.nz/#!9p41CIxL!1Vdb1Bv8NPHe9MH7j2DOfvdPo0SZnuRiTabId9yJasI
