### ISSUE TITLE
Core.xlf has some errors

### ISSUE THREAD

**Issue by 872517414** [akiver/CSGO-Demos-Manager#128]
![1](https://cloud.githubusercontent.com/assets/9050713/18412299/75a7999a-77bd-11e6-8fa9-86a6b5bf4085.png)

These needs translation?

**Comment by 872517414** [comment]
Services and Manager also

**Comment by akiver** [comment]
These are not translatable strings.
You can hide it with the filter of the xlf editor.

**Comment by 872517414** [comment]
OK

**Comment by 872517414** [comment]
Manager.xlf line 96 :"Ignore ban occurred after demo date" non "Ignore ban occured after demo date"

**Comment by 872517414** [comment]
Manager.xlf line 231 :"TK" non "FF"

**Comment by akiver** [comment]
You can create a PR about the English errors or I will fix it, as you want.
If you are translating the app, please create an issue to inform that you are working on it.
It will help to know which languages need translations or not.
Thanks

**Comment by 872517414** [comment]
@Paager is translation,so I don't translation it. #131
