### ISSUE TITLE
Incorrect clutch result when died from bomb plant

### ISSUE THREAD

**Issue by Skysplit** [akiver/CSGO-Demos-Manager#130]
I noticed that when there is clutch situation, you kill every enemy (so you bascially won clutch) and after that die from the bomb plant (in my case it was last round of the map so I died after the round has ended), the clutch "Won" status is set to "No" where it should be "Yes"

**Comment by akiver** [comment]
Could you send me the demo please?
Thanks

**Comment by Skysplit** [comment]
Steam URL: steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-ofjn8-O46FP-2fbiS-77Lnt-8MEKO

If this won't work, could you tell me where to upload `.dem` file for you?

**Comment by akiver** [comment]
I got it thanks
