### ISSUE TITLE
Adding Chinese Translation File to "MultilingualResources"

### ISSUE THREAD

**Issue by ghost** [akiver/CSGO-Demos-Manager#131]
I am able to translate this to Chinese.

**Comment by akiver** [comment]
Which Chinese, traditional or simplified?
So I can add the required files.

**Comment by Paager** [comment]
Both pls.

**Comment by 872517414** [comment]
所以不需要我了XD，加油。

**Comment by 872517414** [comment]
这里有个参考翻译：https://share.weiyun.com/bb3c51d919e900370c94c261d87ef27c 贴吧@EvilEyecc 汉化版。

**Comment by Paager** [comment]
@872517414 谢谢啦~\(≧▽≦)/~

**Comment by akiver** [comment]
I added the Chinese files, I re-open the issue as translation isn't done.

**Comment by 872517414** [comment]
@akiver But why not zh-CN or zh-tw.English is en-US.

**Comment by akiver** [comment]
It will use zh-Hans or zh-Hant (depends on what language you selected) when your system language is zh-*.

**Comment by akiver** [comment]
Chinese (simplified) has been added, see #139 for translation status.
