### ISSUE TITLE
Add a new Demos Source

### ISSUE THREAD

**Issue by wordlesswind** [akiver/CSGO-Demos-Manager#132]
LOGO:
![5eplay](https://cloud.githubusercontent.com/assets/9050713/18507322/788fa840-7aa2-11e6-86ac-cac4534f0e7f.png)
5eplay is a Chinese CSGO news website.
Official website: https://www.5eplay.com
And they set up csgo matchmaking servers on Jan 2016.
They developed anti-cheating system by themselves.
Official website: https://www.5ewin.com/?lang=english
They made Event Solutions for Asia Event.more chinese  event and asia event used it now.
Sl-i League S2 with Nanjing use 5eplay‘s ’Event Solutions.But G20,they cancel it,and go to Ukraine.
Chinese team play csgo on there,such as tyloo.
And Republic of Korea MVP.Project also.

**Comment by akiver** [comment]
Do they use ebot?
Do you have some demos?

**Comment by 872517414** [comment]
Not ebot I think.They create it with the Warmod plugin.

https://drive.google.com/drive/folders/0BxPqOXQUjZuvYWlraXJIU2x1YU0?usp=sharing

https://www.5ewin.com/data/match/20160915183705d75930?lang=english
https://www.5ewin.com/data/match/20160915192920d07192?lang=english
https://www.5ewin.com/data/match/20160915210642d78034?lang=english

MVP.Project vs EDG

**Comment by 872517414** [comment]
![1](https://cloud.githubusercontent.com/assets/9050713/18574810/2b0629fc-7c03-11e6-9a76-513f4ea1735f.png)
interface
![2](https://cloud.githubusercontent.com/assets/9050713/18574811/2b31be96-7c03-11e6-8be3-534bed3485b5.png)
Vote to Friendlyfire
![3](https://cloud.githubusercontent.com/assets/9050713/18574812/2b5d5b96-7c03-11e6-88c2-64b0572672aa.png)
Knife round
![4](https://cloud.githubusercontent.com/assets/9050713/18574813/2b89046c-7c03-11e6-9d79-fa2ee75fb52d.png)
start as team
![5](https://cloud.githubusercontent.com/assets/9050713/18574814/2bb6d766-7c03-11e6-925e-7c44abee34cd.png)
Round Scoreboard
![6](https://cloud.githubusercontent.com/assets/9050713/18574815/2be4ecfa-7c03-11e6-9980-7c903611f6b5.png)
END Scoreboard (Have English,but I set preferences to Chinese.)

**Comment by wertercatt** [comment]
Hey, I'm using the English setting, but where on the site do I go to view the directory of matches? Do I have to browse matches by player? I hope not, because that seems really inconvenient.
