### ISSUE TITLE
Average Damage per Round incorrect if last round a player did damage in wasn't the last round

### ISSUE THREAD

**Issue by adfinlay** [akiver/CSGO-Demos-Manager#133]
Because https://github.com/akiver/CSGO-Demos-Manager/blob/master/Core/Models/Player.cs#L814-L821 uses the last iteration of the foreach loop to set the round number, if the last round in which a player does damage is not the final round, the round number won't accurately represent the total number of rounds they played, therefore giving an incorrect value.

```
int roundNumber = 1;
foreach (PlayerHurtedEvent playerHurtedEvent in PlayersHurted.ToList().Where(
    playerHurtedEvent => playerHurtedEvent != null && playerHurtedEvent.AttackerSteamId == SteamId))
{
    total += playerHurtedEvent.HealthDamage;
    roundNumber = playerHurtedEvent.RoundNumber;
}
if (Math.Abs(total) < 0.1) return total;
total = Math.Round(total / roundNumber, 1);
```

By way of example, if a player plays 10 rounds, and does 90 damage across the first 9 rounds and none in the 10th, the code above would give their ADR as `90 / 9 = 10`, whereas it should be `90 / 10 = 9`.

**Comment by Skaronator** [comment]
nice catch
