### ISSUE TITLE
Demo shows 6 players on one side, 4 on the other

### ISSUE THREAD

**Issue by sonOfRa** [akiver/CSGO-Demos-Manager#134]
![Weird demo](https://cloud.githubusercontent.com/assets/1269520/18790455/1866b92c-81af-11e6-80f5-bf2e1bae6dae.png)

The player Marshall dojki.com was actually on the other team.

Possible cause: One player (maybe this one?) had disconnected during warmup (but while the 60s countdown was already started, they had already connected). They reconnected in the first or second round of the game.

Here's the demo share link if that helps: steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-sDvpw-VJiNj-OPbNo-2GBwc-YE4BO

**Comment by akiver** [comment]
fixed with 497877a9da833d12431fa5ae0cb24323ad6c9836
It will be in the next release.
