### ISSUE TITLE
Incomplete Rank history

### ISSUE THREAD

**Issue by skyborgff** [akiver/CSGO-Demos-Manager#136]
This is my rank history.
https://gyazo.com/7a1216c2f6e1f211111e5382975ef852

I have more than one game were my rank is below SE , but they don't show in the graph.
https://gyazo.com/06ec94d57b57ce5f2d835bc0e9084678 (one for example)
https://gyazo.com/7aff730e8051e2e310a6a121bc7d6ecb (the dates are correct)

Is there a fix for this?

**Comment by akiver** [comment]
Are you sure your missing demos are in the same folder than the others and the option "Limit stats to selected folder" is unchecked in settings?
If it's checked, demos have to be in the same folder.

**Comment by skyborgff** [comment]
yes, they are in the same folder, and the setting is unchecked

**Comment by akiver** [comment]
Could you send the demo from your screenshot please? (https://gyazo.com/06ec94d57b57ce5f2d835bc0e9084678)

**Comment by skyborgff** [comment]
Sure, I reinstalled windows yesterday and still haven't had the chance to analyze all the games i had saved. ill send it as soon as i have it analyzed .( so i can find the correct one )

**Comment by skyborgff** [comment]
https://drive.google.com/open?id=0B4xgn5X2nQxoV0oyaHd1WDFLN2M

https://gyazo.com/08ab86b2fdce7dedd677277dcbb719b5
https://gyazo.com/482806844b55fa8000550ca90170c767
https://gyazo.com/840addaf9eb8ec19731e37399ed7f093

another problem. THe first game has the wrong date, and therefor it fools the rank. im still gold nova 2.
