### ISSUE TITLE
Having trouble in building the manager

### ISSUE THREAD

**Issue by maxinimize** [akiver/CSGO-Demos-Manager#137]
Dear developer,

Hi, I want to test my translation, But I have some problems in building. 

Specifically, I didn't get what is Telerik binaries, and where can I get it. Could you please add the downloading link to the building instruction? I mean I know u had given us Telerik's website but I have no idea which one I should download.

Also, if you could give more details about "setting the correct path for Telerik references if needed", I would be very appreciated.

Thanks

Ch40

**Comment by akiver** [comment]
This one http://www.telerik.com/products/wpf/overview.aspx.
If you don't have a license, just reference dlls from the CSGO Demos Manager installation folder.
By references I mean specify where telerik dll are located from the visual studio "References" menu.
You should have warnings for this dlls and you have to specify where they are located to fix it.

**Comment by maxinimize** [comment]
Thx man it is solved now.
