### ISSUE TITLE
[TRANSLATION] Chinese simplified status

### ISSUE THREAD

**Issue by akiver** [akiver/CSGO-Demos-Manager#139]
This issue is to keep track of the Chinese (simplified) translation.

@maxinimize translated the whole app with 4685ac7ab5f4dbdb2c44689804898cbd5e51fd07.
### Not translated strings:
- BOT: **2**
- Core: **0**
- Manager: **0**
- Services: **0**
### Needs review strings:
- BOT: **0**
- Core: **0**
- Manager: **0**
- Services: **0**

All others strings state are set to "final" (translation done) but you are free to check for typos...

**Comment by 872517414** [comment]
Nice.I will check it on Saturday.
