### ISSUE TITLE
Sides on Eco / Force-buy are based on wrong team's equipment value from 16th round onwards.

### ISSUE THREAD

**Issue by givhug** [akiver/CSGO-Demos-Manager#143]
It seems the demo analysis/presentation fails at swapping the teams at half-time. In the screenshot I uploaded, you can see on the 2nd round the T side is on an eco. Team 2 equipment value shows that team 2 is the T side. We should expect team 2 to be the CT side beginning with the 16th round after the teams have swapped sides, but as you can see on round 18 team 1 is on an eco and the eco is wrongly labelled a CT eco.

If people were wondering why eco rounds in the second half seemed to almost always result in a win for the ecoing team but not in the first half, this is because CSDM correctly gave the winning team in the "winner" column but failed to do so in the "side on eco" column.

![economywrongteamafterhalf](https://cloud.githubusercontent.com/assets/10101337/19207637/e006bfe2-8cf2-11e6-9e55-a9baa24492eb.png)

**Comment by akiver** [comment]
Could you send me the demo please?

**Comment by givhug** [comment]
Here you go:
[https://drive.google.com/open?id=0B6dGqYbxbz8HR3JzakkzdHYwZUE](https://drive.google.com/open?id=0B6dGqYbxbz8HR3JzakkzdHYwZUE)

I also checked a few matches and they all had that issue. Good luck!
