### ISSUE TITLE
Can't get the HLTV options to show up in the overall view.

### ISSUE THREAD

**Issue by whatanoob** [akiver/CSGO-Demos-Manager#147]
I remember I used to be able to it, but now I can't for some reason. Enabling or disabling it in the columns tab only affects the scoreboard in the detailed demo view. Is this intended?

**Comment by akiver** [comment]
HLTV rating column is available only when an account is selected (there is a combox on the demo list view).
You have to uncheck the checkbox "Show all" to be able to select an account.

**Comment by whatanoob** [comment]
Oh cheers!
