### ISSUE TITLE
Add sostronk rating system

### ISSUE THREAD

**Issue by Skaronator** [akiver/CSGO-Demos-Manager#149]
This rating system is still WIP so I'd wait a bit before you adding it, if you even want to do that.

Last blog post update of the system (today): https://www.sostronk.com/blog/updated-impact-rating
Reddit thread: https://www.reddit.com/r/GlobalOffensive/comments/5a5rdi/sostronkthe_asian_minor_use_an_impact_rating_type/

This system seems to be a bit more fair than the HLTV rating since it only count kill/death and also better than RWS since it not only count ADR.

**Comment by 0BuRner** [comment]
duplicate #60

**Comment by Skaronator** [comment]
Woops didn't saw this issue - closing this one.
