### ISSUE TITLE
Show if the match was a win or a loss

### ISSUE THREAD

**Issue by nvlbg** [akiver/CSGO-Demos-Manager#15]
Let's say I want to see how many wins/losses i have since I am an eagle. I should go to details to each demo, because I don't know if I'm on team 1 or team 2. Then I need to see which team is the winner just to determine if I won the match. And I have to do this for 30 demos for example. It's a simple but very useful feature in my opinion.

**Comment by 0BuRner** [comment]
It's already implemented. (see #9)
Would be available in the next release ;)

**Comment by nvlbg** [comment]
Awesome then :)
