### ISSUE TITLE
how to build on linux

### ISSUE THREAD

**Issue by hasufell** [akiver/CSGO-Demos-Manager#150]
How do you build this on linux? Is it even linux compatible?

**Comment by 0BuRner** [comment]
I may be wrong but I don't this it's compatible with Linux since CSGODM is using WPF for the UI and WPF isn't available with Mono.

**Comment by akiver** [comment]
Not possible, there are strong dependencies with Windows.

**Comment by hasufell** [comment]
windows sucks! :feelsgood:

**Comment by fopor** [comment]
Any alternatives that work on linux? :C

**Comment by JoshuaBehrens** [comment]
We could extract logic into dotnet core

**Comment by 0BuRner** [comment]
- https://github.com/markus-wa/demoinfocs-golang
- https://github.com/saul/demofile

**Comment by fopor** [comment]
Thank you!
I will try to use one of the alternatives for now
