### ISSUE TITLE
Add ability to change demos source from demos details view

### ISSUE THREAD

**Issue by b10011** [akiver/CSGO-Demos-Manager#158]
> An error occured while analyzing the demo _demoname_.dem.The demo may be too, if not please send an email with the attached demo.You can find more information on http://csgo-demos-manager.com.

Using ESEA demo from yesterday, tested with multiple demos.

While writing this, noticed that demos which used to work, won't work anymore.

**Comment by akiver** [comment]
Demo link please?

**Comment by b10011** [comment]
https://play.esea.net/index.php?s=servers&d=download_replay&id=6540799

For example this. I tried to reinstall csgo demos manager but it didn't help.

**Comment by akiver** [comment]
I tested your demo, it works for me.
Are you sure the demo's source is set to "ESEA"?

**Comment by b10011** [comment]
https://youtu.be/G5K8KSSeA0E

Updated to newest version and now it works... at the beginning. And yes, it knows the demo is ESEA demo.

**Comment by akiver** [comment]
It's because you renamed your demo.
Demos source are mainly detected from filename.
Change the source to ESEA it will work.

**Comment by b10011** [comment]
Oh! My bad, didn't know that.

I didn't open the demo from csgo demos manager, I opened it from file explorer. Could you add a feature that I can switch the source type when I open the demo from file explorer? Now I needed to add the folder to the paths and then change the source type. I understand this isn't priority-1, but it would be really useful!
