### ISSUE TITLE
Grab additional data 

### ISSUE THREAD

**Issue by Vipitis** [akiver/CSGO-Demos-Manager#159]
some people use web based services to analyse their demos and stats: csgosquad.com, csgostats.gg, csgo-stats.net

some of these websites save progression over time and it would be awesome if the Stats page can lookup any additional data of a steam account from different websites, just so you get more data to look at.

**Comment by akiver** [comment]
Do you mean fetch data from this websites and display it in the application?

**Comment by Vipitis** [comment]
yeah, fetch data or whole demos from those websites if the allow it and display in the stats>progression display.

**Comment by akiver** [comment]
Third application should have a public api which is not the case.
