### ISSUE TITLE
Next release (Not issue) ( Question / Help wanted?)

### ISSUE THREAD

**Issue by skyborgff** [akiver/CSGO-Demos-Manager#160]
I know this shouldn't be posted here, but i didn't knew where should i post this. Sorry in advance.
It has been 3 months since 2.9.0. and a lot of bugs have been fixed since then. When are you thinking in releasing a new installer?
I'd be thankful if anyone could provide one, because i'm not into compiling.
Thank you all who contributed for this awesome program

**Comment by akiver** [comment]
New release is available :)

**Comment by skyborgff** [comment]
Man, i have such a timing hahahah. Thank you veryvery much .
