### ISSUE TITLE
Option to ignore ban before/after demo date

### ISSUE THREAD

**Issue by TheWhiteRussian** [akiver/CSGO-Demos-Manager#161]
In Version 2.7.0 (09/07/2016) patch notes it says "Added option to ignore bans occurred **_before_** the demo's date.". But in the program the setting says "Ignore bans occurred **_after_** the demo's date." Which one is it?

**Comment by akiver** [comment]
It ignore last VAC ban occured before demos date, the label option is incorrect.
https://github.com/akiver/CSGO-Demos-Manager/blob/master/Services/Concrete/DemosService.cs#L62
