### ISSUE TITLE
JSON: sum of deaths in "kills" array different than "team_t"->..->"death_count"

### ISSUE THREAD

**Issue by Skaronator** [akiver/CSGO-Demos-Manager#164]
Hey,

I'm facing a issue of inconsistent data from the json export. The last player in the scoreboard has 1 death more. I'm not 100% sure if its a json error or a mysql error by my side -- gonna analyse the json directly now.

## Using  "team_t"->..->"kill_count", "assist_count", "death_count"
Player | K (HS) | A | D
------- | ------ | --- | ---- 
qWaN | 12 (2) | 1 | 20 
berniRAMBO❤P.		| 13 (7)	| 5	| 19
Metrok ze Wsii		| 12 (3)	| 3	| 20
Nirfer (◣◢)┌∩┐		| 8 (1)		| 2	| 17
MissY	| 6 (1)		| 2	| **20**

## Using "kills" array

Player | K (HS) | A | D
------- | ------ | --- | ---- 
qWaN | 12 (2) | 1 | 20 
berniRAMBO❤P.		| 13 (7)	| 5	| 19
Metrok ze Wsii		| 12 (3)	| 3	| 20
Nirfer (◣◢)┌∩┐		| 8 (1)		| 2	| 17
MissY	| 6 (1)		| 2	| **21**

Demo + json: https://skaronator.com/files/Skaronator-issue-164.rar

**Comment by Skaronator** [comment]
Okay I've retested it without my whole MySQL backend and can confirm this bug.

#### Source Code
```
	$content = file_get_contents(__DIR__."/match730_003148639727981166880_0116858774_133.dem.json");
	$json = json_decode($content, true);

	$death = array();

	foreach ($json["kills"] as $key => $value) {
		$death[$value["killed_name"]] += 1;
	}

<pre><?php  print_r($death); ?></pre>

```

#### Output
```
Array
(
    [Skaro \_] => 10
    [Metrok ze Wsii] => 20
    [MissY] => 21
    [Nirfer (◣◢)┌∩┐] => 17
    [qWaN] => 20
    [berniRAMBO❤P.] => 19
    [Gr33n] => 9
    [Husky™] => 12
    [WidDoW|┣▇▇▇═─] => 10
    [Shepl] => 10
)
```

As you can see **MissY** has **21 death** and if you go to *team_t* -> *team_players* -> *death_count* has **20 death**

**Comment by akiver** [comment]
It's because MissY was controlling a bot at the last kill.
**Demo->Kills** contains all kills (no filter) and **Player->deaths** only deaths when the player wasn't controlling a bot (same as the scoreboard ingame).

I added 3 variables to know if killer / victim and assister was controlling a bot at the kill event.
