### ISSUE TITLE
JSON: killed_steamid empty but killed_name not

### ISSUE THREAD

**Issue by Skaronator** [akiver/CSGO-Demos-Manager#165]
Alright found a 2nd issue with the `kills` array but this one should be easy fixed.

The SteamID is empty but it actually found the correct name. Dunno why, but now does it looks like Steam ID `76561198020411566` killed **nobody** with a MAC-10.

![image](https://cloud.githubusercontent.com/assets/2886913/20463481/586e1cba-af34-11e6-9518-7ec3ececbad7.png)

Demo + Json: https://skaronator.com/files/Skaronator-issue-165.rar

**Comment by Calak** [comment]
I don't looked at the demo, but Ulysses isnt a bot?

**Comment by Skaronator** [comment]
Uhh feeling stupid now but you may be right. I'm not at home but it's very probably a bot.

Thanks @Calak
