### ISSUE TITLE
"Error - AfxHookSource" when watching highlights

### ISSUE THREAD

**Issue by thedudeguy1** [akiver/CSGO-Demos-Manager#169]
Upon trying to watch player highlights from player POV, a dialogue box is opened that says "Problem in addresses.cpp:1528". This error has already been resolved in [HLAE 2.19.1](https://github.com/ripieces/advancedfx/releases/tag/v2.19.1). After clicking OK, another window with the same title says "Problem in addresses.cpp:402". This error has been resolved in [HLAE 2.20.1](https://github.com/ripieces/advancedfx/releases/tag/v2.20.1). When I click OK after that, the highlights play as usual except my name is not highlighted in the kill feed.

**Comment by akiver** [comment]
You have to manually update HLAE.
I hope to make HLAE update easier to do soon.

**Comment by thedudeguy1** [comment]
This may seem like an obvious question but is CSGO Demos Manager already bundled with its own copy of HLAE or does it run the installed version if that is present? I don't remember if I installed HLAE or if it is standalone.

**Comment by akiver** [comment]
ATM it's bundled, I hope to change the way HLAE is integrated soon.

**Comment by akiver** [comment]
HLAE must now be installed / updated from the app 9712a0aafd28552982b40133073b839762d1a020
It will reduce this kind of errors.
