### ISSUE TITLE
Add new language [TR]

### ISSUE THREAD

**Issue by eyupbaytur** [akiver/CSGO-Demos-Manager#173]
I wanted to use the program then i noticed translation section. I wanna help to translate the app but i don't know so much thing about github. If you add turkish .xlf file, i really like to help.

**Comment by akiver** [comment]
You can find all information here https://github.com/akiver/CSGO-Demos-Manager#translations

**Comment by akiver** [comment]
I added the Turkish files if you want to translate it. Thanks.
