### ISSUE TITLE
No Stats

### ISSUE THREAD

**Issue by Aphrox** [akiver/CSGO-Demos-Manager#175]
Hey,
I just started using CSGO Demos Manager and it seems like it can't get any data of my recent matches. I have some older demos (5+ months) which are working fine.

If you need more informations let me know.

Thank you and have a nice day.
![bug](https://cloud.githubusercontent.com/assets/24849317/21575368/4b9e96a4-cf0a-11e6-93c1-bcdbd27b7032.jpg)

**Comment by akiver** [comment]
What's happens when you analyze one of this demos?

**Comment by Aphrox** [comment]
Hey, thanks for your answer!

I tried it again yesterday and now it works perfectly. CSGO DEMOS MANAGER is showing everything now.
Thanks again and have a nice weekend. :)
