### ISSUE TITLE
Added accounts don't act like they used to

### ISSUE THREAD

**Issue by hobbangr** [akiver/CSGO-Demos-Manager#176]
I saw the changelog say the STATUS column is hidden unless an account is selected but I added my two accounts and still do not see my latest rank / status (win/loss/tie) of each match. I've tried adding my accounts using steam 64 ID and steamcommunity URL. Am I missing something?

**Comment by akiver** [comment]
Uncheck "Show all" checkbox, there is a bug that doesn't uncheck it when you select an account.

**Comment by hobbangr** [comment]
... So simple! Thank you, @akiver!
