### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by greznica** [akiver/CSGO-Demos-Manager#181]
I just installed app, and it crashed straight away, when I tried to start it. I do have .net 4.5 installed. I get this error:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	CSGODemosManager.exe
  Problem Signature 02:	2.9.0.0
  Problem Signature 03:	58289cfb
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.6.1087.0
  Problem Signature 06:	583e5abb
  Problem Signature 07:	157f
  Problem Signature 08:	1d7
  Problem Signature 09:	System.IO.IOException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1060
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by akiver** [comment]
Try with the last version, it looks like you are using the 2.9.0.

**Comment by 2called-chaos** [comment]
I have the same issue with 2.11.1 but as I tried to start the app a 5th time to copy the details it suddenly works  ô.O But it definetely contained "System.IO.IOException" as well.

**Comment by akiver** [comment]
Please re-open if you still have the issue.
