### ISSUE TITLE
Error at the start.

### ISSUE THREAD

**Issue by ShinobuDonut** [akiver/CSGO-Demos-Manager#183]
So, one week ago, CSGO-Demos-Manager stopped working and showing me errors "Configuration system failed to initialize". I checked my .Net version and Visual Studio, everything was okay. So I uninstalled CSGO-Demos-Manager and removed the files in Appdata/local and Appdata/Roaming.

Right now I have this BoxError popping at the start : 
http://imgur.com/a/xSgGy
 Can you help me ? 

This is the error.log : 
[errors.log.txt](https://github.com/akiver/CSGO-Demos-Manager/files/730843/errors.log.txt)

**Comment by 0BuRner** [comment]
Delete C:\Program Files (x86)\CSGO Demos Manager\CSGODemosManager.exe.config and try again

**Comment by ShinobuDonut** [comment]
Thx for your help but it seems that there's no .config in the folder for CSGODemosManager.exe but only for CSGOSuspectsBot.exe

**Comment by ShinobuDonut** [comment]
Ok so I did a new installation, when I launch CSGODemosManager.exe, the error http://imgur.com/a/xSgGy appear then it remove the file CSGODemosManager.exe.config 

[http://imgur.com/KVjIf8F](url)

This is damn weird I don't know what to do ...

**Comment by ShinobuDonut** [comment]
I did a clean install of W10 and it's fine. I think that one of my .NET package was fucked up x)

**Comment by ShinobuDonut** [comment]
I did a clean install of W10 and it's fine. I think that one of my .NET package was fucked up x)

Issue closed.
