### ISSUE TITLE
Unable to fully analyze certain demos

### ISSUE THREAD

**Issue by pokemon99990** [akiver/CSGO-Demos-Manager#186]
I have three demos that will not analyze correctly and i cannot figure out why.
Demos:
CSGO-HtEhM-NZdeN-3K2Lp-aeL56-KzBND
CSGO-mjbMZ-Sxojn-NMww9-vZhuX-EQM6H
CSGO-uc8mh-SKPOD-j88zR-weqkZ-Ua7WB

**Comment by akiver** [comment]
I tested with the first 2 demos without error, the last one has expired.

**Comment by zp** [comment]
One of my recent demos gave me the same error about not being able to analyze (using csgo demo manager version 2.10.0)

demo link: https://mega.nz/#!gooHnbAB!En2zbbiaXr965X9f1LPHZEcyhwXSmBIoo6_zMwIqSnQ

**Comment by akiver** [comment]
@zp 2f66122d8cecdf39b051ab75550ce0d7bc58058f fix the error

**Comment by pokemon99990** [comment]
So in the first demo, I went to the point where it stopped analyzing and it stopped at the round when a teammate rejoined after leaving, could this have something to do with it?

**Comment by akiver** [comment]
Could you try with the 2.11.0?

**Comment by pokemon99990** [comment]
Tried analyzing them again, the first one still doesn't, but i have a bigger list now 

CSGO-75A5C-6RNBt-KLByP-YYaWc-BusnC
CSGO-pFLjk-ps5pV-VujPG-UO2cC-7JxbE
CSGO-MFz39-SAiwz-Vk6sF-bbUy9-Hq5uC
CSGO-mohzx-Qa8Gs-OGbrq-8Euie-K564E
CSGO-HtEhM-NZdeN-3K2Lp-aeL56-KzBND
CSGO-mjbMZ-Sxojn-NMww9-vZhuX-EQM6H
CSGO-uc8mh-SKPOD-j88zR-weqkZ-Ua7WB

**Comment by akiver** [comment]
Tested will all without errors.
The first one too, the score is 15-15.
Did you change demos name?

**Comment by pokemon99990** [comment]
I do not believe so, I just downloaded them from the program.

**Comment by akiver** [comment]
I re-tested to be sure and I don't have any errors.
