### ISSUE TITLE
Share code bug / crash.

### ISSUE THREAD

**Issue by zp** [akiver/CSGO-Demos-Manager#188]
I've noticed on 2 demos of mine that the share code is missing the last character (even though copying the share code from inside csgo copies the full string)

If you try to send these share codes to a 3rd party application (csgostats.gg in this case), CSGO demos manager will crash.

I think a potential fix is to check the length of the share code and assume any that aren't 34 chars are invalid and not try to parse/send to 3rd party apps.

I'm in the process of uploading one of the affected demos, I'll reply whenever it's finished.

**Comment by zp** [comment]
Demo link: https://mega.nz/#!Mpp3hawa!MCbt3h8NQB3G6auzr1Voy2vq47ek4yKzaTaYDEeXz84

**Comment by akiver** [comment]
fixed with 55eb6318556ccda1df42afc3d15ea7d357b4f123 thanks
