### ISSUE TITLE
Analyze of FaceIt overtime bug

### ISSUE THREAD

**Issue by NogradThGin** [akiver/CSGO-Demos-Manager#192]
Hello, I got a problem on analyze overtime game.

My team won 19-17 on Train on FaceIt but the Demo Viewer show me 19-17 for the ennemy team ^^
Here is screens

FaceIt Screen : http://img11.hostingpics.net/pics/233758lolnvikjfldgkjl.png
Demo Viewer : http://img11.hostingpics.net/pics/265681fdg.png

**Comment by akiver** [comment]
Could you send the match link please? Thanks

**Comment by akiver** [comment]
Please try with the new version 2.11.0.
