### ISSUE TITLE
[Translation] ES-Spanish

### ISSUE THREAD

**Issue by FGonzalezLopez** [akiver/CSGO-Demos-Manager#194]
Just wanted to let you know that I'm currently working on a Spanish translation. 

I'm trying to be as true to the game's official terminology as I can where applicable, while trying to make everything understandable for the average player (ie using the in game Spanish argot). I know so may people that are deterred by the language barrier in programs...

I am about 75% done (the manager xlf is endless D:) in a couple hours, I need maybe an hour or so more. I'd estimate I will do the pull request by tomorrow afternoon.

Seeing the latest changes to the UI (thanksthanksthanks they were great) inspired me to contribute to the application, and luckily @akiver has setup this super easy way to translate (otherwise it would have probably stopped me since I don't do much programming on Windows). Thanks for your work!

**Comment by FGonzalezLopez** [comment]
It's done! A pull request has been sent to @akiver . I hope everything is alright!

**Comment by akiver** [comment]
Spanish added, thanks :)
