### ISSUE TITLE
Will Mac OSX ever be supported?

### ISSUE THREAD

**Issue by TheWebfrog** [akiver/CSGO-Demos-Manager#203]
Title, I've tried using it with wineskin but sadly that doesn't work.
It would be nice if a milestone for OSX could be added :)

**Comment by ReagentX** [comment]
Parallels or Boot Camp

**Comment by thedudeguy1** [comment]
There's a chance you can get it working with Wine utilities. HLAE, however, is windows only as can be seen on [this forum post](http://advancedfx.style-productions.net/forum/viewtopic.php?t=1737).

**Comment by andreas-marschke** [comment]
Since to tool itself is written in C# and is based on WPT(?) I wonder if it wouldn't be easier to straight port it using Mono/Xamarin. CS:GO itself will likely run poorly but you could still review demo stats from your mac.

**Comment by 0BuRner** [comment]
Since this tool uses WPF and knowing that Mono doesnt support WPF, I dont think it will be possible right now. Maybe it does exist but I'm not aware of a tool supporting WPF on Linux/OSX platform....

**Comment by akiver** [comment]
Sorry but there are too much strong Windows dependencies in the app itself and libs used by the app.
I would like to release a whole new version compatible on mac, linux and windows but I don't have an ETA, the problem is time.
