### ISSUE TITLE
Website: SEC_ERROR_EXPIRED_CERTIFICATE / SSL_ERROR_BAD_CERT_DOMAIN

### ISSUE THREAD

**Issue by ripieces** [akiver/CSGO-Demos-Manager#206]
https://csgo-demos-manager.com/ gives SEC_ERROR_EXPIRED_CERTIFICATE in FireFox. Due to HSTS FireFox won't allow HTTP.

https://www.csgo-demos-manager.com/ gives SSL_ERROR_BAD_CERT_DOMAIN

**Comment by akiver** [comment]
Thanks it's fixed :)

**Comment by ripieces** [comment]
Thanks, but www. subdomain still uses wrong CER (for akiver.com / www.akiver.com)

**Comment by akiver** [comment]
oops I forget it, it's fixed, thanks
