### ISSUE TITLE
HandleSayText inconsistent with HandleSayText2

### ISSUE THREAD

**Issue by n1c** [akiver/CSGO-Demos-Manager#207]
Shouldn't `HandleSayText` also prepend the `e.Sender.Name` to the message as with `HandleSayText2`?

https://github.com/akiver/CSGO-Demos-Manager/blob/master/Services/Concrete/Analyzer/DemoAnalyzer.cs#L1275

**Comment by akiver** [comment]
It's a message from the server, there is no name in this kind of event :)
