### ISSUE TITLE
Fix app crash

### ISSUE THREAD

**Issue by 0BuRner** [akiver/CSGO-Demos-Manager#21]
Someone on reddit reported this error causing the app crash : 

13/06/2015 23:01: Object reference not set to an instance of an object. StackTrace: at CSGODemos_Manager.Services.Analyzer.DemoAnalyzer.<>cDisplayClass92_0.<HandleBombExploded>b0(PlayerExtended p) at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable1 source, Func2 predicate) at CSGO_Demos_Manager.Services.Analyzer.DemoAnalyzer.HandleBombExploded(Object sender, BombEventArgs e) at DemoInfo.DP.Handler.GameEventHandler.Apply(GameEvent rawEvent, DemoParser parser) at DemoInfo.GameEvent.Parse(IBitStream bitstream, DemoParser parser) at DemoInfo.DP.DemoPacketParser.ParsePacket(IBitStream bitstream, DemoParser demo) at DemoInfo.DemoParser.ParseTick() at DemoInfo.DemoParser.ParseNextTick() at DemoInfo.DemoParser.ParseToEnd() at System.Threading.Tasks.Task.Execute() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at CSGO_Demos_Manager.Services.Analyzer.ValveAnalyzer.<AnalyzeDemoAsync>d2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at CSGO_Demos_Manager.Services.DemosService.<AnalyzeDemo>d_3.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at CSGODemos_Manager.ViewModel.HomeViewModel.<RefreshSelectedDemos>d_159.MoveNext()

**Comment by akiver** [comment]
fixed with 097799e8cb0668001c90e3cf44e00a14c980c6ef
