### ISSUE TITLE
Player Info is Incorrect When in Multiple Demos

### ISSUE THREAD

**Issue by Tygon** [akiver/CSGO-Demos-Manager#212]
When analyzing a demo, you can select individual players and see their stats, clutches, duels etc. This is great and it works perfectly, except now if you go to a second demo with the same player and check their stats, it does not update and still shows the player's stats from the first demo. The only way to fix it right now is to close the application and reopen it after every demo.

**Comment by akiver** [comment]
Hi, I didn't find the way to reproduce it.
Could you send me details please?

Are you navigating through demos with previous / next demos buttons from demo's details view?
Do you focus on a player from the demo's details?

Thanks

**Comment by Tygon** [comment]
Follow these steps:

I select a demo from the main list.
Double click on a player to see their performance details.
Then press back twice to get back to the main list.
Select another demo with the same player, double click on them again to see their performance details, the stats shown are from the previous demo.
Relaunch the program and go to the second demo, double click the player and it now shows the correct performance details.

**Comment by akiver** [comment]
Thanks!
