### ISSUE TITLE
ESL Season 5 demos do not work

### ISSUE THREAD

**Issue by ReagentX** [akiver/CSGO-Demos-Manager#216]
CSGO-Demos-Manager fails to analyze these demo files:

http://www.hltv.org/?pageid=216&eventid=2639

http://www.hltv.org/?pageid=216&eventid=2638

No matter what they are classified as (ESL, Valve, etc.) they always error out.

**Comment by akiver** [comment]
I don't know how they recorded this demos but they are all corrupted (end data exactly).
You can still analyze them but you may have missing data.
