### ISSUE TITLE
Add Rating 2.0

### ISSUE THREAD

**Issue by Skaronator** [akiver/CSGO-Demos-Manager#225]
https://www.hltv.org/news/20695/introducing-rating-20

Maybe add a new string for the exported json `"rating2"`?

**Comment by 0BuRner** [comment]
Hi,
I also was enthousiastic when I saw this article on htlv.org. But when reading it to the end we can see "**The exact formula won't be public this time**".
So this is not possible to implement rating 2 in CSGODM as it.

Based on the infos displayed on this picture https://static.hltv.org/images/news/custom/20695/rating2.png and with some brute-force it _might_ be possible to guess the invariants factors used in their formula...

**Comment by Skaronator** [comment]
Hi,
didn't read the whole articel as of opening this issue. Pretty disappointing this move from HLTV. 

You might be right to guess the rest of their formula with some brute-force or maybe they will publish it in the future.

I'll backup this img on github server:
![image](https://user-images.githubusercontent.com/2886913/27206921-f39149a2-523a-11e7-87ee-ffb25c5cd504.png)

**Comment by 0BuRner** [comment]
Rating 1

> KillRating = Kills/Rounds/AverageKPR
> SurvivalRating = (Rounds-Deaths)/Rounds/AverageSPR
> RoundsWithMultipleKillsRating = (1K + 4*2K + 9*3K + 16*4K + 25*5K)/Rounds/AverageRMK

Rating 2

> KillRating = Kills/Rounds/AverageKPR
> SurvivalRating = (Rounds-Deaths)/Rounds/AverageSPR
> ImpactRating = updated formula based on multi-kills, opening kills, 1-v-X duels (and more)
> KASTRating = percentage of rounds with a kill, assist, survival or traded death
> DamageRating = (incorprating) Average Damage Dealt per Round

It will be a lot of work to be able to find exact values...

If someone can extract each of these knowns values needed for all players of a single game and put them in an Excel sheet, I can try to guess the formula and compute the correct factors.

**Comment by ReagentX** [comment]
@0BuRner, see the playerStats.csv file in the csv folder of my HLTV-Scraper repo for the information you want:
https://github.com/ReagentX/HLTV-Scraper

**Comment by akiver** [comment]
I'm not going to do some reverse engineering to find the formula.
