### ISSUE TITLE
[Demo Source]A new CS:GO platform from Perfect World(CN)

### ISSUE THREAD

**Issue by 872517414** [akiver/CSGO-Demos-Manager#226]
Do you know CS:GO in China have a agency?
That is Perfect World.China CS:GO Official Website:http://www.csgo.com.cn
And now,they set up a platform for CS:GO and DOTA 2.Website:http://pvp.wanmei.com
the platform's name is BATTLE PLATFORM.
LOGO:

![logo](https://user-images.githubusercontent.com/9050713/27226978-08d8bc16-52d4-11e7-8567-d6e29b401b14.png)

But it only allows players with a Perfect World CS:GO Pass to play.

**Comment by 0BuRner** [comment]
Can you upload or link a demo recorded from this platform ?

**Comment by 872517414** [comment]
@0BuRner uploaded
https://drive.google.com/drive/folders/0BxPqOXQUjZuvbVVFd1hqMlZHdXc?usp=sharing

**Comment by akiver** [comment]
I added the source but there is no way (based on your demo) to detect it like other sources, you have to do it manually.
If you can contact an admin from the platform and ask to add their platform's name in the server's name for example I could detect it.
