### ISSUE TITLE
Files from Replay Server replay190.valve.net can not be downloaded!

### ISSUE THREAD

**Issue by Floraly** [akiver/CSGO-Demos-Manager#227]
But Demo info Files are still exists. Can CSGO Demo Manager parse the Demo.info Files too?

Something like _190.dem.info it include all Stats of the Match

**Comment by ReagentX** [comment]
The info file contains only a summary of the match: players, kills, map, etc. It doesn't have any of the stats that this software analyses.

**Comment by akiver** [comment]
You can't retrieve all data from .info, you need the demo.
If the download link has expired, it's too late.
