### ISSUE TITLE
[Suggestion]: Add Time of death of every player in a round (+average time of death)

### ISSUE THREAD

**Issue by Viigoo** [akiver/CSGO-Demos-Manager#230]
Could help analyze if a player was more passive or aggressive

**Comment by ReagentX** [comment]
The tick of a death/kill is already in the Kills sheet in the Excel export.

**Comment by Viigoo** [comment]
I can only find that data through round details (if that's what you meant?). But it's still pretty hard to analyze every single round and finding each player in it.

**Comment by ReagentX** [comment]
No. Every kill in a match is reported on the `kills` sheet. You can use this sheet to determine the average time of death using the `=AVERAGEIFS()` function.

**Comment by ReagentX** [comment]
I was able to use several Excel functions to build the model you want. I have uploaded the document [here]() so you can see the formulas I used. Here is a screenshot of the resultant PivotTable:

![](https://i.imgur.com/gKtgy4D.png)

**Comment by Viigoo** [comment]
Ah, I see it now...
But still would be nice to have this feature built into the program, because exporting data to excel every game can sometimes be wearisome (not to mention performing manual calculations)

Anyway thanks for help :)
