### ISSUE TITLE
[Bug] Player details don't change when changing matches

### ISSUE THREAD

**Issue by DavidA122** [akiver/CSGO-Demos-Manager#242]
After viewing my player details for one match, when looking at my player details for a different game, all of my stats will show the stats from the previous game. However, the list of kills will change, as will the round details.

Player stats summary, Duels and Clutches will not update. Can't confirm Economy/Damages.

OS: Windows 10 Current Branch
App Version: 2.11.2

**Comment by akiver** [comment]
fixed with d6be838c6e747e360563036bbaba5d6781d300a3
