### ISSUE TITLE
[Suggestion] adding "time thrown" to the "stuffs" category

### ISSUE THREAD

**Issue by msattam** [akiver/CSGO-Demos-Manager#250]
The time of the nade being thrown is already available in the timeline, but for exporting purposes, it is a bit tedious to put my mouse over the timeline symbol to see when it was thrown and by who. If times were to be added into the stuffs category along with the information already there (and if the stuffs category is able to be copied and pasted), this would help very much with exportation efforts. 

Thanks!

**Comment by ReagentX** [comment]
In the meantime, check the JSON file in AppData\Roaming\AkiVer\CSGO Demos Manager for flash events and grenade damage events.
