### ISSUE TITLE
[Bug] - Match was not correctly analyzed

### ISSUE THREAD

**Issue by v1n1akabozo** [akiver/CSGO-Demos-Manager#253]
Some matches are not being analyzed correctly, my last two were missing a round and it's statistics.

![evidence1](https://user-images.githubusercontent.com/17347657/30465782-afef1f82-99af-11e7-8efb-a2cc5427e83f.png)
![evidence2](https://user-images.githubusercontent.com/17347657/30465783-afef5358-99af-11e7-914b-793e8e034ff3.png)

**Comment by akiver** [comment]
Do you have the demos please?
