### ISSUE TITLE
Demoes is not downloading

### ISSUE THREAD

**Issue by BeansSi** [akiver/CSGO-Demos-Manager#256]
Hello

We, a friend and I, have a problem downloading ESEA demoes.
I dont get any information about recently played matches.
My friend get notification that there is 5 demoes ready to download, but nothing happens.

Anyone else get this issue?
And is it getting fixed?

Best Regards
Beans

**Comment by akiver** [comment]
ESEA demos? The download feature is working only with matchmaking demos.
