### ISSUE TITLE
ESEA Demos: Wrong Team Gets Points

### ISSUE THREAD

**Issue by ConnorJennison** [akiver/CSGO-Demos-Manager#261]
When analyzing an ESEA demo, the scores are reversed for each team. Ex: If Team A wins 16-5 over Team B, then it will show that Team B won 16-5 in the program. Here is a screenshot of my recent match, and a link to the match page (https://play.esea.net/index.php?s=stats&d=match&id=11621568)
![poop](https://user-images.githubusercontent.com/17735436/32203494-c7f40a74-bda0-11e7-87d0-1b8382ed0153.PNG)

I don't know how much of this relates to the issues with ESEA demos that you can't fix, or how difficult it is to have each team's scores reflected correctly, but just wanted to bring this up.  (Weirdly though I think the stats are correct)

**Comment by ConnorJennison** [comment]
Also I know that it has 15 because the demo terminates early server side and thats out of your control.

**Comment by ConnorJennison** [comment]
Also note it has each team on the right side each half, just the team winning the round is wrong.

**Comment by quest1onmark** [comment]
I have the same problem. Additionally it won't analyze ESEA demos to the end.
