### ISSUE TITLE
How to paste the API key into "steam_appid.txt"

### ISSUE THREAD

**Issue by Floraly** [akiver/CSGO-Demos-Manager#262]
inside the text file there is 730 the Game ID of CSGO on Steam already.

Should I just replace 730 with my API Key or do I need to put my API key in the next line?

**Comment by akiver** [comment]
This is not the right file, your Steam API key has to be pasted in `steam_api_key.txt` not `steam_appid.txt`.
`steam_appid.txt` is used by `steam_api.dll` to get last matchmaking user's matches.
