### ISSUE TITLE
Several actual Demos leading into parse Error! This Demos could be processed by csgostats.gg

### ISSUE THREAD

**Issue by Floraly** [akiver/CSGO-Demos-Manager#265]
Hello I got now 4 Demo Files that are throwing errors on Analysing with CSGO Demo Manager. The Demos are not corupt and are able to be parsed by csgostats.gg but not by CSGO Demo Maneger itself.

Did Valve changed something here? The Demos that could not be processed came from different relay Server! 187 and 190

**Comment by roguecode** [comment]
I'm having the same. Here is an example: CSGO-KeGZr-xSCP7-5djFe-i229K-5b9eD

**Comment by Floraly** [comment]
It will be fixed soon! :-)

**Comment by akiver** [comment]
Fixed in 2.12.0 #252
