### ISSUE TITLE
Hungarian translation

### ISSUE THREAD

**Issue by aliendaking** [akiver/CSGO-Demos-Manager#269]
Hello guys, i'm started working on the hungarian translation! :) 

Cheers,

aLieN

**Comment by akiver** [comment]
Hungarian translation added, thank you  :)

**Comment by aliendaking** [comment]
Thank you! :)

**Comment by aliendaking** [comment]
Hello Akiver, 
i've downloaded the new version of the CSGO DM, and as a i see so far, the hungarian translation is not working. Can you give me direction, what's wrong?
Best Regards,
aLieN

**Comment by akiver** [comment]
Sorry I forgot to add Hungarian files in the installer -_-
It will be in the next release.

**Comment by aliendaking** [comment]
Haha, no problem. :D 
Thanks for your answer!
