### ISSUE TITLE
CSGO Demo Manager opens but can't see UI

### ISSUE THREAD

**Issue by mew351** [akiver/CSGO-Demos-Manager#271]
Hey, I was using CSGO Demo Manager for about a week and everything was working amazingly well, now when it opens I can see the tray icon and can right click like this
![image](https://user-images.githubusercontent.com/12377381/34244137-de16460e-e5d8-11e7-8320-f68dd967b25e.png)

But when I try to click Show CSGO-DM it doesn't do anything, just appears in my taskbar but doesn't actually react/let me do anything and then eventually closes...
![image](https://user-images.githubusercontent.com/12377381/34244164-f601b0aa-e5d8-11e7-88b3-2404f7177a68.png)

**Comment by mew351** [comment]
Anybody know a fix?

**Comment by akiver** [comment]
Never seen this before, try to re-install the app and follow this instructions to cleanup everything https://csgo-demos-manager.com/docs/general (App crash on startup section)

**Comment by mew351** [comment]
That fixed it!
Thanks so much! I really missed using this tool! @akiver
