### ISSUE TITLE
[Potential Bug] ADR not being calculated correctly.

### ISSUE THREAD

**Issue by Kikerechu** [akiver/CSGO-Demos-Manager#272]
Hello,

I noticed yesterday a bug when calculating ADR. CSGO DEMOS MANAGER was giving a value, while in-game ADR table cell gives another. 

![image](https://user-images.githubusercontent.com/25110934/34633337-d2bdf9dc-f27b-11e7-87f4-adfabbb4f44c.png)
 _This is taken from the first round of a match_

I'm using player _LizorGOD_ becaue it can crearly be seen how he just hits 1 bullet the whole round. According to CSGO DEMOS MANAGER _LizorGod_ has done **132 TDH** (Total Damage Health).

[https://youtu.be/PZW1VHRKUdk](https://youtu.be/PZW1VHRKUdk)

As you can see in the video above, the player only hits 1 bullet making 86 damage (second 34) in the whole round. CSGO displays ADR calculation after the round, being of course, 86 (86 dmg/1 round).

![2018-01-06 00-25-29 00_02_01_59 imagen fija002](https://share.ksnetwork.es/images/XEEPJkqrD492Lw9.png)
 _Screenshot of the start of the second round_

Is this intended in some way? Or is it a bug?

.dem used can be found here: [https://dl.ksnetwork.es/2.dem](https://dl.ksnetwork.es/2.dem)

**Comment by akiver** [comment]
Change the demo's source to eBot to have the correct data.
I will flag demos coming from https://ksnetwork.es/ as eBot by default instead of Valve.

**Comment by Kikerechu** [comment]
That would be magnificent. By the way, changing the source fixed the problem.

I've been analyzing how ADR works in CSGO DEMOS MANAGER. From what I can see, it takes into account friendly fire and doesn't stop counting on round_end but round_start. So (let's say common) friendly fire once the round ended is still taken into consideration.

**Comment by 0BuRner** [comment]
A thrown nade before round end and exploding after round end should be taken into account

**Comment by akiver** [comment]
Source detection added with 576e47a97c65dd87c50dc058f7789ddf24274076
