### ISSUE TITLE
Rund Number is wrong

### ISSUE THREAD

**Issue by Cookieseller** [akiver/CSGO-Demos-Manager#274]
If a match is restarted (beginning of a match), all rounds are correctly reset, however as a new round was already created at round start, this `Demo.Rounds.Count + 1` will resolve to 2 instead of being 1 as would be correct, resulting in two "second" rounds.
This can be resolved by considering the current round when calling `Demo.Rounds.Clear()`.

Can be reproduced in the following [demo](https://www.hltv.org/matches/2311511/refuse-academy-vs-freeibp-yoggi-yalla-cup-2017)

**Comment by akiver** [comment]
I tested with both demos and rounds number are correct.
Which one is incorrect?

**Comment by Cookieseller** [comment]
I can't reproduce it either, seems that it has been fixed in the meantime.
