### ISSUE TITLE
Importing Demos via share code (Bug?)

### ISSUE THREAD

**Issue by YoBii** [akiver/CSGO-Demos-Manager#276]
I have just started using this tool and have to say it's awesome!
Unfortunately I'm having problems adding demos via share code. On multiple occasions I've tried to add demos via their share code. The demos were only minutes to hours old. I got the codes from friends or twitch streams. 
Every time I try to add them to the manager it fails and gives an "Demo link has expired or you already have it in your download folder."-Error. I am sure I don't have them in my download folder, though.

**Comment by daniel11609** [comment]
same for me when trsying to download my own demos it says no new demos availible or something

**Comment by YoBii** [comment]
That could be a cs:go bug. Can you download the particular demo ingame?

**Comment by daniel11609** [comment]
Unfortunately I can't. None of the demos from the last days Am 16.01.2018 12:10 vorm. schrieb YoBii <notifications@github.com>:That could be a cs:go bug. Can you download the particular demo ingame?
