### ISSUE TITLE
Multi-select doesn't work

### ISSUE THREAD

**Issue by CorySanin** [akiver/CSGO-Demos-Manager#278]
I used to be able to select multiple demos and and have them all analyzed in one go. However, after I upgraded to 2.13.1, this happens:

![issue](https://user-images.githubusercontent.com/2897351/35544879-2b98796a-0532-11e8-8b97-c9d7f9d84d47.gif)

It only analyzes the highlighted one.

**Comment by NitaiCharan** [comment]
I get the same issue

**Comment by decyph3r** [comment]
+1, I get the same issue as well. Was not present in the earlier versions

**Comment by akiver** [comment]
fixed in 2.13.2
