### ISSUE TITLE
[Suggestion] Show victimuid/attackeruid of focused player in movie generation

### ISSUE THREAD

**Issue by Bene-GG** [akiver/CSGO-Demos-Manager#279]
This could help with the `mirv_deathmsg block !<uid> *` command to hide the killfeed for all other players, I'm not sure if it's possible though.

**Comment by Darkhandrob** [comment]
Also combined with `mirv_deathmsg highlightId <uid>` would adjust the deathnotice to look like the pov one or from highlights/lowlights in gotv. (Maybe also `mirv_deathmsg cfg noticelifetime 60`, so all kills are visible during the whole round. But that command should be activated after the `demo_gototick ` command or else all frags from the round before are also visible.)

**Comment by akiver** [comment]
HLAE 2.47.0 required https://github.com/advancedfx/advancedfx/releases/tag/v2.47.0
