### ISSUE TITLE
Share code not working 

### ISSUE THREAD

**Issue by ningwang747** [akiver/CSGO-Demos-Manager#282]
<img width="1001" alt="screen shot 2018-02-10 at 8 16 06 pm" src="https://user-images.githubusercontent.com/18260727/36062077-fcc72650-0e9f-11e8-9991-4182befcd417.png">

Demo link not expired and not in my download folder

**Comment by akiver** [comment]
Could you send me the sharecode?

**Comment by akiver** [comment]
There have been some fixes related to share code in recent versions, please try the last version.
