### ISSUE TITLE
Recording Hlae Streams Support

### ISSUE THREAD

**Issue by Darkhandrob** [akiver/CSGO-Demos-Manager#285]
Currently there is no option to switch from recording with `startmovie` to `mirv_streams record start`, which will record different streams for dof or greenscreen simultaneously. The movie name is also saved differently with `mirv_streams record name <movie name>`.

https://github.com/advancedfx/advancedfx/wiki/Source:mirv_streams

**Comment by akiver** [comment]
Internally it's using `mirv_streams record start`.

You can add HLAE streams in the CFG panel, this CFG is executed after that the demo has been loaded.
For example, if you add (taken from the HLAE doc):
````
mirv_streams add depth mydepth
mirv_streams add depth myDepthF
mirv_streams edit myDepthF depthValMax 8192.0
mirv_streams edit myDetphF captureType depthF 
````
A folder called `takeXXXX` generated by HLAE will be created in the output folder destination.
This folder will contains streams subfolders `mydepth` and `myDepthF` containing all tga files.

You can uncheck the option to delete all raw files after recording to not delete them if you want.
