### ISSUE TITLE
download from share code nothing happens

### ISSUE THREAD

**Issue by lyhyl** [akiver/CSGO-Demos-Manager#288]
CSGO-wJiEa-2tTne-cX754-DLd7a-rjNYE

**Comment by lyhyl** [comment]
Dug into the code and found that replay234.valve.net is down!
Most of the same problem comes from the broken valve server!

**Comment by akiver** [comment]
http://replay234.valve.net/730/003262712255476662363_1030919930.dem.bz2

Server problem :/
