### ISSUE TITLE
Is there a way to reset heatmap when choose different player?

### ISSUE THREAD

**Issue by micturkey** [akiver/CSGO-Demos-Manager#299]
Every time I generate a new heatmap, it just cover the previous one and they become one heatmap, which contains two kinds of data from two choice.
I know this may be a function for user for combined analysis, so is there a way to reset except go back to demo list and re-enter? 
A reset button will be appreciated.

**Comment by micturkey** [comment]
Wait..It seems that this problem happend randomly..

**Comment by akiver** [comment]
I can't reproduce the issue, please re-open the issue with reproduction steps if you encounter the bug.
