### ISSUE TITLE
Manager starts new CS GO process every time

### ISSUE THREAD

**Issue by mifkys** [akiver/CSGO-Demos-Manager#30]
Hello! CSGO Demos Manager starts CS:GO process every time when I press "watch demo" or "watch round" even if CSGO already started. Can CSGODM play demo in already started csgo process?

**Comment by JSadones** [comment]
For me it gives me a steam notification with "app is already running"

**Comment by 0BuRner** [comment]
Hi mifkys,
Theoritically you shouldn't be able to launch multiple csgo process, but you should have the steam notification like JSadones have. Or no problem like me, as the running game is launching the clicked demo... Pretty weird... Do you have multiple Steam accounts at the same time ? Sandboxie ? What's your OS ?

**Comment by mifkys** [comment]
No, I means that CSGODM try to run another CSGO process when one already running. Can CSGODM run demo in already running CSGO process?

**Comment by JSadones** [comment]
I read something that normally when you click like a link for a demo, CSGO (if it's already open) should detect this and open the demo. Not creating another CSGO process.

**Comment by 0BuRner** [comment]
@JSadones yep, this is the behaviour I get on my computer...
Dunno how to solve your problem right now.
This isn't related to CSGODM in any case...
