### ISSUE TITLE
[Question] "localdata" Property meaning

### ISSUE THREAD

**Issue by agpmilli** [akiver/CSGO-Demos-Manager#302]
Hi,

I was going through your application and discovered that you were extracting data I cannot extract from the demos (ducking and velocity) and when going through the code I found out that you were taking these properties with `playerEntity.FindProperty("localdata.PropName")`
I cannot find out where this localdata comes from, is it possible to have explanation or insight ?

Thanks in advance.

**Comment by akiver** [comment]
Hi! Sorry I didn't notice your issue while sorting new issues.

Demos files contain entities (players, weapons, projectiles...) and these entities have "DataTables".
DataTables are records of field name + values.
For example, a player entity has a DataTable named `DT_CSPlayer` which contains a field `m_iAccount`. Its value is an integer corresponding to the amount of money the player has.
DemoInfo flattens all properties, this is why you can access them doing `entity.FindProperty("dataTableName.propertyName")`
