### ISSUE TITLE
Wrong scoreboard in official match

### ISSUE THREAD

**Issue by GUiHKX** [akiver/CSGO-Demos-Manager#308]
CS:GO Demos Manager shows match ended at 15-10, but CS:GO client shows 16-10. Frag counter is wrong as well for some players.

CS:GO Demos Manager:

![csgodemosmanager](https://user-images.githubusercontent.com/626206/39294472-38809e2c-4912-11e8-99da-2e40e1d97ad8.png)

CS:GO client:

![20180426051507_1](https://user-images.githubusercontent.com/626206/39294487-40fd9866-4912-11e8-83e6-dc1a500be4f8.png)

---

DEMO: 

Share Link: steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-QUTnS-yuxSA-qU3n9-MKwOE-od5yD

Mirror: https://mega.nz/#!SE03EQyJ!38O8jxGHegQ4sAZ-CYu__9wqYyQecSRheprS0yoJaoM

**Comment by Cookieseller** [comment]
This happens due to the bug described in #273. For round number 21 the EndFreezetime Event is not fired, resulting in the round not being recorded.
