### ISSUE TITLE
CSGODM does not correctly determine the ticks of start of rounds

### ISSUE THREAD

**Issue by mifkys** [akiver/CSGO-Demos-Manager#31]
In demo details page ticks of start of rounds determine not correctly. If I press "watch demo" demo plaing not from start of round. For example, it plays from 34429 tick but round starts at 30244 tick (tick from demoui).

**Comment by 0BuRner** [comment]
Can you give a link to your demo ? I'll be easier to debug.
Thx for reporting it

**Comment by mifkys** [comment]
http://1drv.ms/1HBUU5A
I saw 6 round (34429 tick) but it really starts at ~30200 tick

**Comment by akiver** [comment]
Issue fixed with EHVAG/demoinfo@b20e86f10dca8f507f8d79097e19ae35ed72bfec
