### ISSUE TITLE
Support for BO3 match demo files?

### ISSUE THREAD

**Issue by Teroan** [akiver/CSGO-Demos-Manager#321]
Looking at some of the tournament demos from HLTV and noticed some of them do not analyze properly. Thinking these are "best of 3" matches all in one demo. Not sure if this is out of the scope of this program but analytics you can do with CSGODM are really useful for inspecting demos from tournaments.

Heres an example GOTV demo i'm trying to analyze in the manager.
https://www.hltv.org/matches/2323620/virtuspro-vs-singularity-esea-mdl-season-28-europe

**Comment by akiver** [comment]
> Thinking these are "best of 3" matches all in one demo.

Sorry but this is an edge case, tournament organizers should record each game separately.
Not only to make easier demos parsing but also for demos viewing comfort (to avoid fast-forwarding until the map you want).
It would require too much work for this rare case.
