### ISSUE TITLE
HLAE mirv_deathmsg breaking changes #PanoramaUI

### ISSUE THREAD

**Issue by dtugend** [akiver/CSGO-Demos-Manager#326]
Hi want to inform you that there are breaking changes to mirv_deathmsg with the #PanoramaUI edition of HLAE:
https://github.com/advancedfx/advancedfx/releases/tag/v2.50.6-panoramaui

These will affect CSGO-Demos-Manager.

Please note that things also improved, since now you can set (attacker|vicitim|isLocal=1) per filter entry to get the highlighting. Alternatively only set mirv_deathmsg localplayer. There are also other improvements.
The console interface to mirv_replace_name changes as well.

**Comment by dtugend** [comment]
The changes are now live: https://github.com/advancedfx/advancedfx/releases/tag/v2.51.0

**Comment by dtugend** [comment]
Hi, not sure if you noticed and if there's time to implement that, but you don't need to switch localPlayer before every death message anymore (from the examples linked in the additional info link above):

```
// Repeat for every <XUID> that shall have red border:
mirv_deathmsg filter attackerMatch=x<XUID> attackerIsLocal=1
mirv_deathmsg filter victimMatch=x<XUID> victimIsLocal=1
````

In case it's a POV demo, you should at least set this for other players that shall not have red border (at least for the POV player:
```
// Repeat for every <XUID> that shall have red border:
mirv_deathmsg filter attackerMatch=x<XUID> attackerIsLocal=0
mirv_deathmsg filter victimMatch=x<XUID> victimIsLocal=0
````

**Comment by akiver** [comment]
Done in 4a7cf30bb8bfa08b2ab0f270da74c7e13cfeb870, thanks!
