### ISSUE TITLE
Can't change demo source to POV

### ISSUE THREAD

**Issue by IncPlusPlus** [akiver/CSGO-Demos-Manager#329]
Hello. I recently started playing CSGO again and I'm on a new computer. I moved all my demos (POV and Valve Matchmaking) from my old laptop to my desktop. They are now in their proper folders. Many of the imported Valve Matchmaking demos are from a while back are understandably corrupted as many changes have occurred to how demos are made. However, What I find strange is that a large number of my POV demos are corrupt. It seems to be because their source is marked as being from Valve Matchmaking which is incorrect. This would be an easy fix if I could change the source of the demo back to POV but there is no option to do so. I have attached an image showing the issue.

![image](https://user-images.githubusercontent.com/6992149/42715441-0f36f8cc-86c5-11e8-900b-ecf89d4197fb.png)

**Comment by 0BuRner** [comment]
If I remember correctly, POV demo aren't supported.

**Comment by IncPlusPlus** [comment]
You're correct in a sense, @0BuRner. However, they can still be listed properly in the demo manager. I did it all the time on my old laptop. Notice how the ones that aren't highlighted in red have an eyeball icon instead of the Valve logo. Those are the POV demos. What @akiver means by "POV demos aren't supported" is that POV demos cannot be analyzed (i.e. no damage stats, kill stats, scoreboard, heatmap, etc.).

**Comment by akiver** [comment]
This is because the hostname is not a valid localhost address, I added the ability to change the source to pov.
