### ISSUE TITLE
Demo cannot be analyzed

### ISSUE THREAD

**Issue by tiagojsrios** [akiver/CSGO-Demos-Manager#330]
Hello. 

I have a demo that I can't analyze and I don't know why. When I press analyze button it does his thing, but at the end every stat is reseted and it shows a message "The demo may be too old, if not...".

I'm going to send an e-mail with demo attached, as well.

**Comment by 0BuRner** [comment]
Upload demo somewhere and provide link please.

**Comment by tiagojsrios** [comment]
I already sent an e-mail to contact@csgo-demos-manager.com with demo attached! Thanks for answering :)

**Comment by akiver** [comment]
Hi, the demo link is private, I can't download it.
Based on the demo's name this demo is not from a Valve server so please be sure this demo is coming from one of the supported third party services (ESEA, FaceIt, CEVO, eBot or PopFlash)
