### ISSUE TITLE
App Crashing when tried to watch demo

### ISSUE THREAD

**Issue by FlowingSPDG** [akiver/CSGO-Demos-Manager#337]
I can analyze demos but can't watch demo.
I tried "Movies" "Watch" "Watch round" but its all crashed.
and I guess demosmanager creates .vdm file in demo's directory.

I re-installed demosmanager and CS:GO,but its not working.
please help.

**Comment by akiver** [comment]
Does the game crash or the app?
Did you try from the game? With the `playdemo` command or the `demoui`?

**Comment by FlowingSPDG** [comment]
app. `playdemo` and `demoui`(Shift+F2) is working fine.
I tried to watch demo after changed CSGO's directory,and now it's working properly somehow...
Thanks for help,I will re-open this issue if It happens again.
