### ISSUE TITLE
CSGODM always starts CS:GO in windowed mode

### ISSUE THREAD

**Issue by mifkys** [akiver/CSGO-Demos-Manager#34]
Why CS:GODM always start CS:GO in windowed mode, 4:3 aspect ration and with 1024x768 resolution? Also can it start CS:GO with parameters which i enter for the game in Steam library (-threads 4 -freq 60 etc.)?

**Comment by 0BuRner** [comment]
There is something wrong with your Steam install or configuration... CSGODM uses Steam to launch the app, so it should use the launch options when starting the game. You're the only one having this issue...
And I don't think it's related to CSGODM

**Comment by akiver** [comment]
Options such are resolution, fullscreen are in the settings menu.
I added the ability to add custom parameters, it works the same as the steam library option.

**Comment by mifkys** [comment]
It is strange. I have default steam and csgo installations. In game's parameters enter: -noforcemspd -noforcemaccel -noforcemparms -nojoy -novid -tickrate 128 -cl_interp 0 -cl_interp_ratio 1 +exec mif -threads 2 -freq 60

Windows 8.

Thanks for solution!

**Comment by akiver** [comment]
I'm not sure to understand properly but when you start the game from CSGO Demos Manager your launch options set from your library are not used.
If you are using the last release (2.1.0) you can't add custom parameters.
It will be available on the next release.
You can however build by yourself the last development release and use the parameters options.
Thanks
