### ISSUE TITLE
Game won't launch when trying to record movie

### ISSUE THREAD

**Issue by The1Retro** [akiver/CSGO-Demos-Manager#342]
Whenever I try to make a movie, I get this error:
```
AfxError #2001: 
Title: Loader failed.
Description: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
Inner exception: System.ApplicationException: Failed to launch program, error code: 5
   at AfxGui.Loader.Load(IEnumerable`1 getHookPathCollection, String programPath, String cmdLine, String environment, Boolean showErrorMessage)
```
This happens on every demo I try to make a movie off of. Oddly enough, I don't get the same or similar error when I "Watch Highlights" or "Watch Lowlights." I'm not sure what's going on. I validated my game files, reinstalled CSGO Demos manager, ran as administrator but nothing has worked. I'm going to continue troubleshooting but I'm kind of clueless as to whats going on atm.

**Comment by akiver** [comment]
Related to HLAE https://github.com/advancedfx/advancedfx/wiki/Half-Life-Advanced-Effects, make sure to update HLAE to the last version from the UI.
