### ISSUE TITLE
Additional parameters for movie maker HLAE

### ISSUE THREAD

**Issue by hellkama** [akiver/CSGO-Demos-Manager#348]
I need to specify these additional parameters for HLAE for the movie maker.

-panorama -afxDetourPanorama

Additional parameters are available for "Watch" but not for "Movie" feature.

![image](https://user-images.githubusercontent.com/6357695/49115986-ec6e2580-f2a4-11e8-8a0b-84e6cf195a67.png)

**Comment by TotalEclipse08** [comment]
I would also really appreciate this as an option, I can use CSGODM for most of my recording but not all due to this.
