### ISSUE TITLE
Faceit Demos will not analyze. Always results in an error. Since update. 

### ISSUE THREAD

**Issue by andrewdurkiewicz** [akiver/CSGO-Demos-Manager#349]

**Comment by IT6uru** [comment]
Make that all demos won't analyze.

**Comment by lkaczmarek-dev** [comment]
I have also encountered this problem.

**Comment by andrewdurkiewicz** [comment]
Please note that I have noticed that this only occurs for games after the update. Older demos still analyze even if they are just downloaded

**Comment by akiver** [comment]
Hi, it should be fixed soon https://github.com/StatsHelix/demoinfo/pull/154

**Comment by guihkx** [comment]
I've built the DemoInfo.dll with this new fix. I've tested with a few demos and it works for me:

[DemoInfo.zip](https://github.com/akiver/CSGO-Demos-Manager/files/2660276/DemoInfo.zip)

Unzip it, and put the DLL file in C:\Program Files (x86)\CSGO Demos Manager
