### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Devilklone** [akiver/CSGO-Demos-Manager#35]
I changed the Folder Directory to my replay Folder where i have 655 Demos now the Demo Manager crashes everytime and wont respond. Any Solutions? 
16GB Ram. Windows 7 64bit
Demo Manager 64bit.

**Comment by akiver** [comment]
One of your demos is corrupted, check if there is any 0kb .dem file, it should be the one which cause the crash.
It will be fix in the next release.
