### ISSUE TITLE
Dangerzone Update broke valve demo analyzer

### ISSUE THREAD

**Issue by Newbrict** [akiver/CSGO-Demos-Manager#350]
I have uploaded the demo to google drive [here](https://drive.google.com/file/d/1qGKlK53BYlX2waejNkauSeqMluliNZq2/view?usp=sharing)

All new match making demos give me the following error:

![image](https://user-images.githubusercontent.com/1683041/49659597-991d7500-fa12-11e8-957d-cdd919437e14.png)

**Comment by akiver** [comment]
https://github.com/akiver/CSGO-Demos-Manager/issues/349#issuecomment-445420554
