### ISSUE TITLE
2.13.8 detected as virus?

### ISSUE THREAD

**Issue by felixbauerschaefer** [akiver/CSGO-Demos-Manager#358]
Hey, this is kinda strange. I've been using your tool for over 3 years now and now it's the first time after reinstalling it that Windows Security Defender marked it as a Trojan virus. Maybe check your Repositories someone might have uploaded a corrupted version for CS:GO Demo Manager.

![capture](https://user-images.githubusercontent.com/34807323/50386246-88901e80-06e3-11e9-8b45-b29e69988497.PNG)

**Comment by akiver** [comment]
The app is not signed (it costs $$), some anti virus may report it as a threat but it's a false positive.

**Comment by felixbauerschaefer** [comment]
Can you give us a download hash I've seen those a bunch of times. And these might help with verfication that you're software is unharmful even though it's not signed and might get recognized by Windows SmartScreen so that we confirm that's the program we're downloading is at least valid?

**Comment by akiver** [comment]
I will add a checksum for the next release but it will not prevent anti-virus / SmartScreen warnings, these are different things.

**Comment by akiver** [comment]
Releases now include a SHA1 checksum file https://github.com/akiver/CSGO-Demos-Manager/releases
