### ISSUE TITLE
Round sorting chaos

### ISSUE THREAD

**Issue by wordlesswind** [akiver/CSGO-Demos-Manager#359]
When I choose to use weapons to sort, round is not sequential.
What exactly is it sorted by?
![1](https://user-images.githubusercontent.com/9050713/51117053-a155a500-1847-11e9-8c81-46e74c03db2f.png)

**Comment by 0BuRner** [comment]
It's sorted by weapon as you chose. I guess there is no multi-columns with priority sorting thus it's sorting other columns randomly.

**Comment by wordlesswind** [comment]
@0BuRner
This is not reasonable and should be judged by the number of rounds.
