### ISSUE TITLE
Incorrect kill totals and other data

### ISSUE THREAD

**Issue by sambooo** [akiver/CSGO-Demos-Manager#36]
The latest update is causing incorrect kill totals to be reported when analysing demos from my server. Probably related to the knife round not being culled.
Demo link: https://dl.dropboxusercontent.com/u/30829668/CSGO/pug_de_cache_2015-09-29_20.dem

**Comment by roknir** [comment]
I'm also seeing weird accounting of on 2.2.0.  If I go into the details page for a specific demo and choose myself as the player to show stats for, there are 2 rounds (round 3 and 11) that say I had both a 2K and a 3K.  If I watch those rounds, I actually only had a 2K in each of them.
Demo link: https://play.esea.net/index.php?s=servers&d=download_replay&id=4499000

**Comment by akiver** [comment]
@sambooo I added a trick to fix the problem but demos coming from community servers are not officially supported.

@roknir it's fixed.

Thanks
