### ISSUE TITLE
Watch highlights/lowlights don't work

### ISSUE THREAD

**Issue by lkaczmarek-dev** [akiver/CSGO-Demos-Manager#360]
Options watch highlights/lowlights don't work for some time, I think since big CS GO update (with battle royal feature). I've tried it on actual faceit demos. Game runs but doen't playback demo, just goes to main menu.

Testes on the 2.13.8 version.

**Comment by akiver** [comment]
If the game stays on the main menu it's probably because of a special character / space in the demo's filepath.  
I tested the hihglights / lowlights feature and it worked.  
Please read the doc https://csgo-demos-manager.com/docs/watch and check your console to be sure
