### ISSUE TITLE
Export xls Round_win incorrect values

### ISSUE THREAD

**Issue by Crus4** [akiver/CSGO-Demos-Manager#363]
Apologize for my English not very good.
Export as XLS function and the excel sheet 'Rounds' line F 'End reason' sometimes appear 'Unknown'.
It causes an error in sheet 'Entry Hold Kills Rounds' and 'Entry Kills Rounds' Line G 'Round Won'.
For example, If Rounds 1  'End reason' appear 'Unknown', although the 'Winner' show correct result 'CT'
but sheet 'Entry Hold Kills Rounds' line G 'Round Won' round 1 appear 'no'(CT side got the Entry Hold Kills).
I analyzed many of the same cases.It seems the reason is loss side success save the gun,so the winner clan not kill all enemy.
I hope that I clearly described the problem. If it is wrong with my use of the software, hope you can point it out.
Finally, this software makes my understanding of the CS:GO deeper,thx a lot!

**Comment by akiver** [comment]
Could you upload an affected demo please?
