### ISSUE TITLE
Submitting demo to csgostats.gg is broken because their cloudflare settings are even stricter than they already were

### ISSUE THREAD

**Issue by CorySanin** [akiver/CSGO-Demos-Manager#366]
The response coming back to the client looks something like this:

![image](https://user-images.githubusercontent.com/2897351/54464968-ea8e7c00-4746-11e9-895c-1ef4b693d93d.png)

Hopefully the site relaxes their cloudflare configuration and nothing has to be done, but otherwise the feature is broken in Demos Manager. SAD.

**Comment by CorySanin** [comment]
An update on the matter: [CS:GO Stats on Twitter](https://twitter.com/csgostatsgg/status/1106990130462629889)

**Comment by Kinc4id** [comment]
Any updates about this? Is this something that can be fixed someday or will it be broken until csgostats changes their settings?

**Comment by CorySanin** [comment]
In theory, a workaround could be possible. However, it would be a lot of work and there's no need to do all of that when [csgostats will eventually fix it](https://twitter.com/csgostatsgg/status/1107847741772832769). Or I hope they do. I still get rate limited just from browsing the site so who knows.

**Comment by rchh** [comment]
Hello! Can anyone confirm this is now fixed? 

@CorySanin If you're getting rate limited just browsing the site, please log exact page visits with timestamps when replicating this. We obviously have a threshold as we're prone to people trying to scrape the data. We do not mean to interupt standard website usage :)

**Comment by CorySanin** [comment]
Yep it appears to be working again. Thank you!
