### ISSUE TITLE
ffmpeg framerate are not correct

### ISSUE THREAD

**Issue by int128fly** [akiver/CSGO-Demos-Manager#369]
Just wanna report a bug, when setting up video framerates in the UI for ffmpeg it doesn't set the -r parameter properly (stuck at 60) so it generate a video file that is 60 fps.

For people who want a quick fix just add -r [framerates] into the Extra parameters section

**Comment by akiver** [comment]
I couldn't reproduce this issue, the `-r` option is correctly bound to the Framerate option in the ffmpeg panel and the `-framerate` option to the Framerate option in the "General" panel.  
However based on the [ffmpeg doc](https://ffmpeg.org/ffmpeg.html#Video-Options), the `-r` parameter is not recommended to generate videos from images and `-framerate` should be used instead.  
I removed the Framerate option for ffmpeg so there will be no confusion.
