### ISSUE TITLE
"Status" column seems broken since 2.2.0 update

### ISSUE THREAD

**Issue by roknir** [akiver/CSGO-Demos-Manager#37]
I don't know what happened, but the "Status" column seems to be broken since the 2.2.0 update.  I upgraded to 2.2.0, exported my custom settings as part of that upgrade, imported them back in, re-analyzed all of the non-POV demos I have, and the status column is really blank now.  I used to have tons of these cells filled in for the same demos before the upgrade (with maybe the odd blank for a game that was surrendered or I was kicked from), but now, for something around 150 demos, I might have 5 of them filled in with win/loss after analyzing.

**Comment by akiver** [comment]
The status (won / lost / draw) isn't keeped when exporting / importing backup.
The "status" exported / imported is the one defined by right clicking on a demo and change the status (watched / to watch / none).
You have to re-analyze demos to have the updated status (win / lost / draw).

**Comment by roknir** [comment]
I re-analyzed every demo I had and still only had those 2-3 statuses filled in out of 150 demos.
