### ISSUE TITLE
Access Denied!

### ISSUE THREAD

**Issue by Rafael-Leal-Prada-dos-Santos** [akiver/CSGO-Demos-Manager#370]
When i try to open the demo while csgo ir already open i get a "access denied" message..

**Comment by akiver** [comment]
This message is from the game? Windows? csgo?  
How do you "open" the demo? From the app? csgo? Windows?  
If you start to watch a demo from the app, the csgo process is simply killed, make sure to not start steam as admin.

**Comment by akiver** [comment]
Maybe related https://www.csgo-demos-manager.com/docs/watch#steam-client-error
