### ISSUE TITLE
Auto download demos with command line flag

### ISSUE THREAD

**Issue by Tirpitz93** [akiver/CSGO-Demos-Manager#371]
Hello,
would it be possible to set up a command line flag to auto download demos periodically, like at midnight using task scheduler?
For example:

`CSGODemosManager.exe -download all`

`CSGODemosManager.exe -download profile1`

**Comment by ClementCariou** [comment]
For info, it's already partially implemented, type : `CSGODemosManager.exe /download`.
https://github.com/akiver/CSGO-Demos-Manager/blob/740abd94e014a5219f8e1b4400763f82d1c89fa6/Manager/ViewModel/Demos/DemoListViewModel.cs#L1393
