### ISSUE TITLE
Fatal Error:Failed to connect with local Steam Client process!

### ISSUE THREAD

**Issue by AugustMa** [akiver/CSGO-Demos-Manager#376]
Whenever I open  a demo via CSGO-Demos-Manager, I get a pop-up window says:
Fatal Error:fail to connect with local steam client process !
Please make sure that you are running latest version of Steam Client
You can check for Steam Client updates using Steam main menu:
       Steam > Check for Steam Client Updates...

But I checked the steam client, it is indeed the latest version

**Comment by dtugend** [comment]
Usually happens when steam runs with admin rights, since csgo demos manager doesn't

**Comment by AugustMa** [comment]
It works,  thanks bro!

**Comment by akiver** [comment]
I think it has been resolved by the reply of @dtugend.  
But this should be added to the documentation to help others in the future.

**Comment by akiver** [comment]
Added https://www.csgo-demos-manager.com/docs/watch#steam-client-error
