### ISSUE TITLE
Bud demo at last round before the half change

### ISSUE THREAD

**Issue by ZUBAT** [akiver/CSGO-Demos-Manager#377]
Due to the fact that in the last round of the 1st half was delivered bomb, 1 round of 2 half was processed incorrectly, and it was recorded in the 1 half. Because of this, the total score was wrong instead of 16-8 counted 12-12
Url demo http://replay191.valve.net/730/003347807671565680813_1604330035.dem.bz2

**Comment by ZUBAT** [comment]
@akiver can you help me?

**Comment by akiver** [comment]
Hi do you still have the demo?

**Comment by ZUBAT** [comment]
Ahem. Interesting observation.. our team broke up, and the project was shut down while you were answering. Unfortunately now the demo is not able to provide.
