### ISSUE TITLE
hlae's new ffmpeg folder is cleaned after updating to new versions

### ISSUE THREAD

**Issue by Purple-CSGO** [akiver/CSGO-Demos-Manager#378]
After hlae's 5-24 update, it supports recording with ffmpeg. But ffmpeg needs to be downloaded from its website and then placed manually into `hlae/ffmpeg/` folder.
I've been using demos manger and hlae installed by dm, but now after automatically updating hlae version with dm, `./ffmpeg` folder is recovered, which **really** causes lots of troubles.
-- --
In addition to that, dm could also support for auto-installing ffmpeg to the correct folder.
-- --
Installing hlae with dm is far too slow in some areas. Could it be possible if I replace files when dm is showing "Installing"?

**Comment by dtugend** [comment]
I should note that we plan to switch advancedfx / HLAE to an Windows Installer based solution due to https://github.com/advancedfx/advancedfx/issues/65 ( Non-ASCII chracters in HLAE install location can cause problems )

**Comment by akiver** [comment]
The last version installs and uses FFmpeg installed in the HLAE `ffmpeg` directory.
During HLAE upgrade, the current HLAE `ffmpeg` folder is now backuped and restored when HLAE has been upgraded.
