### ISSUE TITLE
The homepage is not accessible, so I cannot download it.

### ISSUE THREAD

**Issue by googlepixel** [akiver/CSGO-Demos-Manager#380]
Although it is not an issue regarding the program, 
There's no place to contact, so I upload it here.

**Comment by akiver** [comment]
The website should be back in a few days.  
The problem is that I cannot connect to my account to renew the domain since I moved to an other country (><)

**Comment by akiver** [comment]
You can download the installer from the github releases page https://github.com/akiver/CSGO-Demos-Manager/releases
