### ISSUE TITLE
Cant analyse any demo

### ISSUE THREAD

**Issue by ItzSheldor** [akiver/CSGO-Demos-Manager#383]
Hello, when i try to analyse an demo, its counting the kills and stuff but then returns to 0 or even negative.
![2019-07-21_22h42_53](https://user-images.githubusercontent.com/36795157/61596841-e13b8180-ac08-11e9-8e07-790191a53218.png)

Error Log: https://gist.github.com/ItzSheldor/7a1b5259b5516137cca2c56595127ac8

**Comment by akiver** [comment]
It looks like this demo comes from 99Damage.  
I don't know how the demo recording system is handled by this platform and 99Damage has never been officially supported by the application.  
You should try to change the demo's source to eBot and re-analyze it (don't know if 99Damage is using eBot or not).
