### ISSUE TITLE
Latest version can't lunch cdm...

### ISSUE THREAD

**Issue by Garry050** [akiver/CSGO-Demos-Manager#388]
Windows 10 x64 (1809)

>  Faulting application name: CSGODemosManager.exe, version: 2.13.8.0, time stamp: 0x5c162f28
> Faulting module name: clr.dll, version: 4.7.3190.0, time stamp: 0x5b694768
> Exception code: 0xc00000fd
> Fault offset: 0x004550cd
> Faulting process id: 0x2ff4
> Faulting application start time: 0x01d55f7e81c57d7c
> Faulting application path: C:\Program Files (x86)\CSGO Demos Manager\CSGODemosManager.exe
> Faulting module path: C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
> Report Id: 640380e6-4a11-4eda-af48-1ee755d29f7b
> Faulting package full name: 
> Faulting package-relative application ID:

**Comment by 0BuRner** [comment]
Can you copy/paste application logs? Thé path is mentioned in another issue

**Comment by Garry050** [comment]
It's Windows side problem. If i using Legacy style (i mean win8.1 colored title bar) theme, It's crashing...
