### ISSUE TITLE
Procedure Entry Points can't be located when attempting to watch a demo

### ISSUE THREAD

**Issue by null-zero** [akiver/CSGO-Demos-Manager#390]
Version: 2.13.8

Attempting to have the program launch csgo in any capacity causes these errors

![CSGODemosManager_CSGO_Demos_Manager_2019-09-12_12-59-28](https://user-images.githubusercontent.com/13855377/64808856-a9442100-d55d-11e9-877a-60c22ecd54f5.png)
![CSGODemosManager_CSGO_Demos_Manager_2019-09-12_12-59-47](https://user-images.githubusercontent.com/13855377/64808858-a9dcb780-d55d-11e9-9244-53495df25e34.png)
![CSGODemosManager_CSGO_Demos_Manager_2019-09-12_13-00-00](https://user-images.githubusercontent.com/13855377/64808860-a9dcb780-d55d-11e9-8432-2c9dcf5edb3a.png)
![CSGODemosManager_CSGO_Demos_Manager_2019-09-12_13-00-10](https://user-images.githubusercontent.com/13855377/64808861-a9dcb780-d55d-11e9-91e2-da93f11343f0.png)

**Comment by akiver** [comment]
Did you install https://www.microsoft.com/en-us/download/details.aspx?id=48145?
Try to verify the integrity of CSGO files from Steam.

Here are others possibilities https://www.techjunkie.com/entry-point-not-found-errors-windows/ but I don't think it's related to CSGO:DM

**Comment by null-zero** [comment]
I haven't tried it since then, but trying it now it works again. The only things that have changed are HLAE update and CSGO updates. I'm assuming this was just a one off thing
