### ISSUE TITLE
Suggestion: implementing a name change function e.g (mirv_replace_name 5 "name")

### ISSUE THREAD

**Issue by LlamaLLamaGoose** [akiver/CSGO-Demos-Manager#393]
Do you have any plays of implementing a name change function e.g (mirv_replace_name 5 "Kenny")

Similar how you can select what name you want in the kill feed and what name you want to be highlighed within the movie section.

**Comment by jackbritchford** [comment]
This seems like something you'd want to speak to HLAE/their devs about. As far as I know, all those mirv commands are from HLAE/ActionEffects or whatever it's called

**Comment by LlamaLLamaGoose** [comment]
This function already exists:
https://github.com/advancedfx/advancedfx/wiki/Source:mirv_replace_name

I was hoping to get this implemented into the GUI for the movie section since it already finds the ID.

From Movie/MovieService.cs:

// hightlight kills for selected players
foreach (long steamId in _config.HighlightSteamIdList)
{
  // when the player is the attacker only
  command = $"mirv_deathmsg filter add attackerMatch=x{steamId} attackerIsLocal=1";
  generated += string.Format(Properties.Resources.execute_command, ++actionCount, GOTO_TICK + 1, command);
}

Since the software already gets the ID required to only allow certain players to be highlighted adding an option to change the name will be adding a field to enter the name and using the same ID it gets from that function.

mirv_replace_name (ID it pulls already) (New name in the feed)
command = $"mirv_replace_name {steamId} $newname";
