### ISSUE TITLE
Heatmaps for Workshop maps

### ISSUE THREAD

**Issue by Exodussy** [akiver/CSGO-Demos-Manager#397]
Right now there is no way to generate heatmaps for Workshop maps. It'd be totally cool if that could be implemented.
I can imagine an option to upload an overview image for the respective map when clicking on heatmaps. That way it would be really flexible.

Also: I'd like to see an option for player paths heatmaps.

These would be really useful to analyze playtest demos which would help mappers a lot.

**Comment by akiver** [comment]
Duplicate #306
It will be available in the next major version
