### ISSUE TITLE
ffmpeg configuration + Nvidia HW acceleration

### ISSUE THREAD

**Issue by jackbritchford** [akiver/CSGO-Demos-Manager#398]
Rewrote this due to idiocy and not reading the ffmpeg manual
--
I was trying to get Nvidia GPU/HW acceleration working and I'm not sure if the version of ffmpeg included actually has the necessary stuff (--enable-cuda --enable etc etc)

I got a build of ffmpeg which does, however the app (demo manager) doesn't allow me to change the encoding from libx264 to h264_nvenc.

I'm gonna retry again with just --hwaccel on ffmpeg and by pasting the command manually, but would it be possible to get a tab on configuration/etc to allow you to set some defaults for ffmpeg (extra cli args) as well as override some currently hardcoded things.

Thanks, will let you know how I get on.

**Comment by jackbritchford** [comment]
https://ffmpeg.zeranoe.com/builds/

Found this if of interest, again I'm not sure what the licensing is like with the nvidia libraries baked in but, if they're all good then I don't see why a build with nvidia stuff wouldn't come by default.

Also another feature I just thought, would it be possible to have a "Movie" tab in settings? Changing FFMPEG's install location (or custom location as i'm using a diff build) would be nice.

**Comment by akiver** [comment]
Since you can now change the audio/video codec from the app and use a custom FFmpeg build, I think this issue can be closed.
