### ISSUE TITLE
[Watch Player] Fast Forwarding between player death and beginning of new round

### ISSUE THREAD

**Issue by mariosemes** [akiver/CSGO-Demos-Manager#399]
Hey there,
First of all... You did an amazing job and I cant be more grateful than I already am :) <3

As a heavy user of your app, I was wondering how does the fast forwarding between the players death and the beginning of the new round works? 

I realized that sometimes its perfectly timed, sometimes its missing 10 seconds, sometimes its even more then 10 seconds and the fast forwarding ignores the match pauses. p.s. this is the comment regarding to "Watch player" :)

I am just mind blown of how this feature works and if it could be more precise, maybe :)?

Would love to buy you a beer somehow. Hope to have a great little chat with the mind behind this.

Kind regards

**Comment by biggskanz** [comment]
Hey Mario this feature is my tiny contribution to this app. I saw the watch player option but noticed it simply played the demo normally when selected so I took it upon myself to write it.

I basically studied the highlights and lowlights feature figure out how to do it. I did minimal testing except with my own demos so I’m sure it could be cleaned up a little. I’d be happy to look at the issues you brought up and see what we can do. I have been meaning to look back into it recently anyway. A few demos with noted round times when you see the issues would be helpful.

**Comment by mariosemes** [comment]
Hi @biggskanz , thanks for the reply. You are amazing!

Here is the latest example where watched player "ROPZ" on de_inferno
https://www.hltv.org/download/demo/52865

first few rounds its forwarding trough the actual round start, and then, sometimes again it ignores the freezetime and match pause :)

Please, let me know if I can help you guys out somehow!
Thank you very much.

**Comment by mariosemes** [comment]
You are amazing brother!
