### ISSUE TITLE
Ranks and bans dont show up anymore

### ISSUE THREAD

**Issue by TheMagicDick** [akiver/CSGO-Demos-Manager#400]
Im not to sure when it started but any ranks, profile pics, and bans dont show up on the home screen or when looking at a demo's details. But i can still see my rank when i go to stats and see my rank progression.

**Comment by zionlion77** [comment]
I am having the same problem. Also, I cannot see the players of my suspect list anymore. Any idea how to get this fixed?

**Comment by AllEyEsOnMe9977** [comment]
me too

**Comment by akiver** [comment]
Fixed in 2.13.10
