### ISSUE TITLE
Setpos

### ISSUE THREAD

**Issue by JoIjisok** [akiver/CSGO-Demos-Manager#406]
Hi , in stuffs when I copy the setpos of grenades positions, they goes wrong in game

**Comment by akiver** [comment]
Please provide a demo with information about the stuffs.  
Note: the setpos is the exact player's position/angle when the stuff has been thrown but if he was running or jumping it will not work.

**Comment by JoIjisok** [comment]
For example , https://www.hltv.org/matches/2337460/vitality-vs-100-thieves-iem-beijing-2019 , in inferno, round 10, shox smoke , if you put the setpos the smoke is more to the left then original , check that

**Comment by akiver** [comment]
I copy pasted the position from the app and did a jump throw and it lands perfectly https://www.youtube.com/watch?v=amfi6dAjHsU
