### ISSUE TITLE
Invalid SteamID 64 or Steam community URL

### ISSUE THREAD

**Issue by Effendi112** [akiver/CSGO-Demos-Manager#407]
Hi,

wh trying to add my account (public profile) to the Demos Manager I get the error "Invalid SteamID 64 or Steam community URL".
I've tried both my community URL as well as my SteamID 64.

The error log shows the following output:

Object reference not set to an instance of an object.
Type: System.NullReferenceException
StackTrace:
   at Manager.ViewModel.SettingsViewModel.<<get_AddAccountCommand>b__416_0>d.MoveNext()

**Comment by akiver** [comment]
Fixed in 2.13.10
