### ISSUE TITLE
ban not detect ,suspect list empty 

### ISSUE THREAD

**Issue by midnightcatzz** [akiver/CSGO-Demos-Manager#408]
i had install the latest demo manager but whenever i add user into suspect list, its always empty and it written that player is already in your suspect list. 

analyze demo doessnt detect any player that was banned.

**Comment by AllEyEsOnMe9977** [comment]
mine too

**Comment by Enghausen-petabit-gg** [comment]
Can confirm - I am using last build v2.13.9. The suspect list i empty, something is broken.

**Comment by ColderCoder** [comment]
the same problem

**Comment by akiver** [comment]
Fixed in 2.13.10
