### ISSUE TITLE
'Go to match(s)' option on right click in suspects list

### ISSUE THREAD

**Issue by RixzZ** [akiver/CSGO-Demos-Manager#41]
The addition of see what people are vac-banned on scoreboards was wonderful. Can we have an option to go to the match we played against a player on suspect list? Or a list if there was more than I match?

I use to order that list by DSLB so I would like to see when I played with/against that person.

**Comment by akiver** [comment]
You can display demos containing a suspect from your suspect list since the 2.2.0 release (by clicking on the button "Show suspect demos").
I added this on right click from suspect list and from the scoreboard too (even if the player isn't banned).
