### ISSUE TITLE
Several issuses ive found

### ISSUE THREAD

**Issue by Purple-CSGO** [akiver/CSGO-Demos-Manager#410]
1. latest version dont recognize steam url or steamid64
2. it does not support manually choosing hlae installation path. In some areas, downloading hlae in dm is painful.
3. updating hlae using dm causes hlae's ffmpeg to be cleared and need to be restalled manully(check hlae's new feature)

**Comment by akiver** [comment]
Fixed in 2.13.10
Please open 1 issue by feature/bug in the future 😄
