### ISSUE TITLE
Error while trying get player information

### ISSUE THREAD

**Issue by AllEyEsOnMe9977** [akiver/CSGO-Demos-Manager#412]
Hello i have problem with adding my account.I tried many accounts and none of them were able to be added.please help i need this app too much
![2019-11-15 06_29_48-](https://user-images.githubusercontent.com/57782244/68913710-873f6880-0771-11ea-9253-d2a37ed156eb.png)
![2019-11-15 06_29_48-](https://user-images.githubusercontent.com/57782244/68913724-92929400-0771-11ea-88f8-00b392b4fbcb.png)

**Comment by akiver** [comment]
Fixed in 2.13.10
