### ISSUE TITLE
Add heatmap_point player positions to the "player_hurted" events! Update 8/28

### ISSUE THREAD

**Issue by lilgandhi1199** [akiver/CSGO-Demos-Manager#414]
It seems like you have access to this information of where the players are standing when they kill each other but could you also please add the player positions to their Hurted events.
I looked under Weapons_Fired to try and line them up but I guess it would be too much data so you only display grenades in there.
For the trade-off of saving space and giving helpful data can you please add in this

"heatmap_point": {
              "killer_x": 1161.97571,
              "killer_y": 2717.06226,
              "victim_x": 337.320068,
              "victim_y": 1881.83777,
              "X": 0.0,
              "Y": 0.0
            },

to the "players_hurted": [
events in the json?

My only alternative is to code from scratch and I don't know! I just started doing map analysis for comparing my A Site hold vs B site hold vs B Retake vs A Retake and I only go based on kills but it would be 5x more accurate if I had every damage event too!

**Comment by lilgandhi1199** [comment]
I see you're working on upgrading to Version 3!
I've got it working from CSGO's released source code to dump every damage event with each player's positions but the demo file unpacks to 450mb with 12 million lines and for my code (which does work...) takes 2 and a half hours to come up with this simple log file.
[___match730_003366221182058627168_0031300372_128.txt](https://github.com/akiver/CSGO-Demos-Manager/files/5144303/___match730_003366221182058627168_0031300372_128.txt)

Then I just match it as I parse through your awesome JSON dump. *note that instead of X and Y it does use the pretty cool prebuilt "m_szLastPlaceName" for every map for example.... here is all the available ones for dust2. That would be an excellent addition...but please X and Y would be amazing! I don't want to run 3hrs per demo to get my data!

ARamp
BDoors
BombsiteA
BombsiteB
Catwalk
CTSpawn
ExtendedA
Hole
LongA
LongDoors
LowerTunnel
Middle
MidDoors
OutsideLong
OutsideTunnel
Pit
Ramp
Short
ShortStairs
Side
TopofMid
TRamp
TSpawn
TunnelStairs
UnderA
UpperTunnel

**Comment by lilgandhi1199** [comment]
@akiver Hope you take a look!
Thank You very very much if you do this.

**Comment by lilgandhi1199** [comment]
I see you are busy checking out your github's updates.
I have finally setup ubuntu which might be capable of parsing player locations out myself but then I would have to go write out a ton of code to interface between the 2 machines etc. If you would consider adding this small amount of code then I would be totally satisfied with my statistics calculation.

Thank you for your consideration and reading this far!
This app is awesome

**Comment by akiver** [comment]
Done with https://github.com/akiver/CSGO-Demos-Manager/commit/5eae8a7deed3429540fabee76f255da84d824263
