### ISSUE TITLE
HLAE 2.82.0 infected with Win32.Startun

### ISSUE THREAD

**Issue by cryptearth** [akiver/CSGO-Demos-Manager#415]
please be informed that current version 2.82.0 of HLAE is infected with malware: Win32.Startun

**Comment by dtugend** [comment]
https://github.com/advancedfx/advancedfx/issues/250

**Comment by Devostated** [comment]
Hello @cryptearth 
I can confirm that HLAE is not infected by any malware.
What you should do is to only download HLAE from our official Github page.
If you still feel uncomfortably feel free to read the whole code, since it's open source, and compile it yourself.
