### ISSUE TITLE
Question about highlights

### ISSUE THREAD

**Issue by lukezito1** [akiver/CSGO-Demos-Manager#423]
Is it possible to watch a highlight from a player that show only the rounds that said player killed 3 or more?
 Thank you.

**Comment by akiver** [comment]
No but you can use the "Player view" that lists all player's kills by round.  
![2020-03-15 14_25_44-](https://user-images.githubusercontent.com/1842524/76710967-f188fb00-66c8-11ea-8882-f6a6c7bcfdd5.png)
