### ISSUE TITLE
Errors in the suspect list

### ISSUE THREAD

**Issue by tintinmaster** [akiver/CSGO-Demos-Manager#424]
- The columns "status" and "account visibility" are swapped

- "Last connection" only shows the start of unix time: 1/1/1970 01:00:00 (1:00 am because of my timezone) 

I'm using version 2.13.11 on Windows 10
![image](https://user-images.githubusercontent.com/36089973/75635814-63693b00-5c19-11ea-9e54-b13f2130a15b.png)

**Comment by tintinmaster** [comment]
In the whitelist the "last connection" is also missing, but "status", "account visibility" and "profile setup" is empty

**Comment by tintinmaster** [comment]
I don't know much of your code, but maybe i got the problem of the "last connection"-problem
https://github.com/akiver/CSGO-Demos-Manager/blob/d526c2f43fa925e522a243dc7a5d3c48910dd077/Core/Models/Suspect.cs#L38 
Could this be the problem?

**Comment by akiver** [comment]
I had to remove the last connection column since the Steam API now return it only for friends https://steamcommunity.com/discussions/forum/1/1753525585395205696/#c1753525585396410038
