### ISSUE TITLE
analyze all demos error 

### ISSUE THREAD

**Issue by oscaryangam109** [akiver/CSGO-Demos-Manager#425]
when i analyze every demos. it is error

error
an error occured while analyzing demos:
match
this demo may be too old,if not please send an email with the attached demos

my demo download address:
CSGO-vFtMy-GTP3b-BSQDh-8cUb5-9AMsE

**Comment by akiver** [comment]
The issue is related to an incomplete download, the file was only 8MB instead of 61.
After deleting the demo and re-downloading it, it works.
Direct link if needed http://replay144.valve.net/730/003400380553759817849_0053941759.dem.bz2
