### ISSUE TITLE
Problem launching my highlights with enemys' pov

### ISSUE THREAD

**Issue by R3koVn1** [akiver/CSGO-Demos-Manager#428]
like the title said, for more detail it forced my 4:3 stretched into 4:3 windowed when i clicked on the enemy's pov button and i got my game loaded at the panorama ui screen. after that nothing else happened

**Comment by akiver** [comment]
> it forced my 4:3 stretched into 4:3 windowed

You can change video options from settings, by default it starts the game in window mode.

> my game loaded at the panorama ui screen. after that nothing else happened

Make sure there is no special characters in the demo file path, see https://www.csgo-demos-manager.com/docs/watch#stuck-menu
