### ISSUE TITLE
Is the program suppoed to crash when "watching" a demo?

### ISSUE THREAD

**Issue by Andrew3019** [akiver/CSGO-Demos-Manager#429]
The program crashes every time I load a demo by pressing "watch"... is this supposed to happen?

![image](https://user-images.githubusercontent.com/30658674/76681735-16319400-6631-11ea-9af1-1943414548e0.png)
![image](https://user-images.githubusercontent.com/30658674/76681740-29446400-6631-11ea-9bb2-11f6103b693d.png)

Error log:
https://pastebin.com/sfGQ7PTm

**Comment by 0BuRner** [comment]
Yes it's obviously a frequently requested feature !

**Comment by akiver** [comment]
I think it's because you are running Steam with admin rights.

**Comment by Andrew3019** [comment]
> I think it's because you are running Steam with admin rights.

how do I change that?

"Run this program as an administrator" is disabled, and I'm not getting the UAC prompt when launching steam. I do get the prompt when launching csgo though...

**Comment by Andrew3019** [comment]
I ran csgo demos manager as admin and that seemed to stop the crashes

**Comment by akiver** [comment]
Same as https://github.com/akiver/CSGO-Demos-Manager/issues/439 you should not run programs as admin
