### ISSUE TITLE
Can't open demo files

### ISSUE THREAD

**Issue by Benschi99** [akiver/CSGO-Demos-Manager#436]
I can't open demo files from the program, sometimes it didn't work when I tried to watch someones lowlights for example but now it doesn't work at all anymore. Opening from Replayfolder in CSGO folder works fine...

![Counter-strike  Global Offensive Screenshot 2020 03 31 - 11 25 00 52](https://user-images.githubusercontent.com/55798359/78010171-5b98d580-7342-11ea-8e66-52acced1efeb.png)

**Comment by 0BuRner** [comment]
Put you demo in another folder, you have a fucked up character in the folder name... -_-
