### ISSUE TITLE
Esportal demo can not be analyzed 

### ISSUE THREAD

**Issue by CaishenNefri** [akiver/CSGO-Demos-Manager#437]
Hello. Esportal nowadays is more popular. Can you take a look at demos from that platform? 

Link do demo:
https://mega.nz/file/iOwjFLqR#7nRYD2FGPlIUILNlwUEYy63e5Hp2cpLqEiZh-JzJ15U

**Comment by 0BuRner** [comment]
Why did you close your issue ?

**Comment by CaishenNefri** [comment]
Because I made mistake. 
Analyze Esportal demo works but issue shows when I change localization of demo but demo was analyzed
