### ISSUE TITLE
All export xls for all matches at once [enhancement]

### ISSUE THREAD

**Issue by evesira** [akiver/CSGO-Demos-Manager#44]
Currently, you can go into each match individually and export the match data to an Excel sheet. It would be a very nice feature to be able to do this for all demos at once, either as separate files per match or as one large combined file. This would allow you to analyze the raw data however you want with statistical applications or straight up programming.

One can't design a GUI that allows someone to extract any kind of data or correlations they could possibly want. Let's say I want to know how many games on Mirage I top fragged. Or bottom. Or middle. Or let's say I want to know how many games I top fragged when the other team had a smurf by some definition (e.g. really high KDR compared to the rest). Or let's say I want to know how much better/worse I do playing with a certain Steam friend.

The possibilities are endless if you have access to all the raw data!

**Comment by akiver** [comment]
I added the ability to export multiple demos into a single or multiple files yesterday 43ccd23a3052fcbfd32b48aff8fe32e5c01a5d29.
Here is an example (data are from DH winter 2015) https://drive.google.com/file/d/0B6WTk8ow9zh9ZUppZWpXWlhlb3M/view.
I will close this issue if it's ok.

**Comment by evesira** [comment]
Oh, hahah. Nice! Sure, close it.

*Vince Rubinetti*
