### ISSUE TITLE
Demo cannot load ingame.

### ISSUE THREAD

**Issue by N0O3** [akiver/CSGO-Demos-Manager#443]
A few days back everything worked, until now. When II try to record or watch it, CSGO gets launched, loads the demo and gets back to the main menu instantly.

Any fix?

**Comment by tek909** [comment]
having the same issue. my friends are not. 
select watch. it loads the client, it looks like its loading the demo, 
quite quickly it stops loading and returns me to csgo main menu

**Comment by akiver** [comment]
What's the output in the console?

**Comment by N0O3** [comment]
here you go

`Parent cvar in client.dll not allowed (weapon_max_before_cleanup)
Parent cvar in client.dll not allowed (weapon_auto_cleanup_time)
Parent cvar in client.dll not allowed (sv_bumpmine_detonate_delay)
Parent cvar in client.dll not allowed (sv_bumpmine_arm_delay)
Parent cvar in client.dll not allowed (sv_breachcharge_arm_delay)
Parent cvar in client.dll not allowed (sv_breachcharge_fuse_max)
Parent cvar in client.dll not allowed (sv_breachcharge_fuse_min)
Parent cvar in client.dll not allowed (sv_breachcharge_delay_max)
Parent cvar in client.dll not allowed (sv_breachcharge_delay_min)
Parent cvar in client.dll not allowed (sv_breachcharge_distance_max)
Parent cvar in client.dll not allowed (sv_breachcharge_distance_min)
Parent cvar in client.dll not allowed (cl_grenadepreview)
Parent cvar in client.dll not allowed (snd_max_pitch_shift_inaccuracy)
Parent cvar in client.dll not allowed (steam_controller_haptics)
Parent cvar in client.dll not allowed (mp_endmatch_votenextleveltime)
Parent cvar in client.dll not allowed (mp_verbose_changelevel_spew)
Parent cvar in client.dll not allowed (cl_remove_old_ugc_downloads)
maxplayers set to 64
V8 Version: 5.8.283
FcConfigAppFontAddDir d:\steamlibrary\steamapps\common\counter-strike global offensive\csgo\panorama\fonts\ took 15.550 ms.
CUiComponent_OptionsMenu::CUiComponent_OptionsMenu
Loading Game State Integration: gamestate_integration_logitech.cfg
Steam config directory: D:\SteamLibrary\steamapps\common\Counter-Strike Global Offensive\platform\config
ChangeGameUIState: CSGO_GAME_UI_STATE_INVALID -> CSGO_GAME_UI_STATE_MAINMENU
--- Missing Vgui material vgui/store/store_item_bg
--- Missing Vgui material vgui/store/store_item_bg_highlight
--- Missing Vgui material vgui/store/store_item_sel_bg
--- Missing Vgui material vgui/store/store_item_pickup_bg
--- Missing Vgui material vgui/store/store_preview_bg
--- Missing Vgui material vgui/store/store_bottom_bar_button_bg
--- Missing Vgui material vgui/store/store_bottom_bar_button_highlight_bg
--- Missing Vgui material vgui/store/store_default_dialog
--- Missing Vgui material vgui/store/store_backpack_bg
--- Missing Vgui material vgui/store/store_backpack_bg_highlight
--- Missing Vgui material vgui/store/store_backpack_bg_highlight
--- Missing Vgui material vgui/store/store_discount_corner
--- Missing Vgui material vgui/store/store_preview_bg
--- Missing Vgui material vgui/store/store_tooltip_bg
--- Missing Vgui material vgui/store/store_tab_selected
--- Missing Vgui material vgui/store/store_tab_unselected
--- Missing Vgui material vgui/btn_econ_blue
--- Missing Vgui material vgui/store/button_econ_blue_over
--- Missing Vgui material vgui/store/store_backpack_bg
--- Missing Vgui material vgui/store/store_backpack_bg_highlight
--- Missing Vgui material vgui/store/store_backpack_bg_highlight
Unknown command "cl_thirdperson"
Unknown command "tr_best_course_time"
Unknown command "tr_completed_training"
Unknown command "weapon_accuracy_logging"
Elapsed time:  0.00 seconds
**** Unable to localize '#DemoPlayback_Restart' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Back' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Pause' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Slow' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Play' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Fast' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Next' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#Panorama_CSGO_Spray_Cursor_Hint' on panel 'RosettaInfoText'
Unknown command "cl_teamid_min"
Unknown command "cl_teamid_max"
Unknown command "cl_teamid_overhead"
Can't use cheat cvar cl_teamid_overhead_maxdist in multiplayer, unless the server has sv_cheats set to 1.
Deferring playdemo command!
NET_CloseAllSockets
Got SDR network config.  Loaded revision 275 OK
Performing ping measurement
RelayNetWorkStatus:  avail=Attempting  config=OK  anyrelay=Attempting   (Performing ping measurement)
AuthStatus (steamid:76561198169097057):  OK  (OK)
Unknown command "cl_thirdperson"
Unknown command "tr_best_course_time"
Unknown command "tr_completed_training"
Unknown command "weapon_accuracy_logging"
Cluster 'atl' has a selection penalty of 5ms for load balancing purposes.  (As per atl#35 (162.254.199.178:27029)).
Cluster 'lax' has a selection penalty of 4ms for load balancing purposes.  (As per lax#33 (162.254.195.86:27027)).
CCSGO_BlurTarget - Unable to find panel with the given id "CSGOLoadingScreen"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "eom-winner"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "id-mainmenu-mission-card-bg"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "id-op-mainmenu-top"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "id-tournament-pass-status"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "CSGOLoadingScreen"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "CSGOLoadingScreen"! Panel is possibly created dynamically.
Elapsed time:  0.00 seconds
Telling Steam it is safe to update the app
Host_WriteConfiguration: Wrote cfg/config.cfg
Executing deferred playdemo: f:\@demo\raw\d556b5bd-be11-4146-a8ca-ac93d78bb6b7.dem
**** Unable to localize '#DemoPlayback_Restart' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Back' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Pause' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Slow' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Play' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Fast' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#DemoPlayback_Next' on panel descendant of 'HudDemoPlayback'
**** Unable to localize '#Panorama_CSGO_Spray_Cursor_Hint' on panel 'RosettaInfoText'
ChangeGameUIState: CSGO_GAME_UI_STATE_MAINMENU -> CSGO_GAME_UI_STATE_LOADINGSCREEN
PNG load error Interlace handling should be turned on when using png_read_image
PNG load error Interlace handling should be turned on when using png_read_image
CDemoFile::Open: couldn't open file f:\.dem for reading.
ChangeGameUIState: CSGO_GAME_UI_STATE_LOADINGSCREEN -> CSGO_GAME_UI_STATE_INGAME
CCSGO_BlurTarget - Unable to find panel with the given id "sliding-panel--TERRORIST"! Panel is possibly created dynamically.
CCSGO_BlurTarget - Unable to find panel with the given id "sliding-panel--CT"! Panel is possibly created dynamically.
ChangeGameUIState: CSGO_GAME_UI_STATE_INGAME -> CSGO_GAME_UI_STATE_MAINMENU
PNG load error Interlace handling should be turned on when using png_read_image
Failed to communicate with routing cluster 'gnrt'.
Failed to communicate with routing cluster 'scl'.
Failed to communicate with routing cluster 'waw'.
Failed to communicate with routing cluster 'lim'.
Ping measurement completed
Ping location: sgp=3+0/4+0,man=87+8/30+0,hkg=42+4/32+0,maa=55+5/35+0,canm=48+4,cant=186+18/48+4,canu=266+26/48+4,bom=54+5,tyo1=70+7,fra=169+16,iad=243+24/229+7,gru=346+34/364+7
RelayNetWorkStatus:  avail=OK  config=OK  anyrelay=OK   (OK)`

ps hopeful  that's what you want

**Comment by N0O3** [comment]
I think its something dodo with my demo being not in the same directory as the game

**Comment by akiver** [comment]
> `f:\@demo\raw\d556b5bd-be11-4146-a8ca-ac93d78bb6b7.dem`

> `CDemoFile::Open: couldn't open file f:\.dem for reading.`

The game can't open the demo because of the `@` in the path, it's a special char that the game doesn't support https://www.csgo-demos-manager.com/docs/watch#stuck-menu.
