### ISSUE TITLE
Heatmaps - sides/players filters should be and rather than or

### ISSUE THREAD

**Issue by decarlec** [akiver/CSGO-Demos-Manager#448]
In the Heatmap manager, the user should be able to filter by side and player so they could see for example where a certain player died on T side vs CT side.

**Comment by akiver** [comment]
I think you fixed it by yourself with https://github.com/akiver/CSGO-Demos-Manager/pull/449 😄 
Feel free to close the issue if that's the case.

**Comment by decarlec** [comment]
Yes - sorry haven't used github a lot, still getting used to it!
