### ISSUE TITLE
Heatmap selection improvements

### ISSUE THREAD

**Issue by Brekkjern** [akiver/CSGO-Demos-Manager#45]
I would like to be able to make more granular selections with the heatmap. Currently you can select only a single round or all of them, a side/both or a player and what type of event.

I'd like to create heatmaps of a specific player on a specific side (first/second half), or even a range of rounds (ecos/full buys/other).

It would also be nice to select several players instead of just one to see how a group of players working together died.

This last part isn't as important, but it would be interesting if once could get the program to identify trades and make heatmaps of where those happened. It would probably be inaccurate, but it could give some important insight for a demo.

**Comment by akiver** [comment]
You can now select any side / players / rounds.
