### ISSUE TITLE
[EASYONE] How to remove demo filtering in listing

### ISSUE THREAD

**Issue by mariosemes** [akiver/CSGO-Demos-Manager#454]
Yeah yeah, it's me again...

I was hoping for some assistance. As I am analyzing a lot of demos, a lot of times happens that I have the same demo for 2 or more players. The complicated backstory forces me to load the same demo sperately in CSGO Demos Manager. Currently, the manager shows only 1 demo if there are duplicates.
TLDR; I need to comment out the part of the code that filters the duplicated demos and shows only one in the main listing.

I have downloaded the source, made it into VS2017, and yes, with my badas* knowledge, I even succesfully build one release. Of course, only for my private purposes.

But this one, I just cant get it how it works :( (python coder here...)

Thank you very much for everything, regardless of the outcoming answer.

**Comment by akiver** [comment]
Hi,

I'm not sure to understand from your issue why you would like to keep duplicated demos from the list?
But yes I think an option to ignore duplicated demos would be useful.
It will allow us to delete or show in Windows Explorer a unique demo that has different locations.

The code part that removes duplicated demos from the list is here https://github.com/akiver/CSGO-Demos-Manager/blob/master/Services/Concrete/DemosService.cs#L142

**Comment by mariosemes** [comment]
Thank you very much!

As I commented out the line, there seems to be another problem with showing the demo name in the listing.

Example:
Demos in folder:
1. DemoName_1.dem
2. DemoName_2.dem
3. DemoName_3.dem
4. DemoName_4. dem

This demos are all the same 1 demo.

The listing in CSGODM is showing like this:
1. DemoName_1.dem
2. DemoName_1.dem
3. DemoName_1.dem
4. DemoName_1. dem

Probably because he used the header of the demo, and not the demo name :-/

**Comment by mariosemes** [comment]
I replaced the list name in the line: 144 with "demos.Add(demo)"
And commented everythin from line 150 to 188.

It works great for me now. Shows all demos and its real names.
