### ISSUE TITLE
Antivirus prevents v2.13.12 installation

### ISSUE THREAD

**Issue by MatiasFernandez** [akiver/CSGO-Demos-Manager#455]
Avira antivirus prevents installation due to identifying the installer as "FileRepMalware".

I'm not sure if this is a false positive or what, but I can't install the latest version

Thanks

**Comment by akiver** [comment]
Hi!

Yes it's a false positive, it may happen with some antivirus as reported in this issue https://github.com/akiver/CSGO-Demos-Manager/issues/358.

Avast is the only one reporting the last version as a malware https://www.virustotal.com/gui/file/73e11d6484c31560ff1e4eda4ffd85ed8d8f989ec362c72863aa47b9e924b16e/detection

You can whitelist the installer from Avast settings, see this doc for details https://support.avast.com/en-us/article/Antivirus-scan-exclusions

Thanks for the report, I will send the installer to the Avast whitelisting program.

**Comment by MatiasFernandez** [comment]
Thanks for the quick answer!
