### ISSUE TITLE
Loading demos - takes long time - keep stats for each replay so it can be deleted

### ISSUE THREAD

**Issue by lsv** [akiver/CSGO-Demos-Manager#46]
So, loading demos takes about 40 sec on my system, and I only have about 50 demos.
The reason why I keep them is so I can see my stats improve (or not :)) over time.

A suggestion, when a demo has been analyzed, could csgo-manager maybe keep the stats from the demo in a database? - Ofcourse the details for a replay will be lost, but keep the information only for the "Account stats" (CTRL + E) page would be nice.

**Comment by MRuy** [comment]
147 replays (7.86GB) takes 1min 22sec to load at start  
  
PLEASE optimize loading time and store stats without demo-file

**Comment by akiver** [comment]
I made some adjustements to decrease startup time.
I tested with 174 demos and it goes from 27s to 13s.
What's your CPU and RAM?

**Comment by MRuy** [comment]
CPU: i7 870 (2.93Ghz)  
Ram: 10GB (yes, 10GB)  
OS: Win 10  

~37sec until demos shown  
+ ~30sec until rank  
Total: 01min 7s  
  
My CPU goes up to constant 20% usage and ~38% Ram
