### ISSUE TITLE
Adding Dutch translation.

### ISSUE THREAD

**Issue by rpm192** [akiver/CSGO-Demos-Manager#461]
Hi,

I'd like to translate the application to Dutch for you, but the XLIFF files for that locale (nl) have not been created yet.

Could you add them so I can translate it for you?

Thanks.

**Comment by Mad-Kingu** [comment]
Hello,

I also can translate into Turkish if you point me the XLIFF file location. This would be a good contribution for all. 

Cheers

**Comment by akiver** [comment]
Hi, I added Dutch and Turkish files, please see this commit to find the files location https://github.com/akiver/CSGO-Demos-Manager/commit/d73b5d9a1032f9c2241deebe39aba99dd0430ee0.

Thank you
