### ISSUE TITLE
CSGO-Demos-Manage  Not available for download [Demo Support ]

### ISSUE THREAD

**Issue by wlsgud12290** [akiver/CSGO-Demos-Manager#464]
I am using Windows 10 Pro.
CSGO-Demos-Manager was used, but suddenly it was not executed.

![123](https://user-images.githubusercontent.com/67301281/85353951-5cf22c80-b544-11ea-9e76-983195e8466d.png)

**Comment by akiver** [comment]
It looks like the path to the app installation folder can't be found (maybe related to HDD / partition changes).
Try to uninstall the app manually and re-install it, please see [this issue](https://answers.microsoft.com/en-us/windows/forum/windows_10-windows_install/error-message-the-drive-or-unc-share-you-selected/ed8ab443-b645-44be-9634-e1a9b5d9e063) for details
