### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by learnNmaster** [akiver/CSGO-Demos-Manager#469]
Error pops up when CSGO-Demos-Mana
![image](https://user-images.githubusercontent.com/67230271/89700727-2a628e80-d94e-11ea-9c53-016ffac6ee87.png)
ger tries to launch csgo for demo viewing.
[errors.log](https://github.com/akiver/CSGO-Demos-Manager/files/5044531/errors.log)

**Comment by Insan3011** [comment]
Having the same issue please reply a fix

**Comment by bonbon12** [comment]
Check the permissions of the folder and files!

The folder containing all the demos for me was the culprit!
