### ISSUE TITLE
Change max concurrent parsing threads

### ISSUE THREAD

**Issue by Sandra-UwU-neko** [akiver/CSGO-Demos-Manager#470]
can i somehow increase the max concurrent parsing threads?
so it's parsing like 8 instead of 4 demos

**Comment by Sandra-UwU-neko** [comment]
Thanks ^^

Am Mo., 1. Feb. 2021 um 06:45 Uhr schrieb AkiVer <notifications@github.com>:

**Comment by Allesanddro** [comment]
Hey, is it possible to add this feature again? 

Greetings
