### ISSUE TITLE
Demo's don't show up and I can't open them manually.

### ISSUE THREAD

**Issue by yesriskk** [akiver/CSGO-Demos-Manager#471]
Hey,
I downloaded my recent matches from FACEIT and added them to the folder "C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\csgo" but they don't show up in the manager.
I ticked the box "show all" and nothing happend.
When I try to start them manually I get this error "An unexpected error occured. Please send the 'errors.log' file accessible from settings. Message Error: Object reference not set to an instance of an object."

Please help.

**Comment by lilgandhi1199** [comment]
They should end in ".dem" and try the replays subfolder (without changing the csgo folder assignment)

**Comment by akiver** [comment]
FaceIt demos are zip archives, you have to unzip it to get the .dem file.
Also, make sure the current folder from the demos list is correct.
