### ISSUE TITLE
unable to download ffmpeg

### ISSUE THREAD

**Issue by Xhirox88** [akiver/CSGO-Demos-Manager#472]
When i tried to download ffmpeg via movies tab, it says ffmpeg has not been installed, this is the error from error file

10/2/2020 11:54 PM: The remote name could not be resolved: 'ffmpeg.zeranoe.com'
Type: System.Net.WebException
StackTrace:
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at Services.Concrete.Movie.FFmpegService.<>c__DisplayClass11_0.<Download>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Services.Concrete.Movie.FFmpegService.<Download>d__11.MoveNext()

**Comment by letuwang** [comment]
ffmpeg.zeranoe.com closed on Sep 18, 2020 and all builds are removed.

**Comment by sheharyaar** [comment]
I found a workaround for this problem. As the link hardcoded exists no more, download ffmpeg to any drive and then copy the folder to **"C:\Users\{user}\AppData\Local\AkiVer\hlae\"** user refers to the current username.

**Note: The folder should be lowercase ffmpeg**

**Comment by akiver** [comment]
Hi! Sorry for the delay, it will be fixed in the next version.

**Comment by brenodiogo** [comment]
Sorry to reopen this but I'm still having this bug as of today (version 2.13.15)

@sheharyaar fix worked for me though

**Comment by Stani1k** [comment]
@sheharyaar I followed your workaround but unfortunately it doesn't work for me.. I installed **ffmpeg** by the help of this [video](https://www.youtube.com/watch?v=r1AtmY-RMyQ&ab_channel=TroubleChute) and after running it from the cmd it looks like I installed it right. 

But in the Demo Manager application the FFmpeg section still only shows "Install". I tried restarting the App but that doesn't help. Are there any other steps I missed?

**Comment by sheharyaar** [comment]
@Stani1k Can u check these steps for me -
1) Version of CSGO Demo Manager you are currently having
2) Check if ffmpeg is added to your path by opening cmd and entering ffmpeg. 
3) Have you place the ffmpeg folder in the "C:\Users\{user}\AppData\Local\AkiVer\hlae" folder and if the name of folder is in lower case

**Comment by Stani1k** [comment]
Hello @sheharyaar,

1. My Version is **2.13.15**, same as @brenodiogo , where your workout worked for him.
2. Yes I placed it in that folder and the name is in lowercase.

Here is a screenshot of the folder path and the content:
![ffmpeg_folder](https://user-images.githubusercontent.com/71967305/115139813-5f25fa00-a034-11eb-8546-c481bc5a9655.png)

Any ideas what might be wrong?

**Comment by sheharyaar** [comment]
@Stani1k I think there is some issue since you have compiled the binaries. Generally the ffmpeg executables are stored in ffmpeg/bin/ which is not there in your case. So either you can create a folder named bin and put the 3 exes in that, or download a complete version from : https://www.gyan.dev/ffmpeg/builds/ffmpeg-git-full.7z 

Please check and reply

**Comment by Stani1k** [comment]
That was exactly my issue.
I created a new bin folder and moved the .exe files inside and now it looks the same as in your screenshot.
Thanks for the help.

**Comment by Stani1k** [comment]
@sheharyaar Unfortunately I have now a different issue with ffmpeg. 
After genereting the video and starting it with the default windows player it only shows a black screen.
Do you know about this issue?

**Comment by sheharyaar** [comment]
@Stani1k The latest issue which you describe may be present in the issues list. Else you can produce it again, and attach few screenshots and open a new issue tracker. I will try to look into it as I do not know much about the codes of the program. 
Glad my workaround worked for you 👍🏻

**Comment by Stani1k** [comment]
@sheharyaar good idea, I had a look at the issues list but didn't find something similiar.
I will create a new issue and describe the problem, like you mentioned :)

@akiver Can you tell us when the fix will go live so we don't need this workaround.
