### ISSUE TITLE
(QUESTION) HLAE POV DEMO

### ISSUE THREAD

**Issue by xgoose420** [akiver/CSGO-Demos-Manager#477]
Hi im new to this software but how can I watch the demo/record demo but with "mirv pov 6" enabled? like I can watch/record the demo but in a POV mode of the player Im watching, not in regular demo watch..
thanks.

**Comment by akiver** [comment]
`mirv_pov` needs the player's index which is available only after playing the demo https://github.com/advancedfx/advancedfx/wiki/Source%3Amirv_pov.

It should work if you have the player's index, add `mirv_pov playerIndex` in the CFG text area, and set "Focus on player" to the desired player.

**Comment by Khamroz** [comment]
hi i cant find my index among others
