### ISSUE TITLE
Help creating videos

### ISSUE THREAD

**Issue by RafTGM** [akiver/CSGO-Demos-Manager#478]
First, sorry if it's been answered, but I've been trying to make it work for the last 2 days and I'm stuck, still I can't generate movies from my demos (Arms Race, recorded locally with the console record command).

Here's what's happening: I try to create a movie, CSGODM opens a windowed instance of CSGO, plays the demo and create .tga and sound files in 
C:\Program Files (x86)\Steam\steamapps\common\Counter-Strike Global Offensive\untitled_rec

Then as far as I've read, CSGODM supposedly would automatically close CSGO and open VDUB or ffmpeg to create the final movie, but all that happens is the demo finishing (and CSGO instance kept open in the main screen) and CSGODM spinning wheel (with a message "CSGO in-game recording in progress, please wait..."). I've waited for a really long time (the computer seems to be idle, no significant CPU usage), then closed CSGO. The spinning wheel from CSGODM stops and... nothing. I'm left with a 200GB folder (trying to record the full demo, but it's the same if I try just a small part).

HLAE version 2.109.2 and VirtualDub 1.10.4 are installed (through the install button on CSGODM). I copied ffmpeg (BtbN release) to HLAE ffmpeg folder (CSGODM doesn't show ffmpeg's version, but since I copied the ffmpeg's files to HLAE ffmpeg's folder, it allowed me to change configurations in the ffmpeg section).

What I've tried:
Checked if CSGODM and dependencies are all installed
Run CSGODM as administrator
Run the ffmpeg command line from CSGODM (but I don't know how it handles all the .tga and sound files, tried to run from several folders, including in the .tga folder)
Couldn't find the VDub script, was going to run it.

Thanks!

**Comment by akiver** [comment]
Does it happen only with local demos?
Could you send a demo with the steps to reproduce the issue (mainly the configuration used)?

I think it's because the app can't find tga files and does nothing but I'm not sure.
