### ISSUE TITLE
[Question] How to use nSkinz or other programs which needs dll injection? 

### ISSUE THREAD

**Issue by rajansaumya** [akiver/CSGO-Demos-Manager#479]
I tried adding this "mirv_loadlibrary "D:\CSGO\nSkinz\nSkinz.dll"" to the cfg and then load skins but demo is just playing from starting tick.

**Comment by akiver** [comment]
I tested without problems, make sure to not wrap the command with double-quotes in the CFG text area, i.e.

`mirv_loadlibrary "D:\CSGO\nSkinz\nSkinz.dll"`
not
`"mirv_loadlibrary "D:\CSGO\nSkinz\nSkinz.dll""`
