### ISSUE TITLE
Wrong demo status

### ISSUE THREAD

**Issue by GreenBandana** [akiver/CSGO-Demos-Manager#48]
Somehow it messes up the status of some demos. Some demos are shown as "win", although they are not, and with others it shows "lose" although it's a win.
In the details tab it shows the players in the wrong teams or shows the same team name for both teams.

With the second latest version I could fix this by changing the source to "ebot", but now this doesn't fix the problem anymore with the latest version.

**Comment by joshuajolly** [comment]
I think they are all switched (the loser shows as winner), at least the demos I've looked at.

**Comment by GreenBandana** [comment]
Yes according to the developer it's a known bug. He said he will fix it in the next version.
