### ISSUE TITLE
Popflash stats not correct

### ISSUE THREAD

**Issue by Nakkivaan** [akiver/CSGO-Demos-Manager#480]
Create application, not sure if admins are still around.

We use Popflash in our games. Popflash demos have always some stats missing when opened with CSGO Demos Manager. Same problem exists in application and Excels. Is this known issue? Is problem in Popflash demos or application?

Difference in the end results is always 0-2 two points, but looks like this comes from missing one or two round's stats.

**Comment by switz** [comment]
Tagging myself here if you find anything. I'm the creator of PopFlash. Happy to fix any issues you find, but I'm not currently aware of any.

**Comment by Nakkivaan** [comment]
Hi and sorry for late reply.

I can send game ids on PM, if you want to check. I have loaded other demos and stats have looked fine with demo manager.

-N

**Comment by akiver** [comment]
Hi, could you send an affected demo with details about what stats are wrong?
