### ISSUE TITLE
Engine Error when trying to record a movie

### ISSUE THREAD

**Issue by IncPlusPlus** [akiver/CSGO-Demos-Manager#483]
![image](https://user-images.githubusercontent.com/6992149/99604075-aef38d00-29d2-11eb-926b-86a2cfd78f19.png)

Hi! I've used CS:GO Demos Manager for a long time to manage my demos and I appreciate how much work has gone into it. Kudos! When trying to use the movie making feature, I ran into an issue that I can't figure out. After clicking the "generate" button, CS:GO launches but before it can even get to the main menu, I'm presented with the error shown in the screenshot above.

Launching CS:GO normally works just fine. Launching CS:GO through the same install of HLAE that this program uses (stored in C:\Users\Ryan Cloherty\AppData\Local\AkiVer\hlae) works fine too. It's only when launched via the movie making area that this crash occurs.

An interesting detail that might help determine the cause and solution to this issue:
The crash does not occur when I have the resolution in the demos manager set to 1280 by 720
The crash _does_ happen when the resolution is set to 1920 by 1080 (like the settings below)
![image](https://user-images.githubusercontent.com/6992149/99604679-0b0ae100-29d4-11eb-9ba1-76444fe40b3e.png)
My monitor is a 1080p monitor and the game opens in windowed mode when CS:GO Demos Manager attempts to start recording the video. I'm wondering if the crash would happen if the game launched fullscreen.

This error has been encountered before in https://github.com/advancedfx/advancedfx/issues/211 and https://github.com/advancedfx/advancedfx/issues/374 but I haven't found any real solutions on my own.

**Comment by akiver** [comment]
Hi, it looks like a CSGO or maybe HLAE issue.
Make sure HLAE is up-to-date, I can't reproduce the issue (tried in windowed/fullscreen and several resolutions).

The next version will have an option to run CSGO in fullscreen when generating videos, you may try it to see if it's related.

**Comment by IncPlusPlus** [comment]
Thanks! I appreciate the fullscreen option.

It's been a little while since I've used CS:GO Demos Manager to do some recording so I'll try again soon. I'll make sure CS:GO, the demo manager, and the HLAE installation it manages are all up to date and I'll try to replicate this issue again when I get the chance.

**Comment by akiver** [comment]
Version 2.13.13 is available with the full-screen option.
Let me know if the issue still occurs.
