### ISSUE TITLE
CS:GO says Tie, Manager says Win

### ISSUE THREAD

**Issue by elieux** [akiver/CSGO-Demos-Manager#484]
![image](https://user-images.githubusercontent.com/1399406/99835635-2c4f0700-2b65-11eb-9cdd-74b2b3a34d6f.png)
![image](https://user-images.githubusercontent.com/1399406/99835732-4c7ec600-2b65-11eb-9bbe-6ed2f8826f04.png)
![image](https://user-images.githubusercontent.com/1399406/99835744-50aae380-2b65-11eb-8956-121ac823c2a2.png)

Looks like round 16 is missed somehow.

~~[.dem](https://www.elieux.net/match730_003448616599169270397_0364721863_136.dem), [.dem.info](https://www.elieux.net/match730_003448616599169270397_0364721863_136.dem.info)~~

[.dem](https://www.elieux.net/match730_003448394811353071667_1113218962_136.dem), [.dem.info](https://www.elieux.net/match730_003448394811353071667_1113218962_136.dem.info)

**Comment by IncPlusPlus** [comment]
Does this persist if you try to analyze the demo again?

**Comment by elieux** [comment]
Good point. Yes, same result after multiple analyses.

**Comment by akiver** [comment]
Are you sure the linked demo is correct?
The demo is a game on vertigo and the score is 16-7 which is ok

**Comment by elieux** [comment]
Ah, not sure how that happened, sorry. The correct files are these: [.dem](https://www.elieux.net/match730_003448394811353071667_1113218962_136.dem), [.dem.info](https://www.elieux.net/match730_003448394811353071667_1113218962_136.dem.info)
