### ISSUE TITLE
Correctly analyses first 20 rounds of a 10-10 tie, then shows only 21st round

### ISSUE THREAD

**Issue by armisael** [akiver/CSGO-Demos-Manager#485]
Basically what it says in the title: I have a demo of a game played on a private server, on a workshop map. I don't know if something weird happened at the end of that game, I don't think so, but the following happened: the game ended with a 10-10 tie; when I analyse the demo with Demo Manager (latest available version, 2.13.12) I can see all the rounds correctly popping up; then the 20 rounds disappear, and only a 21st round is shown.

Also, the behaviour is consistent among multiple analysis re-run.

Is this a known bug? I tried having a look around the issues currently open here on github, but I could not find something similar to this.

Demo is [available for download here](https://www.dropbox.com/s/kmw0405icnq413c/auto0-20201203-223610-65176381-workshop_2242472711_de_calavera-Lonati_30_CS_GO.dem?dl=0).

Thank you for your time!

**Comment by akiver** [comment]
Demos from private servers are not officially supported, it *may* work.
This demo could work as it looks like it's using the Valve recording system but the main issue is that the game is a 3V3, MR 10 which is unusual and unsupported.

**Comment by armisael** [comment]
Yeah I noticed this kind of demo are not 100% supported, but for what we need so far Demos Manager does a decent job.

After I opened this issue I investigated it myself: apparently a "game restart" was triggered after the game ended; Demos Manager then resets almost all the stats, but not the round count: that's why we got a 21st round, and no data about the game.

It would be nice to have an option to select what to do in case of a "game restart", but I understand this is a corner case, and nobody will really need this feature in the future, so you can close this issue if you feel about it.

**Comment by akiver** [comment]
Analyzing Valve demos will now stop when the win panel is displayed, it will not make your demo 100% compatible though

**Comment by armisael** [comment]
Thank you! Keep up the good work! Looking forward v3!
