### ISSUE TITLE
Struggling to install demo manager

### ISSUE THREAD

**Issue by tezmond** [akiver/CSGO-Demos-Manager#490]
not sure if its just me not understanding what to do, but when I try to open the exe it says windows cannot access the specified device, path or file. you may not have the appropriate permissions to access the item.

I've tried a number of things still cant seem to get it to work

its there a guide to help install or am I just being really stupid today :D

**Comment by akiver** [comment]
It's a local issue, this doc should help you to solve it https://support.microsoft.com/en-us/topic/-windows-cannot-access-the-specified-device-path-or-file-error-when-you-try-to-install-update-or-start-a-program-or-file-46361133-47ed-6967-c13e-e75d3cc29657
