### ISSUE TITLE
Can't analyze demo from Snow Sweet Snow 1 Regionals

### ISSUE THREAD

**Issue by CaishenNefri** [akiver/CSGO-Demos-Manager#491]
It is not possible to analyze demo from Snow Sweet Snow 1 Regionals
Here is a link: https://www.hltv.org/matches/2346098/pompa-vs-honoris-snow-sweet-snow-1-regionals

![image](https://user-images.githubusercontent.com/24476768/105093227-af77d500-5aa2-11eb-8004-4ed1962c7cce.png)
Version: 2.13.12

**Comment by akiver** [comment]
Demos are recorded with eBot, change the demo's source to eBot and analyze it, it will work.
