### ISSUE TITLE
Watch highlights/lowlights doesn't work; Only goes to warmup then nothing happens

### ISSUE THREAD

**Issue by Frezcooo** [akiver/CSGO-Demos-Manager#492]
I've had this issue for months now, which is why I stopped using cs go demos manager. Whenever I right click and click watch highlights/lowlights on my faceit demos, it just goes into the match warmup and then the demo just continues normally. I just want to watch my highlights/lowlights :(

**Comment by arpitacharya23** [comment]
I have had the same issue, searching for a solution brought me here, still no success

**Comment by Frezcooo** [comment]
I deleted my Akiver folder in my user/Appdata/Roaming folder and now it's working again!!

**Comment by arpitacharya23** [comment]
Doesn't work for me mate

Regards
Arpit Acharya

**Comment by we1l** [comment]
Having the same issue here too. Wonder what could be the cause...

**Comment by we1l** [comment]
> Having the same issue here too. Wonder what could be the cause...

Watch --> Use custom highlits / lowlights generation

Turning above option off solved my issue. This was on by default for my installation.

**Comment by akiver** [comment]
I tried to reproduce the issue without success.
Could you send an affected demo with steps to reproduce it? (selected player, POV selection, from where you start the playback in the app...)

**Comment by we1l** [comment]
BTW, after I figured out how to make Player POV work for watching highlights, I have since found the Enemy POV rarely work (although it did work like twice out of 18 tries). I haven't figured out the patterns or deciding factors yet.

**Comment by wallds** [comment]
[https://github.com/akiver/CSGO-Demos-Manager/blob/8e6f415ba73cc511942e569914bcde58656e97cd/Services/Concrete/GameLauncher.cs#L110](url)

**Comment by arpitacharya23** [comment]
Not able to open the url

Regards
Arpit Acharya

**Comment by wallds** [comment]
https://github.com/akiver/CSGO-Demos-Manager/blob/8e6f415ba73cc511942e569914bcde58656e97cd/Services/Concrete/GameLauncher.cs#L110-L123

When the network is bad, steam can't create csgo process in 3 seconds, this code will think csgo process has quit and delete vdm file. ------- (translate)

![asdf](https://user-images.githubusercontent.com/12907032/106754716-467a8a80-6668-11eb-9f70-5737f5626ee5.gif)
(disable NIC)

**Comment by akiver** [comment]
Thanks @wallds ! 
It's surely the problem since it seems to be random and if the VDM file doesn't exist it will start at the beginning of the demo.
I published the version 2.13.15 that contains a fix, let me know if it's fixed.

**Comment by FlyMeToTheMars** [comment]
It seems the problem still exists.

**Comment by akiver** [comment]
The next version will not rely on Steam to start CSGO and delete the VDM file when the game process exited (see https://github.com/akiver/CSGO-Demos-Manager/commit/5b592a3627432cd008d7e931ac47ed4c36d7521c), it should fix the issue.
Please open a new issue if you still have the issue.

Thank you for the details!
