### ISSUE TITLE
Can't add custom folder 

### ISSUE THREAD

**Issue by Gkjad** [akiver/CSGO-Demos-Manager#493]
Hello I just downloaded this program twice with no progress
When I start the program it will say that i dont have CSGO on my main HDD and I want to add the custom folder trough setting but the program just freezes for a sec after i hit OK and I just can't add the custom folder bqs it will close

**Comment by akiver** [comment]
Do you have a logs file here `C:\Users\USERNAME\AppData\Local\AkiVer\errors.log`?
It may contain details.
