### ISSUE TITLE
Overwatch demo?

### ISSUE THREAD

**Issue by Ativ3k** [akiver/CSGO-Demos-Manager#494]
Is any way to add auto download overwatch demo and mark it on blue color or shield logo which would mean this is an overwatch demo?

**Comment by lilgandhi1199** [comment]
The only way right now to download your overwatch demos is to have an internet tracker running while you download it then in the logs somewhere it gives you what you need to recreate the download link.
YouTube it.

**Comment by Ativ3k** [comment]
Yeah, i know.
Overwatch bot does it.
But is there any option to add this "function" to CSGO Demo Manager?

**Comment by akiver** [comment]
Nop, no plan to intercept any http requests.
