### ISSUE TITLE
I just donated! Please consider this enhancement in your v3

### ISSUE THREAD

**Issue by lilgandhi1199** [akiver/CSGO-Demos-Manager#495]
https://github.com/akiver/CSGO-Demos-Manager/issues/414
It is just to fill in the heatmap player positions on your export json for all damage events (not just killed)

This is my steamID which shows (in the screenshots) all that I do with this amazing program.
https://steamcommunity.com/profiles/76561197997327350

I promoted your app in a steam guide and it trended top 3 in the steam overlay on 9/24/19 for a night until the steam bots mass disliked it.
https://steamcommunity.com/sharedfiles/filedetails/?id=1865414061

About 2 months later in November of 2019 after they saw all my stats boards with my specialized MVPs .... MVPs were released to the end game board lol

Even though I got no credit I would apreciate if you could throw me a bone and help me simply improve the positional stats of which I feed to players I meet a 2nd time ingame

I give them their 1v1 1v2 and A site / Mid / and B site control on T and CT side.
Using only kills to calculate this is OKAY but I won't stop until I have every damage event.

Please help me in this small regard (attaching player heatmaps to all player_hurted events in export) I have over 1200 games now with 8900 unique steamIDs of other players data and my own data of course that has only normalized to 1:1 trades but if I look at damage I bet it will reveal where to improve.

~
Mike Arnold
littlegandhi1199@gmail.com

**Comment by akiver** [comment]
😄 I added players position in player's hurt events and now the JSON export contains weapon fired / player blind events.

The V3 will use a CLI (separated project) that allow exporting all data into CSV or JSON files, I think it will avoid this kind of issue.

**Comment by lilgandhi1199** [comment]
Wohoo!
Love you bro.
Thank You
