### ISSUE TITLE
Include HLTV Rating 2.0?

### ISSUE THREAD

**Issue by TheReaperr** [akiver/CSGO-Demos-Manager#498]
I saw there was an old issue back in 2017 about HLTV2.0 being added and it was closed because you (rightfully) didn't want to reverse engineer the formula.
However it got reverse engineered recently: https://flashed.gg/posts/reverse-engineering-hltv-rating/

Any chance of it being added now the formula is known?

**Comment by akiver** [comment]
The HLTV rating 2 will be in the next version
