### ISSUE TITLE
Official matchmaking demo not displaying any ranks

### ISSUE THREAD

**Issue by guihkx** [akiver/CSGO-Demos-Manager#510]
How it shows up on CSGO Demos Manager 2.13.15:

![image](https://user-images.githubusercontent.com/626206/109256678-4425cf00-77d5-11eb-8c0a-705d798334fc.png)

And here are the actual ranks (shown after watching demo):

![IMG_20210226_014909108](https://user-images.githubusercontent.com/626206/109257229-74ba3880-77d6-11eb-9bba-e49d617d24e5.jpg)

Sharing code: steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-Zydf9-NufFk-joXay-jykTQ-WmPhG

Backup: https://mega.nz/file/mdMGCJTS#KqX2JazaUh88KlrMZqoX1ktfuU4G4V61iD49kYdWQ94

**Comment by akiver** [comment]
The message that reveals players' rank is missing for this demo, that's why ranks are not correct.
Unfortunately it's a CSGO bug, we can't do anything to fix it.

Note: I tried with several demos parser and the message is always missing.

**Comment by guihkx** [comment]
No problem! Glad to see some activity on the project again! glhf
