### ISSUE TITLE
Bug: demo analyzed as 25-5 when score was 16-14

### ISSUE THREAD

**Issue by dsf3449** [akiver/CSGO-Demos-Manager#512]
![image](https://user-images.githubusercontent.com/25350725/111059673-04114e00-845d-11eb-8e87-5ea4ba479c03.png)

The actual score of this match was 16 for Team 1 and 14 for Team 2.

[Demo download](https://drive.google.com/file/d/1ss9G9fTGFa8h_0cO53GXyvImTJ_7KLUJ/view?usp=sharing)

**Comment by sheharyaar** [comment]
@dsf3449 It seems the program reverses the second-half round wins. I wish somebody with knowledge of this program could help
