### ISSUE TITLE
ERROR WHEN ANALYZING A DEMO

### ISSUE THREAD

**Issue by Xiguinilster** [akiver/CSGO-Demos-Manager#514]
When analyzing the demo with the objective of extrarer the statistics to keep track of my equipment, this error occurred.
It usually happens with some demos I would like to know how to solve it or if you could help me thank you very much
@akiver 
![error](https://user-images.githubusercontent.com/67611329/112112554-70462d00-8b94-11eb-9990-3750534772e5.PNG)

.DEM
https://drive.google.com/file/d/1RUcU7-KlCWlRP49ZH6fuI2AEBFbRxTCd/view?usp=sharing

**Comment by Pheil** [comment]
I got the same error on one of mine.  Share code:  CSGO-kcKcz-PHuKc-jWa6X-V5zwy-CCLwF

**Comment by lilgandhi1199** [comment]
@Pheil analyzed fine for me. Sometimes it fails first try and you have to right click "Delete from cache" then re-run it.
And it works. Only time I come across complete failure analyses is like 1/100.

In the case of OP he's talking about 3rd party demos which are a pain for the coder to detect game start from warmup ETC when it's not standardized like every OFFICIAL game
