### ISSUE TITLE
Generated video file with FFmpeg format is not playable

### ISSUE THREAD

**Issue by Stani1k** [akiver/CSGO-Demos-Manager#519]
I used a workaround from here #472 to install and use FFmpeg in my application.
After my video was generated I couldn't play it. It shows only a black screen and nothing happens. I tried running it with different video players (e.x. Windows Media Player) but none of them worked.

The mentioned section looks like this:
![FFmpeg_section](https://user-images.githubusercontent.com/71967305/115270650-d34bc500-a13c-11eb-959f-cb91c8a3ba35.png)
and here my cfg:
```
// CFG example with some useful commands
cl_draw_only_deathnotices 1
cl_clock_correction 0
mirv_fix playerAnimState 1
mirv_streams record matPostprocessEnable 1
mirv_streams record matDynamicTonemapping 1
mirv_streams record matMotionBlurEnabled 0
mirv_streams record matForceTonemapScale 0
net_graph 0

mp_display_kill_assists  "0"
mirv_replace_name debug 1
mirv_replace_name 105 "Name1"
mirv_replace_name 107 "Name2"
```

If you need more data or informations let me know.

**Comment by 1stator** [comment]
I had the same issue - I just right clicked the file and opened with VLC and it worked perfectly ok :D

**Comment by OhGodANoob** [comment]
I regularly use Demo Manager to recreate clips and make highlights. Whenever I generate the file, it will show up as black, but if I open with VLC it will play fine. What I usually end up doing is running it through Handbrake and encode it with a bit different settings to compress the file size down and stuff. I think it might have to do with one of the codecs potentially. @akiver if I put a flag in where there is a space for extra parameters for FFmpeg will it override what the default is in the Command-line input?

**Comment by akiver** [comment]
Use a better video player than Windows Media Player, it doesn't include required codecs.
It's also recommended by HLAE when using FFmpeg (FAQ section) https://github.com/advancedfx/advancedfx/wiki/HLAE-FFmpeg-recording-with-preset-config#faq
