### ISSUE TITLE
Add steamid to be excluded from showing banned in the demo list,.

### ISSUE THREAD

**Issue by mpguidry** [akiver/CSGO-Demos-Manager#52]
I currently have a vacban and every demo shows red with ban. Can you possibly have an exclude list to not show as a banned player in demo. makes it hard to find other banned players

**Comment by akiver** [comment]
You can do it by adding your account to the whitelist (you can do it from the scoreboard).
Your SteamID will be ignored for the next analyze.
You have to re-analyze your demos to hide the red line.

**Comment by mpguidry** [comment]
i didnt know. thanks for the info
