### ISSUE TITLE
Sequence contains no matching element in demo kills view

### ISSUE THREAD

**Issue by vancushen** [akiver/CSGO-Demos-Manager#520]
I was trying to check a demo from my private server and when i tried to check the kills tab, i receive the message:
![Capture](https://user-images.githubusercontent.com/82924479/115495483-1a6daf00-a23e-11eb-825a-329beb845a73.PNG)

As this is a private server, i change the configuration and max players for the competitive mode is more than 10, and when checking the amount of players in the game, i see that there was only 5 in each time.

Is it possible that due to the fact that it's taking the game as competitive, it may not recognize that there are more players and that's why the error message pop ups? Sorry if it's not correctly explained, i can provide error.log data as well.

**Comment by akiver** [comment]
Could you please send an affected demo?
