### ISSUE TITLE
boiler.exe hang and caused steam to detect csgo as running

### ISSUE THREAD

**Issue by clutch9** [akiver/CSGO-Demos-Manager#521]
first off. i never turn off my computer. I had a problem for a few days that every time I exited CSGO, Steam still detected CSGO as running. I was then unable to start CSGO as Steam thought CSGO was running. then quit and restart Steam and then I was able to run CSGO before it again hanged like before. After some research it finally was resolved when I killed boiler.exe process which was somehow causing the issue. Not sure how it happened. So this was just a report of that :)  thanks for a great tool.

**Comment by lilgandhi1199** [comment]
You should check your demos. I've found 2 corrupted demos in the past day which have this effect.
