### ISSUE TITLE
Ratings 2.0 Solution

### ISSUE THREAD

**Issue by Epzilepzi** [akiver/CSGO-Demos-Manager#522]
Hi there, I saw issue #225 regarding HLTV Ratings 2.0, and you mentioned that you weren't willing to reverse engineer the ratings 2.0 algorithm. I recently stumbled across this post https://flashed.gg/posts/reverse-engineering-hltv-rating/ where the author of the article seems to have found a close algorithm to what HLTV uses to calculate their ratings. Perhaps this could be implemented?

**Comment by 3vaLpwner** [comment]
You are correct. But HLTV reads these rankings separately for T and CT side, which is difficult for now with current type of parsing in CSGODM. That should be awesome to see separate lists "Players_1stHalf" and "Players_2ndHalf". It will be possible to calculate Rating 2.0 then.

**Comment by akiver** [comment]
The estimated HLTV rating 2.0 will be in the next version
