### ISSUE TITLE
Demo list refresh is not working

### ISSUE THREAD

**Issue by Denzqree** [akiver/CSGO-Demos-Manager#527]
Windows 10, new October update.

Refreshing the list doesn't really work, because it doesn't delete the cache but you can do it right-clicking the demo and clearing the cache. 

Another solution is to restart the program

Appreciated

**Comment by akiver** [comment]
The purpose of the "cache" is not to have to re-analyze demos every time you open the application.
When you click on "Refresh", the app reads all .dem files and if they are in the "cache" it fetches data from it otherwise you would have only data from the .dem file's header.
