### ISSUE TITLE
I want to know how to parse the official match share link to get the direct link to the demo file

### ISSUE THREAD

**Issue by GamerNoTitle** [akiver/CSGO-Demos-Manager#532]
I'm currently working on a tool that helps users to download their official competitive match demo automatically. After I working on it, I want to add a feature to download the demo by using the match share link, but I don't know how to parse it to get the link to the file. People around me have recommended me to checkout CSGO-Demos-Manager and try to ask about this. So can someone tell me how to make it?

**Comment by lilgandhi1199** [comment]
It's all built off of his code here I believe.
https://github.com/akiver/boiler-writter

**Comment by GamerNoTitle** [comment]
> It's all built off of his code here I believe.
> https://github.com/akiver/boiler-writter

Thank you. Actually later I found that Valve has an official wheel for python on Github and I thought it's suitable for my project.
The official one is here: https://github.com/ValvePython/csgo
