### ISSUE TITLE
Running in Wine on Linux

### ISSUE THREAD

**Issue by GenocideStomper** [akiver/CSGO-Demos-Manager#533]
I enjoyed using this program when on Windows. I've since migrated to Linux some time ago, and now I'm looking into getting this to work on Linux through Wine.
I'm fully aware that the developer only supports Windows and don't expect support with this issue, however I hope maybe someone in the community has this running through Wine or perhaps has any pointers.

Based on the message "*CSGO Demos Manager requires .NET Framework 4.5 and Visual C++ Redistributable for Visual Studio 2015" on the main website, I've tried the following:

1. Create a new Wine prefix
2. `winetricks dotnet45`
3. `winetricks vcrun2015`
4. Install the application
5. Run the application from Program Files

The application installs successfully, however when I run the application, I get the following error in the terminal:

> 002d:err:ole:CoGetContextToken apartment not initialised
> 0009:err:eventlog:ReportEventW L"Application: CSGODemosManager.exe\nFramework Version: v4.0.30319\nDescription: The application requested process termination through System.Environment.FailFast(string message).\nMessage: Unrecoverable system error.\nStack:\n   at System.Environment.FailFast(System.String)\n   at MS.Inter"...

Thank you in advance for any suggestions.

**Comment by BlueMarch42** [comment]
Hello @GenocideStomper, may I ask what is the complete compiled error when you ran it using the above instructions? I have a friend who wants to know the complete error so he could try idk creating a fork for linux? As he is the same as you who migrated from windows to linux usertype.

**Comment by GenocideStomper** [comment]
@BlueMarch42  I actually managed to install the latest version v2.14.3 in Lutris.

I used lutris-GE-Proton8-5-x86_64.

Installed the following through winetricks:
- dotnet40
- dotnet45
- dotnet461
- dotnet462
- dotnet46
- vcrun2015

What works: loading demos, analyzing demos, taskbar icon
What doesn't work: the link to CSGO doesn't work so can't watch highlights, etc.
What's a bit weird: the initial loading of the demos list takes a while, the borders of the UI are a bit janky especially when moving the window.

If your friend can figure out how to forward the custom launch commands for CSGO to the Linux version of CSGO, then please let me know.

**Comment by GenocideStomper** [comment]
Gonna close the issue because it works for the most part.
