### ISSUE TITLE
analyzing demo bug

### ISSUE THREAD

**Issue by xep1x** [akiver/CSGO-Demos-Manager#536]
I had such a problem, I recorded a demo with bots (don't ask why), but the program just doesn't see this demo, I understand that it is intended only for analyzing games with real people, but is there any way to get around this barrier so that it can analyze bot games?

demo: https://drive.google.com/file/d/1ullTGgXcwcIh3HC9uh5BnBAuXDjbwUa7/view?usp=sharing

**Comment by akiver** [comment]
Hi sorry for the delay, do you mean you can't *see* it in the app or can't *analyze* it?  
The demo link is dead.
