### ISSUE TITLE
Demos that are not complete shows that they are too old when analyzing

### ISSUE THREAD

**Issue by crashzk** [akiver/CSGO-Demos-Manager#537]
I have a server and I downloaded a demo of it, but I did it before finishing the game.

Whenever I download demos like this, without finishing the game and try to play it through CSGO Demos Manager it gives an error saying that the demo is too old, as in the screenshot below:
![image](https://user-images.githubusercontent.com/32937653/136844771-295586a9-44c3-409f-8369-e9afc1266b7e.png)

But this demo is not old, it was downloaded today, and it was created today too. (10/11/2021)

https://www.mediafire.com/file/kh9u9no7mobv40v/_2021-10-11-1425-6a89-de_mirage-luminositygaming-vs-gambitesports.zip/file

**Comment by StyxOne777** [comment]
same Problem diffrent time...

**Comment by akiver** [comment]
The demo is corrupted and even the game crash when playing the demo (around the tick 149000).
There is nothing we can't do.
