### ISSUE TITLE
Highlights option not working

### ISSUE THREAD

**Issue by Kfadro** [akiver/CSGO-Demos-Manager#538]
After downloading a demo (Faceit) when i want to pick Highlights of my match. CS:GO turns on but the demo just starts as if i turned it on 
normally from warmup.
I dont know what to do or how to make it work. I have tried ways to fix it or just try over and over again but that doesnt always work.
I hope there is a fix to this issue. 
Good night.

**Comment by akiver** [comment]
Did you follow the instructions here https://csgo-demo-manager.com/docs/watch#watch-highlow?
