### ISSUE TITLE
Add an option to not search for last rank

### ISSUE THREAD

**Issue by sambooo** [akiver/CSGO-Demos-Manager#54]
I have a huge mm demo archive and every time I switch player there is a extremely long wait while their rank is updated. Since I don't really care about ranks, can you let us disable this process?

Also, during the search memory usage goes from 500MB to upwards of 1300MB for me. Checking against about 550 demos if that helps.

**Comment by akiver** [comment]
Rank detection has been improved, check 1d740f48937f26621b68d9f45877278fdb109478
I don't think an option is necessary now.
