### ISSUE TITLE
Option to convert .dem to .avi/.mp4

### ISSUE THREAD

**Issue by crashzk** [akiver/CSGO-Demos-Manager#541]
Would it be possible to implement or do you have any option to automatically convert the demos to another format? MP4, AVI, even a direct conversion to Youtube or other platforms?

**Comment by sheharyaar** [comment]
A .dem can be converted only by opening the demo in game and recording and then generating the raw files and then processing those raw files using ffmpeg or similar utility. For this there is option within the application. This application is not cloud based so it opens the demos in the user's system itself. Had this been a cloud service, direct conversion would have been possible.

I hope this helps you understand. Please close the issue if you are satisfied.
Have a great day.
