### ISSUE TITLE
[Update Player position every 1 second] and [Restart second timer ] IN JSON

### ISSUE THREAD

**Issue by karingijs2727** [akiver/CSGO-Demos-Manager#546]
Hello is there a possibility to update player position every 1 second on JSON
And restart seconds every new round in JSON
Thanks!

**Comment by lilgandhi1199** [comment]
If you look at players_hurted under each player or every round inside the JSONs. They already put in player positions to that of which there are numerous samples.

            "round_number": 3,
            "victim_x": 1513.70374,
            "victim_y": 1481.544,
            "attacker_x": 1011.90234,
            "attacker_y": 921.877441,
            "tick": 18117,
            "seconds": 283.557037

**Comment by lilgandhi1199** [comment]
Although you may have hope yet. In v3 he is releasing a cool 2D replay tool for an entire demo to watch the action inside his app.
Which of course has every player's position though I doubt it will be logged like you were hoping to see.

**Comment by akiver** [comment]
I'm not sure to understand your question but players' positions are not exported in the JSON export.
