### ISSUE TITLE
Download button is not work

### ISSUE THREAD

**Issue by minion1122** [akiver/CSGO-Demos-Manager#549]
**Hello!**
I found that when I want to download my demos, I click the download button, but it is ineffective.
I tried to solve this problem, but I found I couldn't.
Hope you can solve my problem thanks!

**Comment by lilgandhi1199** [comment]
Sometimes depending on how you launch the program until you restart it it will not attempt to download any demos.
Have you ever got it working before? You need to be logged into steam
