### ISSUE TITLE
Does it support X-rays？If yes, how to enable it?

### ISSUE THREAD

**Issue by jiaokele** [akiver/CSGO-Demos-Manager#554]
Does it support X-rays？If yes, how to enable it?
支持开启X光吗？如何启用？
thanks

**Comment by akiver** [comment]
X-Ray is a CSGO feature, not a CSGO Demo Manager one.
The CSGO command to enable it is `spec_show_xray 1`, so you can:
- Type it in the console when CSGO is running
- Add it into your `autoexec.cfg` so it's always enabled when CSGO is started
- If it's for the movie feature, you can add it to the CFG panel
