### ISSUE TITLE
ESEA demos corrupt

### ISSUE THREAD

**Issue by HiyaNoot** [akiver/CSGO-Demos-Manager#559]
Frequently, ESEA demos become corrupt/"missing data" when going through analysis.
On other occasions, RWS data is wrong, with a multitude of incorrect data that needs to amended (despite no indication that said file is corrupt)

I don't have this issue with FACEIT demos, only a recurring issue with demos from ESEA

Due to incorrect data being processed, this leads to other metrics in the exported .xlsx file to be wrong, as these metrics have a dependency on other figures to be correct

This may be an issue with ESEA's demo system, but I cannot be certain

Is their also a way to view how other metrics (such as HLTV 1.0, RWS, etc) are calculated using CSGO-Demos-Manager

**Comment by akiver** [comment]
> ESEA demos become corrupt/"missing data"

I guess it's still the case but yeah it's an old issue. Demos from ESEA may be corrupted and it's probably related to their recording system (server plugin/how the recording is stopped). Unfortunately, there is nothing we can do about it.

> On other occasions, RWS data is wrong

If you have demos with data that are definitely wrong, please upload them, it will help understand the issue.
Please note that e-sport companies have their own system to extract players' stats (demos, server logs, server plugins...), and even if they use demos to extract stats, they probably have their own program and thus algorithm variances. There is a small note about it here https://csgo-demo-manager.com/docs/analyze#esea-rws.

> Is their also a way to view how other metrics (such as HLTV 1.0, RWS, etc) are calculated using CSGO-Demos-Manager

The demos analyzer uses formulas described in the articles [HLTV 1.0](https://web.archive.org/web/20170427062206/http://www.hltv.org/?pageid=242&eventid=0) and [ESEA RWS](https://support.esea.net/hc/en-us/articles/360008740634).
You can find the implementation in the source code, here is the [HLTV 1.0](https://github.com/akiver/CSGO-Demos-Manager/blob/master/Services/Concrete/Analyzer/DemoAnalyzer.cs#L1823) for example.
