### ISSUE TITLE
HE Grenade kill not shown in Stats but is shown in round?

### ISSUE THREAD

**Issue by opello** [akiver/CSGO-Demos-Manager#56]
[Here are some screenshots](http://imgur.com/a/wkjRq) showing what happened.

I got an HE kill but it isn't showing on the overall stats screen.  Should I put the demo somewhere or can I dig into any other state to help investigate why this is happening?

**Comment by muratsu** [comment]
Im sure sharing the demo file always help :)

**Comment by opello** [comment]
steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-KayOL-A7MNT-LRGnp-3jh5A-jAhaB

If that doesn't work:
https://dl.dropboxusercontent.com/u/7256610/csgo/match730_003122327688879013953_0745863552_125.7z
