### ISSUE TITLE
Players not in the correct teams

### ISSUE THREAD

**Issue by Lutchas** [akiver/CSGO-Demos-Manager#562]
Hello. My name is Lucas, and im from Brazil. I've a problem and i dont know if it is from csgo demos manager software or the recording demos server.
The issue: the players dont appear in the correct teams. For example:
Team 1 - A, B, C, D, E
Team 2 - F, G, H, I, J

When i open the demo in cs go demos manager, it is mixed.
Team 1 - F, G, C, D, E
Team 2 - A, B, H, I, J

Could you help me?

**Comment by akiver** [comment]
Could you please upload the demo?
