### ISSUE TITLE
Highest HS% Analysis error

### ISSUE THREAD

**Issue by LMXXH** [akiver/CSGO-Demos-Manager#567]
Error in analysis record statistics

**Comment by LMXXH** [comment]
The calculated value is not the actual highest value

**Comment by LMXXH** [comment]
![image](https://user-images.githubusercontent.com/84369032/180372728-a41809ce-a6f5-4bc3-b14b-956d016b1ef9.png)

**Comment by akiver** [comment]
fixed with https://github.com/akiver/CSGO-Demos-Manager/pull/566
