### ISSUE TITLE
Video Rendering : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by itskrmb** [akiver/CSGO-Demos-Manager#568]
So there's this issue i'm having. It's the first time it's happening.
I wanted to generate a video of some frags, the 1st part where it opens CS:GO was working like usual, but then when comes the second part, where it opens VirtualDub, instead i had this error message.
I didn't use the demo manager since weeks, so to make sure, i uninstalled everything and reinstalled the latest versions of the manager, HLAE and vdub, but still.
Happened with MM, wingman and faceit demos.

![Capture d’écran (43)](https://user-images.githubusercontent.com/73650765/183286289-3851166e-d57c-496a-8cbd-5ad2b23f65c6.png)

**Comment by Rozadj92** [comment]
Same problem
