### ISSUE TITLE
Searching account's last rank is slow

### ISSUE THREAD

**Issue by ijagberg** [akiver/CSGO-Demos-Manager#57]
Whenever you choose a new account to check stats for, the process of looking through the demos to see its most recent rank can take several seconds (or much more if you have a lot of demos). Adding an option to skip the process would be a good solution (ignoring the ranks), since a lot of people don't care what their rank is, and just want the stats :)

**Comment by akiver** [comment]
Rank detection has been improved, check 1d740f48937f26621b68d9f45877278fdb109478
