### ISSUE TITLE
Is it possible to avoid restarting the game when trying to watch another event within the same demo?

### ISSUE THREAD

**Issue by ryefig** [akiver/CSGO-Demos-Manager#577]
Is it possible to not restart the CSGO when clicking 'Watch' button within the same demo if this demo is already running?

**Comment by Xiguinilster** [comment]
If you can, you just have to use the csgo console.
You have 2 options shift+f2 and you are looking for the path where you have the demo hosted.
option 2 you place the demo in the rude by default of the game and in the console colossal playdemo "name of the demo"

**Comment by ryefig** [comment]
> If you can, you just have to use the csgo console. You have 2 options shift+f2 and you are looking for the path where you have the demo hosted. option 2 you place the demo in the rude by default of the game and in the console colossal playdemo "name of the demo"

I think this is not what I've meant. 
When I open some type of an event (grenades thrown) and want to watch multiple instances, I would click on the 'Watch' button and the 'Watch' for another which causes current instance of 'csgo.exe' to close and open again with the new moment. I was asking if we could avoid this. 

At least, you could give a user an option to copy 'demo_gotick' command to view this very event, instead of 'Watch' feature that will relaunch the game process if it's already opened.

**Comment by ryefig** [comment]
Wow, gratz on this huge update. Can't wait to test it out
