### ISSUE TITLE
Starting not from the beginning of a clutch when using 'Watch'

### ISSUE THREAD

**Issue by ryefig** [akiver/CSGO-Demos-Manager#578]
When you start to watch a clutch involving a bomb defuse you can miss some early kills of the clutch

**Comment by akiver** [comment]
Which "Watch" button in the app do you use?  
Could you please send a demo with steps to reproduce the issue?

**Comment by ryefig** [comment]
> Which "Watch" button in the app do you use?

- Choose demo
- Go for player's page from scoreboard
- Go to 'Clutches'
- Click on 'Watch
This very demo is from FACEIT. If you contact me directly I can reply with Google Drive link

**Comment by akiver** [comment]
Thanks for the help! It will be fixed in the next version.
