### ISSUE TITLE
A way to navigate through demo faster 

### ISSUE THREAD

**Issue by ryefig** [akiver/CSGO-Demos-Manager#580]
Is the current way to go to the specific moment of a demo is launching csgo.exe with specific launch options? So if you want to watch another event each time you have to restart the game.
Maybe there is a more direct approach with sending 'demo_gototick' to the game's console? I understand that the solution will not be VAC-safe but there is "-insecure" option in CSGO to prevent a cheat ban if user unexpectedly tries to connect to a VAC server.

**Comment by akiver** [comment]
Could you confirm it's a duplicate of https://github.com/akiver/CSGO-Demos-Manager/issues/577?
The goal is to avoid restarting the game right?
