### ISSUE TITLE
Issues with a few demos from our plugin, in particular Ancient

### ISSUE THREAD

**Issue by MischiefCS** [akiver/CSGO-Demos-Manager#583]
I have managed to parse over 1000 demos through demos manager with no issue however we often seem to have issues on ancient for some reason. The demos are fully complete and show no signs of corruption.

Some demos I had to hand that wont analyze.

http://demos.epiclan.co.uk/epic36/Main/upper-final/%5b9881%5d-%5b20220709162028%5d-elimination-upperfinal-ava_mix-vs-empskidsyaroslavjaustere=kicked-%5b20220709-185146%5d-%5bde_ancient%5d-%5b20043%5d.dem

http://demos.epiclan.co.uk/epic36/Main/round-5/%5b9662%5d-%5b20220708153145%5d-group-groupa-temperate-vs-milkmenacademy-%5b20220708-165901%5d-%5bde_ancient%5d-%5b19620%5d.dem

http://demos.epiclan.co.uk/epic36/Main/lower-quarter-final/%5b9870%5d-%5b20220709093153%5d-elimination-lbround21-blvkhvnd-vs-milkmenacademy-%5b20220709-101613%5d-%5bde_ancient%5d-%5b20008%5d.dem

As we're an un supported plugin I understand this may not be resolved but any support would be greatly appreciated. An outstanding tool and really appreciate its development.

**Comment by akiver** [comment]
Fixed in https://github.com/akiver/CSGO-Demos-Manager/commit/e24c1cef304450eb101900ab0e6cc097078ebdbd
