### ISSUE TITLE
Suggestion: Add ESEA's Round Win Shares metric

### ISSUE THREAD

**Issue by EnviousElitist** [akiver/CSGO-Demos-Manager#59]
How about adding ESEA's RWS along side the HLTV Rating?

https://play.esea.net/index.php?s=support&d=faq&id=212

It's a bit different as it is calculated per round that is won.  Basically, when a team wins a round, 100 Win Shares are divided up based on how much damager was given for each player that round.  I think it's a good alternative to the HLTV Rating, which can be inflated by lower impact frags (e.g. exit frags).

**Comment by 0BuRner** [comment]
Yep great idea. It wasn't possible to compute it some time ago. Damage dealt is a fairly new info we can get from demo =)

**Comment by 0BuRner** [comment]
I'm working on this =)
