### ISSUE TITLE
Does not find demos in folder anymore

### ISSUE THREAD

**Issue by JanEricNitschke** [akiver/CSGO-Demos-Manager#591]
I just upgraded to the most recent version. However now the demo manager only find my demos in the csgo/replays folder but not in my own d:/csgo/demos folder that i have also added.

It just shows: "No demos found for this account in this folder"

**Comment by akiver** [comment]
Which version did you have before the upgrade?
You could try to delete "cache" files, see https://csgo-demo-manager.com/docs/general#app-crash for instructions

**Comment by JanEricNitschke** [comment]
Seems it was 2.13.15.0. Thats at leasts the other folder in the `C:\Users\YOU USERNAME\AppData\Local\AkiVer`

it shows them now again after deleting all the demo files in the `Roaming` folder. Sadly now i have to re-analyze 800 demos ;(

**Comment by akiver** [comment]
Sorry but upgrading to 2.14.x require to re-analyze all demos anyway (internal breaking changes).
