### ISSUE TITLE
not loading demos + not launching csgo

### ISSUE THREAD

**Issue by TheDanee** [akiver/CSGO-Demos-Manager#593]
Hi guys,

Ever since the new update I get 2 error messages.

Whenever i click "Show all demos" I get an error saying value X cant me converted to type 'Core.Models.Events.ChatMessage'. X being a player name. Error shared below. 

EDIT: posted wrong picture
![image](https://user-images.githubusercontent.com/118399570/202303512-4dfa3d89-f5b7-4701-8564-ad71fb012ac5.png)

EDIT: Added the following 2 screenshots:

![image](https://user-images.githubusercontent.com/118399570/202304308-e236ff55-5497-4cc9-a6fb-feae7af55a4f.png)

![image](https://user-images.githubusercontent.com/118399570/202304391-417d4c71-8257-4e61-9496-0077a8d4fb26.png)

Also, when I load a demo (highlights, player POV) I get the error below. Error happens 4 times with the following DLLs: icui18n and v8 (both 2 times).

![image](https://user-images.githubusercontent.com/118399570/202302850-cf49843e-864e-48cb-93cb-2f8b360bc6c2.png)

Error log attached to this post.

Anybody know how to fix this? Thanks a lot!

[errors.log](https://github.com/akiver/CSGO-Demos-Manager/files/10025979/errors.log)

**Comment by akiver** [comment]
it could be an upgrade issue similar to https://github.com/akiver/CSGO-Demos-Manager/issues/591#issuecomment-1312714347, could you try to [clear the app files](https://csgo-demo-manager.com/docs/general#app-crash) please?

**Comment by TheDanee** [comment]
Done, deleting the map in roaming solved the isssue.

Thanks!
