### ISSUE TITLE
BUG : CSGO Demo manager can't open csgo

### ISSUE THREAD

**Issue by BiNoXTv** [akiver/CSGO-Demos-Manager#594]
![Capture](https://user-images.githubusercontent.com/80566829/202882736-315ebab9-334f-4637-95ad-6142c9f31c4b.PNG)
Hi, CSGO is not opening when I press watch. I've tried several demos and they all to this. 

Error
Failed to start CSGO.
Error: Access is denied.

**Comment by pqt2p1** [comment]
I got the same problem a few minutes ago after update csgo demo manager, the way to fix is turn off any anti-cheat (FACEIT AC), and run the app as administrator
