### ISSUE TITLE
Demo analyze error

### ISSUE THREAD

**Issue by BBftb** [akiver/CSGO-Demos-Manager#596]
The following content by machine translation, may be different from the original meaning!

When using, click Analyze Demo, and the software returns an error and marks my demo as an error.

![1](https://user-images.githubusercontent.com/97345027/205433709-39e11b5b-cbc6-44e4-b472-50debf68a9a2.png)

**Comment by akiver** [comment]
Please read the [doc](https://csgo-demo-manager.com/docs/about#provider-support) and make sure this demo comes from a supported source as mentioned in the error message.
If the demo comes from a supported source please upload the demo.
