### ISSUE TITLE
Hitgroup 8

### ISSUE THREAD

**Issue by fenriscs** [akiver/CSGO-Demos-Manager#598]
Hi, I'm wondering what hitgroup 8 means in the json export.

I have looked into the official documentation and found this:
// ---------------------------
//  Hit Group standards
// ---------------------------
#define	HITGROUP_GENERIC	0
#define	HITGROUP_HEAD		1
#define	HITGROUP_CHEST		2
#define	HITGROUP_STOMACH	3
#define	HITGROUP_LEFTARM	4	
#define	HITGROUP_RIGHTARM	5
#define	HITGROUP_LEFTLEG	6
#define	HITGROUP_RIGHTLEG	7
#define	HITGROUP_GEAR		10			// alerts NPC, but doesn't do damage or bleed (1/100th damage)

**Comment by akiver** [comment]
Could you send a link to download the demo, please?

I'm not sure but it's probably a neck shot.

**Comment by fenriscs** [comment]
https://demos-asia-southeast1.faceit-cdn.net/csgo/1-001496ac-96ec-4a54-9853-149e10683eab-1-1.dem.gz

Maybe you are right. In this update post Valve is talking about a new hitbox. https://blog.counter-strike.net/index.php/2018/05/20417/
That could explain, why it isn't in the documentation. But it does only 13 damage AND 7 armor damage on short distance with Glock-18 and in the post they told that a neckshot is considering as a headshot. When I look at the demo, it could be a shot in the back. I think the armor is not protection the neck but we are talking about digital hitboxes, so maybe the game struggles with the realistic scenario.

The hit with hitgroup 8 is in the first round from the player kiritom12 backside close to kitchen.
