### ISSUE TITLE
Crash when searching for account's last rank

### ISSUE THREAD

**Issue by SebastianReitzner** [akiver/CSGO-Demos-Manager#599]
So, I've used your cool tool for a while now, sure it has a few bugs, sadly now its the first time stuck crashing repeatedly.

I had a longer break until this week, the last demo before that was from 2021/09/19, then I played two games this week 2022/12/05:
![image](https://user-images.githubusercontent.com/36883233/206269595-0844b4ac-aca8-470a-82d4-cbba6b80779a.png)

I downloaded the games from this week without analyzing them, then selected my Steam account as a filter, then this happened:
![image](https://user-images.githubusercontent.com/36883233/206269768-510edafc-6b03-4598-8040-b09aa7dab0ad.png)

Sadly I cannot access the errors.log file from the settings (also didn't find it in the install folder) because anytime I start the application it will be searching for my rank before I can do anything and crash again.

Before this week I got unranked due to my break, but I ranked back in, I assume this is due to me not analyzing the demo files before selecting my account?

**Comment by akiver** [comment]
Could you please try to clean up "cache" files? Instructions are [here](https://csgo-demo-manager.com/docs/general#app-crash)
It's undoubtedly an app upgrade issue similar to this issue https://github.com/akiver/CSGO-Demos-Manager/issues/593, you have to delete cache files and re-analyze demos.

The next major version will handle upgrades in a better way and I may take some time to improve V2 upgrades in the meantime.

**Comment by SebastianReitzner** [comment]
The first step, deleting all folders in C:\Users\YOU USERNAME\AppData\Local\AkiVer allowed me to start the application without crashing again! Thanks!

After that I analyzed the last two matches which I hadn't previously, and then selected my account, then however the following error shows again:
![image](https://user-images.githubusercontent.com/36883233/206560129-3c7222dc-07fe-4bb4-ab7a-a99a94570f2a.png)

After pressing OK it is stuck searching for the last rank:
![image](https://user-images.githubusercontent.com/36883233/206560633-6f4225d4-6818-47f6-967e-ecc93d9de983.png)

After I reopened the application to get rid of the 'Searching for rank' (additionally the software was not responsive after I selected the account), I again get that error:
![image](https://user-images.githubusercontent.com/36883233/206561193-ab74158d-40f0-4513-835b-080fdc481755.png)

After, again, deleting the folders I tried just re-analyzing everything, but then it will crash directly with the same error..
![image](https://user-images.githubusercontent.com/36883233/206561467-afc9890b-e285-4aba-8e14-0271f028e84c.png)

Now I know where the error.log is, 
[errors.log](https://github.com/akiver/CSGO-Demos-Manager/files/10189263/errors.log)
so I will just attach that right here as well.

**Comment by akiver** [comment]
You must delete all files in `C:\Users\USERNAME\AppData\Roaming\AkiVer\CSGO Demos Manager` (not `C:\Users\YOU USERNAME\AppData\Local\AkiVer`).

The error is because the data in the files come from an old app version incompatible with the last version. It's trying to convert chat messages from a string (old format) to an object (new format).

**Comment by SebastianReitzner** [comment]
That worked, thanks!
