### ISSUE TITLE
Suggestion : add SoStrong's impact rating

### ISSUE THREAD

**Issue by 0BuRner** [akiver/CSGO-Demos-Manager#60]
All data available here : https://www.sostronk.com/blog/impact-rating-feature-announcement

**Comment by Calak** [comment]
Quoted from the above link: "This is definitely NOT the final iteration of the Impact Rating. We will be testing it out and of course be open to feedback on how to improve this system."

So,  yes,  that's a great idea but not yet totally stable.

**Comment by 0BuRner** [comment]
Updated : https://www.sostronk.com/blog/updated-impact-rating

**Comment by 0BuRner** [comment]
I'm working on it right now. I'll create a pull request when done

**Comment by akiver** [comment]
Closing it, SoStronk seems down.
