### ISSUE TITLE
Duration input not visible on low screen resolution

### ISSUE THREAD

**Issue by Karnav-Thakur** [akiver/CSGO-Demos-Manager#607]
![image](https://user-images.githubusercontent.com/80342673/213363256-1a942805-c161-4cf2-a581-c20aa5846a4f.png)

**Comment by GenericUserNameGoesHere** [comment]
You should be able to see it on the default page, If not the column may need enabling in Settings>Columns and tick the box labelled "Duration".

Duration column should be visible as it is in the screenshot below

![exampleDemoManager](https://user-images.githubusercontent.com/29975453/215258446-eee63a54-66b0-4af3-995d-402a12bf04a3.png)
