### ISSUE TITLE
Round details missing or cannot be analyze, pls help

### ISSUE THREAD

**Issue by Cmon-TLg** [akiver/CSGO-Demos-Manager#608]
![image](https://user-images.githubusercontent.com/124756568/217430207-f842a9fd-dea1-47ef-ae71-8b56899b4d31.png)
I've try to analyze and switching source but it cannot show the round detail
the demo file is from my server
actually, it just happen with the new file I download form Jan

**Comment by akiver** [comment]
> the demo file is from my server

https://csgo-demo-manager.com/docs/about#provider-support
