### ISSUE TITLE
did i have to delete all my demos for this error?

### ISSUE THREAD

**Issue by LIINE33** [akiver/CSGO-Demos-Manager#609]
![c8c40e9c7e3b0f3f1b5d7fa35a58abc](https://user-images.githubusercontent.com/126400388/221415850-b6284587-11e4-4e31-8a71-ee42ce6a8d59.png)

**Comment by akiver** [comment]
Same as https://github.com/akiver/CSGO-Demos-Manager/issues/599#issuecomment-1366083947
