### ISSUE TITLE
Suggestion: Add button to copy demo path to clipboard for playback

### ISSUE THREAD

**Issue by flare561** [akiver/CSGO-Demos-Manager#61]
Using the watch demo button to launch csgo gives me massive frame drops with faceit demos, if there were a button to click that would copy `playdemo "path to demo"` to the clipboard, to make it easy to just copy paste it into the console instead of having to find the file and type the big long string faceit uses for demo names

**Comment by Calak** [comment]
Or maybe a "copy file path to clipboard"  as context menu in the demos list.
