### ISSUE TITLE
GOTV demos gets Corrupted when players use !forceready commands

### ISSUE THREAD

**Issue by Schneider59** [akiver/CSGO-Demos-Manager#620]
Hallo - demos from GOTV has corrupted-status, when players use !forceready commands, to start the game.
Changing the source to faceit, helps for some data, but not all like: rounds-data, 1k etc in rounds and more.
I can summit a demo if you like.

**Comment by akiver** [comment]
Is it an eBot demo? Could you upload an affected demo please?

**Comment by Schneider59** [comment]
Where do you wan't me to upload the demos to?

**Comment by Schneider59** [comment]
I upload to google drive - hope you can get it:
1) https://drive.google.com/file/d/19mtnQhoMiIg2wFwKvenllabVvRo8L6_N/view
This is a corrupted one

2) https://drive.google.com/file/d/19iKNmrFaRAB6HGO-IxlP0kYH848_-ntj/view
This is one from the same bot, but not corrupted.

**Comment by Schneider59** [comment]
Anything you need from me? :)

**Comment by Schneider59** [comment]
Anything @akiver

**Comment by akiver** [comment]
Hi @Schneider59,

The first demo has the same problem as many ESEA demos, the .dem file is "corrupted" at the end.
I checked, and it's not a parser problem, the end of the file contains malformed data.

These demos come from the sourcemod plugin https://github.com/splewis/get5, which is not officially supported (even if the demo is not corrupted you may have inaccurate data).
There is no plan to support officially Get5. As you noticed the best thing you can do is to change the source to "eBot", analyze the demo and remove the "corrupted" status.
I also tried this demo with the V3 of the app and it looks like there is no missing data despite the fact that Get5 is also not officially supported.

**Comment by ar1a** [comment]
What's stopping get5 demos from being supported - is this something I could PR?
