### ISSUE TITLE
Excel export shows first digit

### ISSUE THREAD

**Issue by PetterSelin** [akiver/CSGO-Demos-Manager#621]
Hi,

When I export a match to excel/calc/libreoffice, I can only see the first digit in the HLTV ranking ( or in fact in neither of the decimals are showing for any of the stats )

![Problem2](https://github.com/akiver/CSGO-Demos-Manager/assets/62980988/4083a63d-e22e-492d-9669-eb8646685e34)
![Problem1](https://github.com/akiver/CSGO-Demos-Manager/assets/62980988/67c79771-c5e6-41fc-a53d-3b60ad5c7652)

It´s strange, since it does not round of the numbers ( like if we had 0,994 that would make 1 ), but it more seems like it just takes the numbers before the decimal sign. 0,994 becomes 0 in the xlms. Or KAST=86,96 becomes (86 instead of 87, or the best thing is if it would stay at 86,96 )

**Comment by akiver** [comment]
Hello, are you sure it's not an issue with your spreadsheet application?
I tried with several demos, and I don't have the issue (I use LibreOffice Calc):
![export](https://github.com/akiver/CSGO-Demos-Manager/assets/1842524/96991fbe-db1c-40ca-9daf-645b0271910b)
