### ISSUE TITLE
Suspects tab not working anymore ?

### ISSUE THREAD

**Issue by djtomcat** [akiver/CSGO-Demos-Manager#622]
is there any problem with the suspects tab ? even when i reanalyze the demos all "reds" are gone and in the suspects (even with show only banned) is not working anymore :(

**Comment by Maz0o2** [comment]
Same Issue

**Comment by akiver** [comment]
Hi, I tested without any issues.

After analyzing a demo with 2 banned players, adding all players to the suspects and then going to the suspects tab:

![suspects](https://github.com/akiver/CSGO-Demos-Manager/assets/1842524/5d95a3ed-092f-4ead-9a52-39a284008a7a)

Clicking on "Show only banned" also work.

I'm not sure but maybe the Steam API was down when you tried, could you please upload your error log file? (Settings -> Misc -> Browse to errors file)

**Comment by akiver** [comment]
See https://github.com/akiver/CSGO-Demos-Manager/issues/623#issuecomment-1624129703
