### ISSUE TITLE
KPR and other stats are returning incorrect results

### ISSUE THREAD

**Issue by JesseMH** [akiver/CSGO-Demos-Manager#628]
For example, I [have a demo](https://cscdemos.nyc3.digitaloceanspaces.com/s11/M13/s11-M13-Triggermen-vs-TeamFlash-mid2081-2_-2023-07-19_02-13-43.zip) that shows 27 kills over 26 rounds and should calculate a KPR of 1.0384 or 1.04 rounded, but you show a KPR of 1.08.

**Comment by akiver** [comment]
This demo comes from a server using [https://github.com/splewis/get5](https://github.com/splewis/get5), which is [not supported](https://cs-demo-manager.com/docs/about#provider-support).
You can still analyze demos coming from get5 and change the demo's source to get better results but please don't expect perfect stats.
