### ISSUE TITLE
I dont saw demos list

### ISSUE THREAD

**Issue by jandoe111** [akiver/CSGO-Demos-Manager#63]
Hello

when i update to 2.4.1 i dont saw demo list. On version 2.3.4 (maybe, i dont remember) its work properly. I added csgo folders to the program. Any idea? 
http://i.imgur.com/eAQxO05.png
http://i.imgur.com/wPylKtM.png

btw. good job, keep going! ;) 
btw2. sry for my bad english

**Comment by akiver** [comment]
You may have a corrupted demo. You can try this:
1. Clear data cache from settings.
2. Move half of your demos into a temp folder until you find the one which cause the problem (if it's the case)

**Comment by akiver** [comment]
Should be fixed with the version 2.5.0.
