### ISSUE TITLE
startup errors

### ISSUE THREAD

**Issue by artstylee** [akiver/CSGO-Demos-Manager#630]
trying to watch demo 
getting this
windows 10x64

![Снимок](https://github.com/akiver/CSGO-Demos-Manager/assets/56781292/5471af92-5463-42d5-8ce1-2b1cc23b6fa9)
![2](https://github.com/akiver/CSGO-Demos-Manager/assets/56781292/ff8c1707-18d0-4aba-afed-deea969e00bc)
![3](https://github.com/akiver/CSGO-Demos-Manager/assets/56781292/dd7e1c38-cec9-4fbe-8e21-82f8c3a72e1c)
![4](https://github.com/akiver/CSGO-Demos-Manager/assets/56781292/6dfd7b51-5d67-47dc-bab4-31424caa0018)

**Comment by akiver** [comment]
The app only launches CSGO, only else. Those dialog errors are coming from the game, not the app.
Please make sure your game is up to date, and you are not running Steam with [admin rights](https://cs-demo-manager.com/docs/watch#steam-client-error)
