### ISSUE TITLE
Option to View all Smokes/Flashes

### ISSUE THREAD

**Issue by bott0r** [akiver/CSGO-Demos-Manager#64]
Could you include an option to view all smokes/flashes a player has thrown in a given demo.

**Comment by akiver** [comment]
I'm not sure to understand, you can already see which player thrown a specific stuff.

**Comment by bott0r** [comment]
lets say you'd like to see every flash the player "akiver" has thrown in a match. You can scroll through the lists of flashes and click on each individual flash. 

What I like to see is you click on show all flashes from player "akiver" and the demo starts with fast forward in-between each flash

**Comment by akiver** [comment]
added with 361de325f59ecbbb3b9bd476d51db3ccef0487f1
