### ISSUE TITLE
SQLite backend

### ISSUE THREAD

**Issue by felipe19930** [akiver/CSGO-Demos-Manager#690]
### What problem is this solving

Simplifying installation and usage for regular users.

### Proposed solution

Having a SQLite backend would simplify greatly the installation and usage for users.

SQLite is arguably lighter (disk space wise) than PostgreSQL, and doesn't require a server service running, or setting up passwords.

**Comment by H1ghSyst3m** [comment]
SQLite would be so good, because the database can then also be saved then if you have to change or reset computer. The Database would be portable then
