### ISSUE TITLE
Excel Export: Bug & Feature Request

### ISSUE THREAD

**Issue by MTWebSer** [akiver/CSGO-Demos-Manager#71]
Hi Akiver,

Firstly, thank you very much for this tool and the support is much appreciated.

I am playing around with the data exported from CSGO Demos Manager into Excel and noticed two things:

1) The team indicated as the 'Winner' is incorrect. IE:

- Team 1 Score = 16
- Team 2 Score = 12
- Winner = Team 2

This issue is found in the 'Winner' field of the 'General' sheet within the exported workbook.

2) Would you be able to also export the 'Date' of the match to a field within the 'General' sheet? 

I would like to offer more of a solution rather than just this post but I know nothing about C# , apologies for not bringing more to the table. 

Thanks,
Mike

**Comment by ReagentX** [comment]
You can fix this in the export manually by changing the winner column to a formula, `=IF(N2>O2,L2,M2)`, where 2 is the row of the first match. This can then be filled down to correct the misinformation.

**Comment by vontuxen** [comment]
Hey,

I'd love the DATE export too.

THX
VT
