### ISSUE TITLE
Demos not analyzing if wrong source selected

### ISSUE THREAD

**Issue by GuitarrasDeAmor** [akiver/CSGO-Demos-Manager#72]
Sometimes when demos are analyzed, they appear to get the wrong source and not analyze correctly. When this happens, it starts to run through the demo, then resets midway and shows a random number of rounds but no statistics as shown: http://i.imgur.com/l0IjhtW.jpg

These were ESEA demos - all my other ESEA demos have analyzed fine. When I switched the source to ESEA on these demos, they analyze correctly.

Just a small bug that caught me off guard initially as I didn't think of changing the source. Not sure if it is random or related to specific demos.

(Demo links at bottom)

**ORIGINAL POST:**
I have two demos (both from ESEA) that are not analyzing. One is on Cobblestone, one is on Overpass. When I press analyze from the main menu, they start to analyze and then seem to reset in the middle and show a random number of rounds at the top but no statistics. Same thing happens if I click and go into the demo itself. The rest of the demos I have downloaded from ESEA have worked and analyzed correctly. Both show up as Valve demos but I assume that is because they didn't finish analyzing. 

Re-downloading and renaming doesn't work. Clearing the demo cache doesn't work. Clearing the demo data doesn't work.

Image after analyzing: http://i.imgur.com/l0IjhtW.jpg

Demos located here:
https://play.esea.net/index.php?s=stats&d=match&id=6422057
https://play.esea.net/index.php?s=stats&d=match&id=6083745

**Comment by akiver** [comment]
Demos aren't available, what was their filename?
ESEA demos are detected by their name, it must contains "esea".
Unfortunately it's the only way to detect esea demos as they don't change others available demo's header data.

**Comment by GuitarrasDeAmor** [comment]
The files were renamed to something other than "esea_**" by myself. That makes sense, I think it is just more confusing than anything and took me a bit to figure out 'troubleshooting' it.
