### ISSUE TITLE
Excel Export shows incorrect Winner

### ISSUE THREAD

**Issue by ReagentX** [akiver/CSGO-Demos-Manager#74]
The Excel export shows incorrect information when determining the winner of a match. 

http://www.hltv.org/?pageid=28&demoid=20662 on Inferno will show Astralis even though NaVi clearly won.

You can fix this in the export by changing the winner column to a formula, `=IF(N2>O2,L2,M2)`, where 2 is the row of the first match. This can then be filled down to correct the misinformation.

**Comment by akiver** [comment]
fixed with 091261895fd5522e9afad5a1bd8bc9acbb5c602b
