### ISSUE TITLE
Demo with overtime has wrong results

### ISSUE THREAD

**Issue by skmasq** [akiver/CSGO-Demos-Manager#76]
Demo for this match: http://www.hltv.org/?pageid=28&demoid=20995
Demo: http://www.hltv.org/interfaces/download.php?demoid=20995

When analysed gives wrong results (actual results 23:25) shown 17 - 13:
![image](https://cloud.githubusercontent.com/assets/3149408/14853087/f626f93c-0c81-11e6-93d1-803e13875236.png)

**Comment by kimbadim** [comment]
I guess I have a similar error:
When analyzing a game between Cloud9 and Immortals [http://www.hltv.org/match/2305491-cloud9-immortals-ecs-season-2-north-america](url), it shows the first three overtimes correctly, but in the fourth (Cloud9 won it 4-0 and closed out the game 28-24) it says Immortals won the four rounds, even though the round details clearly show that Immortals couldn't have won these rounds
