### ISSUE TITLE
Program not Loading

### ISSUE THREAD

**Issue by KJP831** [akiver/CSGO-Demos-Manager#77]
I tried to reinstall the program but get the same issue of it saying it is open but nothing showing up besides the tab. http://prntscr.com/ayvfcs

**Comment by akiver** [comment]
Did you upgrade from a previous version or did you reinstall the same version?

Try to delete all folders within "C:\Users\YOUR USERNAME\AppData\Local\AkiVer".

**Comment by akiver** [comment]
Closed due to inactivity.
