### ISSUE TITLE
Error when downloading demo

### ISSUE THREAD

**Issue by TResult97** [akiver/CSGO-Demos-Manager#778]
### Describe the bug

Show "下载录像时发生了错误" when downloading the demo .
![snipaste_20240307_171852](https://github.com/akiver/cs-demo-manager/assets/13347605/d5d94062-5e3e-4e17-8ee1-d09fb97ffbbd)

### Demo links

http://replay234.wmsj.cn/730/003671641054563533002_1172106872.dem.bz2

### Steps to reproduce

1. Refresh demo list.
2. Select a demo and download it.
3. Error show at the end of the progress bar.

### Expected behavior

Download the demo

### How often does this bug happen?

Only once

### Log file

Thu, 07 Mar 2024 09:09:51 GMT | LOG | server | WS:: message with name add-download and uuid 3f2028a5-0db3-4f12-ac7a-64a262fe8339 received from renderer process
Thu, 07 Mar 2024 09:09:51 GMT | LOG | renderer | WS:: message with name "downloads-added" received from server
Thu, 07 Mar 2024 09:09:51 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:51 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:51 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:51 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:51 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:51 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:51 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:51 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:52 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:53 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:54 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:55 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:56 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-demo-progress" received from server
Thu, 07 Mar 2024 09:09:57 GMT | ERROR | server | TypeError: Cannot read properties of undefined (reading '0')
    at bits (C:\Users\Zhu\AppData\Local\Programs\cs-demo-manager\resources\node_modules\unbzip2-stream\lib\bit_iterator.js:30:29)
    at Object.Do.decompress (C:\Users\Zhu\AppData\Local\Programs\cs-demo-manager\resources\node_modules\unbzip2-stream\lib\bzip2.js:283:28)
    at decompressBlock (C:\Users\Zhu\AppData\Local\Programs\cs-demo-manager\resources\node_modules\unbzip2-stream\index.js:31:29)
    at decompressAndQueue (C:\Users\Zhu\AppData\Local\Programs\cs-demo-manager\resources\node_modules\unbzip2-stream\index.js:48:20)
    at Stream.<anonymous> (C:\Users\Zhu\AppData\Local\Programs\cs-demo-manager\resources\node_modules\unbzip2-stream\index.js:83:17)
    at _end (C:\Users\Zhu\AppData\Local\Programs\cs-demo-manager\resources\node_modules\through\index.js:65:9)
    at Stream.c.end (C:\Users\Zhu\AppData\Local\Programs\cs-demo-manager\resources\node_modules\through\index.js:74:5)
    at xZ.exports.endFn (node:internal/streams/pipeline:430:11)
    at Object.onceWrapper (node:events:628:28)
    at xZ.exports.emit (node:events:526:35)
Thu, 07 Mar 2024 09:09:57 GMT | LOG | renderer | WS:: message with name "download-error" received from server

### Environment information

Version: 3.3.1
OS: win32 x64 10.0.19045
Electron: 29.0.1
Chrome: 122.0.6261.57
Last database migrations:
v1 - 2023-12-03T11:14:48.661Z

**Comment by akiver** [comment]
The archive is corrupted so the demo is also corrupted.
There is nothing we can do to fix this, the game client can't even play it.
