### ISSUE TITLE
Include EFF (cevo) RWS (ESEA) and allow the ability to change threshold for Assists

### ISSUE THREAD

**Issue by bott0r** [akiver/CSGO-Demos-Manager#78]
It would be outstanding if you could include an EFF calculation (CEVO system) and an RWS calculation  (ESEA/ESL) alongside with the already implemented HLTV rating. Further it would be great to have the ability to set the thresholds for assists, e.g. ESEA utlizes 60 as a threshold while MM and Faceit use 50.

**Comment by 0BuRner** [comment]
Are you sure about these threshold values ? I think in MM its 45 not 50...
Could you share "official" link with datas about these differents calculation methods and the threshold you gave ?
Thx

**Comment by akiver** [comment]
I added ESEA RWS but results are not exactly the same as ESEA website.
It may be due to missing damages events or algorithm variances.

I can't add CEVO EFF as they keep it private.
BTW, threshold is 51+ damages on ESEA and 40 on valve servers (set by cs_AssistDamageThreshold).

**Comment by bott0r** [comment]
Thanks! again... my bad
