### ISSUE TITLE
[Suggestion] See An Accounts 2/3/4/5k Rounds From One Place

### ISSUE THREAD

**Issue by Tygon** [akiver/CSGO-Demos-Manager#80]
Currently if you want to see your aces for example you have to go through each demo, select your account and check if you got an ace on one of the rounds. On the account stats page there is a nice way of seeing how many aces you have gotten total but not where they were. It would be nice to be able to click on the 5k for example and see the round / demo details of that ace.

Same thing would also be really nice for clutches, although on a side note the clutches are shown in the player section of the match details without any real way of watching them or finding the round they occurred on.

**Comment by akiver** [comment]
When you select an account, data are filtered on this account.
So you can see how many 5K for example you had from the demos list.

I added a player view that allow to watch quickly clutches / kills.
