### ISSUE TITLE
i want to know how can i change language

### ISSUE THREAD

**Issue by BlingRabbit** [akiver/CSGO-Demos-Manager#85]
like title. i cant find any useful. icant translate to other language.
How should i start?

**Comment by akiver** [comment]
There is currently no translation system.
A good start point would be using resources files http://www.codeproject.com/Articles/123460/Simplest-Way-to-Implement-Multilingual-WPF-Applica

**Comment by akiver** [comment]
I added a translation system, you are free to translate it in your language.
More details are in the [readme](https://github.com/akiver/CSGO-Demos-Manager#translations)
