### ISSUE TITLE
Not responding when I not connected to the internet

### ISSUE THREAD

**Issue by GuilhermeShinti** [akiver/CSGO-Demos-Manager#87]
When I not connected to the internet the program dont find my demo folder and not work. Then, when i press settings button the program stop responding.

**Comment by akiver** [comment]
I cant' reproduce your problem.
Does csgo / steam is installed on the computer?
Did you add demos to your folders? (it may be due to a corrupted demo)
Did you move / remove folders or demos?
Any information will help.

Thanks

**Comment by akiver** [comment]
Closed due to inactivity.
