### ISSUE TITLE
Low level events

### ISSUE THREAD

**Issue by Ottunger** [akiver/CSGO-Demos-Manager#90]
Hi, for a project of my own, I'd like to be able to retrieve events from CSGO demo files, and your lib is great! However, it lacks events for when a netmessage is coming (https://github.com/alliedmodders/hl2sdk/blob/csgo/game/shared/usercmd.h).
Do you think it would be possible to subscribe to such event while parsing?

Many thanks,

**Comment by 0BuRner** [comment]
You should use the library used by CSGODM : https://github.com/StatsHelix/demoinfo ;-)

**Comment by Ottunger** [comment]
Thanks! Will ask its creator, or do some modifications on my own if he cannot help.
