### ISSUE TITLE
Mistake in /src/Services/DemosService.cs - Same demos are downloaded over and over again

### ISSUE THREAD

**Issue by KurrKurr** [akiver/CSGO-Demos-Manager#92]
Hi,

I also posted on reddit the problem with the MM demos, that get downloaded again and again. (see here: https://www.reddit.com/r/GlobalOffensive/comments/4iahwy/app_csgo_demos_manager_260_download_your_last_mm/d3xa2xj)

I think I found the mistake:
In this line https://github.com/akiver/CSGO-Demos-Manager/blob/master/src/Services/DemosService.cs#L1104
instead of
`if (fileList.Contains(demoName + ".dem") && fileList.Contains(demoName + ".info")) result = false;`
it needs to say
`if (fileList.Contains(demoName + ".dem") && fileList.Contains(demoName + ".dem.info")) result = false;`.

Since the ".info" files don't get found right now, it always downloads all demos again. The info files are named "match730_reservationid_tvport_serverip.dem.info" as is stated in the function above in line 1085 (GetDemoName).
But afterwards in function IsDownloadRequired, you check for files named "match730_reservationid_tvport_serverip.info".

Please fix this issue, so it doesn't always download the same files again and again.

Best regards,
KurrKurr

**Comment by KurrKurr** [comment]
Meanwhile, you can save the following few lines of batch script code into a file "whatever.bat", put it in the demos folder and make a shortcut to it on the desktop:

```
@ECHO OFF
FOR %%I IN (*.dem.info) DO (
    SET "demoName=%%~nI"
    SETLOCAL EnableDelayedExpansion
    COPY "%%I" "!demoName:.dem=.info!"
    ENDLOCAL
)
```

What it does is it simply takes all files named "<something>.dem.info", makes a copy and names this copy "<something>.info".
You now have the analysis information twice on your harddrive, but CSGO-DM now finds already existing demos and doesn't download everything again.

**Comment by akiver** [comment]
Thanks for reporting!
