### ISSUE TITLE
Total kill count is not equal to the sum of 1k,2k,3k,4k,5k

### ISSUE THREAD

**Issue by playcode001** [akiver/CSGO-Demos-Manager#93]
Total kill count is not equal to the sum of 1k,2k,3k,4k,5k.

e.g.
kills:23
1k:7, 2k:5, 3k:0, 4k:1, 5k:0

`7*1 + 2*5 + 3*0 + 4*1 + 5*0 = 21`
`23 not equal to 21 `

demo url:
http://d1.demo.5ewin.com/20160525/20160525205203d84709_de_cache.zip

**Comment by akiver** [comment]
I tested your demo.
You have to change the source to eBot to have the right result.
Your demo is corrupted, it looks like the analyze is ok but it's probably a problem related to the GOTV.
If you are using tv_autorecord, you should stop using it as some demos are corrupted because of it.
