### ISSUE TITLE
Stats should only calculate with the current selected folder

### ISSUE THREAD

**Issue by Skaronator** [akiver/CSGO-Demos-Manager#96]
For instance: If I press now the "Stats" button on top it should calculate the result of 8 matches
![image](https://cloud.githubusercontent.com/assets/2886913/16848245/254954e8-49f5-11e6-822d-d402185f14ea.png)
 but instead it'll show 31 matches. 8 from this folder + 23 demos from MM and 4 POV demos.

**Comment by akiver** [comment]
There is already an option to do it (from settings flyout).
