### ISSUE TITLE
HLTV rating and RWS rating wrong calculated

### ISSUE THREAD

**Issue by Skaronator** [akiver/CSGO-Demos-Manager#97]
I'm currently building a stats site for my team and notice some difference in the HLTV rating but I dont get the reason why.

HLTV Source: http://www.hltv.org/?pageid=242
CSGO Demo Manager Source: https://github.com/akiver/CSGO-Demos-Manager/blob/master/src/Services/Analyzer/DemoAnalyzer.cs#L1502-L1512

Player | CSGO Demo-Manager | My Calculation
------------ | ------------ | -------------
ME | 1.451 | 1.434
Mate1 | 1.692 | 1.663
Mate2 | 1.557 | 1.578
Mate3 | 0.98 | 0.986
Mate4 | 0.95 | 0.958

But lets focuse on my stats, the data is from the exported json file -> players -> [me]

Name | Value
------------ | ------------ | -------------
kill_count | 18
death_count | 9
5k_count | 0
4k_count | 1
3k_count | 0
2k_count | 2
1k_count | 10
round_count | 20
rating | 1.451

I calculated my rating twice, in Excle and in PHP and both get the same results, now I make a 3rd round and calculate it by hand:
```
KillRating = Kills/Rounds/AverageKPR
SurvivalRating = (Rounds-Deaths)/Rounds/AverageSPR
RoundsWithMultipleKillsRating = (1K + 4*2K + 9*3K + 16*4K + 25*5K)/Rounds/AverageRMK
```
```
KillRating = 18/20/0.679 = 1.325
SurvivalRating = (20-9)/20/0.317 = 1.735
RoundsWithMultipleKillsRating = (10 + 4*2 + 16*1)/20/1.277 = 1.331

Rating = (KillRating + 0.7*SurvivalRating + RoundsWithMultipleKillsRating)/2.7
Rating = 3.871/2.7 = 1.434
```
**1.434** again. Got the same result in Excel and the same in PHP. Something must be wrong with the exporter or the calculation.

**Comment by 0BuRner** [comment]
Weird indeed... Do you see anything wrong in the code ?
Do you have the same result in the app than in the json in term of data values (rounds, kills, etc...) ?

**Comment by Skaronator** [comment]
@0BuRner RWS Rating seems also wrong. The ESEA site say I've a RWS of **18.38** and the Demo Manager says I've a RWS of **17.58**

**Comment by akiver** [comment]
The hltv rating wasn't correctly updated at the end of the analyze, it's now fixed.

**Comment by Skaronator** [comment]
Thanks! Did you also check the wrong esea rws rating?

**Comment by akiver** [comment]
It's a known issue, I think esea register more or less damages than the demo contains.
It causes divergence between the app and the website (the result is nearly the same).
